### ISSUE TITLE
Wrongly labels transactions as 'invalid'

### ISSUE THREAD

**Issue by frohal** [iotaledger/iri#1018]
### Bug description
Newly updated nodes labels perfectly valid transactions as 'invalid' if they have too old timestamp for the updated node.
In an environment where users are told that they don't need to upgrade node unless they want to shrink DB-size, it is a wrong assumption that such tx'es are 'invalid'.  They just should not be stored in local db.

### Steps To Reproduce
1. Keep one node on 1.5.3 
2. Upgrade a nbr to 1.5.4
3. Let the 1.5.3-node forward som incoming transactions published prior to last snapshot.

### Expected behaviour
1.5.4-node should just disregard transactions without counting them as 'invalid'

### Actual behaviour
1.5.4-node will mark tx'es as 'invalid', and stats for 1.5.3-nbr will possibly lead to removal of nbr...

**Comment by TeeVeeEss** [comment]
I see the same behavior with my 1.5.3 node sending tx to a 1.5.4 nbr.

**Comment by alon-e** [comment]
>1.5.4-node will mark tx'es as 'invalid', and stats for 1.5.3-nbr will possibly lead to removal of nbr...

I agree that in this case transactions should not show up in the `getNeighbors` `invalidTransactions` count, and this can easily be changed by removing: https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/network/Node.java#L258

however, this will hurt the ability to spot a neighbor that is bombarding you with old transactions on purpose.

**Comment by GalRogozinski** [comment]
@alon-e 
Maybe we should introduce a different counter for this case?

**Comment by jakubcech** [comment]
Can we tell the difference just based on the timestamp, though?

**Comment by GalRogozinski** [comment]
If the error resulted from a stale timestamp we can tell
