### ISSUE TITLE
findTransactions missing exception

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#103]
{"command": "findTransactions", "address": ["12345"]}

{
  "hashes": [],
  "duration": 0
}

**Comment by alfredch** [comment]
Added input validation to release 1.1.3.9.
The invalid request (example above) returns HTTP code 400 and a JSON response:
{
"error": "Invalid params",
"duration": 0
}
In case of an exception in IRI core processing, the API returns HTTP code 500 and JSON response. Here an example:
{
"exception": "Invalid request payload: ''",
"duration": 0
}
