### ISSUE TITLE
As a developer, I want to retrieve the configuration of API limits on IRI nodes

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1038]
### Description
Developers need a way to discover how request size limits on APIs on an IRI node are configured.

Previous PR on this #760, we should now use the new configuration interfaces that will be part of 1.5.5 - `ApiConfiguration`. 

### Motivation
Developers need to be able to programmatically retrieve request limits on IRI nodes. For example request size limits as per #496 . 

### Requirements
1. As a developer, I call an endpoint on an IRI node. 
2. I get back an object with the value of the following parameters.
          - minRandomWalks;
          - maxRandomWalks;
          - maxFindTxs;
          - maxRequestList;
          - maxGetTrytes;
          - maxBodyLength;

### Other
Paging can be a follow-up later for specific endpoints.

### Implementation
I think this should be a separate endpoint, like in #760.

**Comment by legacycode** [comment]
See also #496 and #1200
