### ISSUE TITLE
As a developer, I want to be able to programmatically discover whether an IRI node support remote PoW

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1039]
### Description
Developers need a way to discover whether an IRI node supports remote proof of work. This can now be fulfilled in a not very nice way by making an empty `attachToTangle`  request as discussed in #854. This also logs an error on the node. 

The node doesn't have the API call on the remote limit list as well. 

### Motivation
Developers need a supported and documented way to programmmatically discover that a node supports remote PoW. 
Trinity currently needs this functionality and uses an empty `attachToTangle` call and has a dependency on the return results of that empty call. We should have a clear contract for this scenario. 

### Requirements
1. As a developer, I call an endpoint on an IRI node. 
2. I get a response a that explicitly states that a node supports or doesn't support remote PoW. 

### Implementation
As discussed in #854, this could be a value returned via `getNodeInfo`.

**Comment by kwek20** [comment]
@jakubcech I propose to return all the blocked commands instead of just "if we support PoW".
It could in the future be useful to programmatically find out if we support `addNeighbor` or others.

**Comment by jakubcech** [comment]
Regression test update: 
https://github.com/iotaledger/iri-regression/issues/61
