### ISSUE TITLE
add/removeNeighbors missing exception

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#107]
{"command": "removeNeighbors", "uris": 999}

{
  "exception": "java.lang.Double cannot be cast to java.util.List",
  "duration": 1
}

**Comment by alfredch** [comment]
In this case, the parameter value of "uris" should be an array of strings.
The example throws and exception:
{
"exception": "java.lang.Double cannot be cast to java.util.List",
"duration": 1
}
