### ISSUE TITLE
Networking refactoring

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1072]
### Description
We want to write a NIO based networking layer that utilizes proper queues.

### Motivation
1. Ability to kick-out a compromised/malfunctioning neighbor while preserving overall architecture performance. This means that a malfunctioning neighbor will only affect its own relationship with IRI node and will not affect how IRI treats other neighbors. 
2. Ability to add a new protocol at network layer without changing much of the code. Ideally a protocol interface, which defines Connect, Send, Receive, Disconnect methods. 
3. Enabling and enforcing global and per neighbor rate limits in both ingress and egress direction. Prioritizing new transactions over incoming requests.

**Comment by GalRogozinski** [comment]
Users are complaining that there is a problem of tethering to a peer over tcp that is solved by restart.
We should be mindful of this while refactoring
