### ISSUE TITLE
The wrong Hash type is used in several places of IRI

### ISSUE THREAD

**Issue by hmoog** [iotaledger/iri#1079]
### Bug description
The recently merged hash refactor uses the wrong kind of hashes in several places and should be checked again.

### Expected behaviour
https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/Snapshot.java#L86 should be an ADDRESS hash
https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/model/StateDiff.java#L25 should be an ADDRESS hash
https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/API.java#L999 should be a TRANSACTION hash (maybe? didnt examine the code enough to be 100% sure)

### Actual behaviour
The wrong hash types are used in several places.

### What should be done
Better check all the changed lines and verify that are really correct.

**Comment by alon-e** [comment]
https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/controllers/TransactionViewModel.java#L272
should this be `OBSOLETETAG` - well maybe also good to rename to `OBSOLETE_TAG`

similar task: make sure that `NULL_HASH` is only used in the context of a transaction - especially where equality is tested. (https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/model/Hash.java#L8)

**Comment by GalRogozinski** [comment]
Part of the scope of the issue will be to search the project for similar errors.

**Comment by hmoog** [comment]
i addressed the most obvious things in that PR already but we should double check the other parts of the code as well
