### ISSUE TITLE
Snapshot files should be at a different repository

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1080]
### Description
We want to transfer all the files that describe the state of a global snapshot to a git LFS repository.

### Motivation
Snapshot files are becoming increasingly large and they can surpass the maximal file size that git can store. This makes it hard to maintain our repository. Moving these problematic files to an LFS repository will solve the issue.

### Requirements
1. Move `snapshotMainnet.txt`, `snapshotMainnet.sig`, `snapshotTestnet.txt`, 
 and `previousEpochSpentAddresses` to the new repo.
2. When we build IRI those files should be pulled from the repo to their original location (`resources` directory).

**Comment by jakubcech** [comment]
For link: https://github.com/iotaledger/iri/issues/1003

**Comment by jakubcech** [comment]
iotaledger/snapshots repo is a good candidate

**Comment by GalRogozinski** [comment]
Now that we have the spent-addresses-db maybe we can close this?

**Comment by jakubcech** [comment]
Agree
