### ISSUE TITLE
attachToTangle missing exception

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#109]
{"command": "attachToTangle", "trunkTransaction": "999", "branchTransaction": "999", "minWeightMagnitude": 999, "trytes": ["999"]}

{
  "duration": 2
}

**Comment by alfredch** [comment]
Added input validation to release 1.1.3.9.
The invalid request (example above) returns HTTP code 400 and a JSON response:
{
"error": "Invalid trunkTransaction hash",
"duration": 0
}
In case of an exception in IRI core processing, the API returns HTTP code 500 and JSON response. Here an example:
{
"exception": "Invalid request payload: ''",
"duration": 0
}
