### ISSUE TITLE
Using Singleton to store configuration

### ISSUE THREAD

**Issue by stplaydog** [iotaledger/iri#1102]
### Description
Turn configuration object into Singleton.

### Motivation
Now, configurations are parsed from files and arguments, the issue is, it should be passed to different constructors for use. If we need the configuration information somewhere in the middle of the code, it's not possible unless writing functions to pass the configuration object in that place. Therefore making configuration as a Singleton is a improvement under this case.

### Requirements
Configuration.GetInstance()->getxxxxConfig()

### Am I planning to do it myself with a PR?
Yes

**Comment by GalRogozinski** [comment]
I am fine with injecting configuration for now
