### ISSUE TITLE
Publish/Subscribe and Push/Pull (i,e notifications)

### ISSUE THREAD

**Issue by paulhandy** [iotaledger/iri#111]
I think that it would be beneficial for clients to be able to request, for example, transactions that happen with address "A", and instead of needing to continuously ping the node for updates, let it push a notification to the device when it sees the transaction.
Also, for analytics purposes, it would be useful to be able to subscribe to what currently goes into the logs, rather than only printing them to the console.
Because it supports both TCP and IPC (even better for nodes run locally), and seeing as it's used in other crypto-currency projects (like bitcoin core and libbitcoin), I think that ZMQ would be a good candidate for this. Another alternative would be MQTT

**Comment by jakubcech** [comment]
Already implemented
