### ISSUE TITLE
IRI node sync features using IPFS folder

### ISSUE THREAD

**Issue by Fabryprog** [iotaledger/iri#1137]
### Description

I propose a feature to download database from an IPFS folder automatically. 

When it is going done IRI can switch automatically to peer2peer network.

### Motivation

IRI slower sync is a tipically problem.

Today common steps are:
1. stop iri
2. download database from a site (using curl?!?)
3. start iri
4. wait wait and wait

### Am I planning to do it myself with a PR?

yes, i can plan this feature to my TODOs

**Comment by Fabryprog** [comment]
I am thinking an embedded feature. Is isn't a personal solution

**Comment by GalRogozinski** [comment]
You will have to put a more detailed description to get a serious response

**Comment by Fabryprog** [comment]
@galrogozinski i am proposing to modify iri db initialization. The main idea is lighten main network using another structure (IPFS) to download iota database.

When download will be completed iri can start using main network!!!

Today this phase is a very slow operation!

**Comment by svenger87** [comment]
Imo downloading the full database snapshots is no longer needed when local-snapshots are introduced.

**Comment by Fabryprog** [comment]
@svenger87 when is it planned?

**Comment by jakubcech** [comment]
Some thorough internal and community testing is not far off. :) And yes, not only will you not need the full DB, the syncing/start up will be improved by quite a bit in the next version.

**Comment by Fabryprog** [comment]
Omg it is a fantastic news.

So... this issue is deprecated! :-)
