### ISSUE TITLE
Test the LOCAL_SNAPSHOTS_BASE_PATH flag

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1168]
### Description
General tests for the LOCAL_SNAPSHOTS_BASE_PATH flag. 

1. That file is actually created under the PATH.
2. What happens if snapshot path is absent after restart. 
3. Test different, non-default paths.
4. Test changing the path between node restarts. Node stops with one path, is started with a different one.

**Comment by alon-e** [comment]
@hmoog the base path doesn't act as one would expect. b/c the file naming: 
`<BASE>.snapshot.meta` - this means that in order to put the files in a folder, I need to explicitly add a `/`  and the files are "hidden"
```
--local-snapshots-base-path alon/
```

```
 ✗ ls alon
 ✗ ls -a alon
.  ..  .snapshot.meta  .snapshot.state

```

**Comment by alon-e** [comment]
@hmoog, also garbage collector name is still present in the code:
1. `.state.gc`
2. AsyncTransactionPruner (constants and docs)

**Comment by alon-e** [comment]
> 1. That file is actually created under the PATH.
> 2. What happens if snapshot path is absent after restart. 
> 3. Test different, non-default paths.
> 4. Test changing the path between node restarts. Node stops with one path, is started with a different one. 

All tests pass!
