### ISSUE TITLE
Remove the step that creates original-iri-x.x.x.jar

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1189]
### Description
Maven builds an *original-iri-x.x.x.jar* using the [shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html). We want to remove this step.

### Motivation
There is no difference between *original-iri* and *iri*. The step exists due to historical reasons and currently it only seems to confuse people (for example, #851).

### Requirements
1. Remove the step from the pom file.
2. Update internal documentations about the release process to ignore this file.

**Comment by alon-e** [comment]
>There is no difference between original-iri and iri.
this is not accurate - if you try to run `original-iri` then you will get an error:
```
no main manifest attribute, in original-iri-0.1.0.jar
```

**Comment by alon-e** [comment]
@GalRogozinski see https://github.com/iotaledger/cliri/pull/47 for a "fix".

**Comment by GalRogozinski** [comment]
True, the "original-iri" is missing the dependencies.
Since we only need the "uber" jar with the dependencies I suggest we drop the shade plugin and use the `maven assembly plugin`:

```
<plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.iota.iri.IRI</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <appendAssemblyId>false</appendAssemblyId>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id> <!-- this is used for inheritance merges -->
                        <phase>package</phase> <!-- bind to the packaging phase -->
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by iotarin** [comment]
thanks Gal
