### ISSUE TITLE
Use proper HTTP status codes for API responses

### ISSUE THREAD

**Issue by knarz** [iotaledger/iri#12]
It would be really helpful if IRI could make proper use of the various HTTP status codes.

i.e. I wouldn't expect to get `200` here but a `400`:

```
~ » curl --data '{"command": "getTrytes", "hashes": [""]}' http://127.0.0.1:14265
> POST / HTTP/1.1
> Host: 127.0.0.1:14265
> User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:45.0) Gecko/20100101 Firefox/45.0
> Accept: */*
> Referer:
> Content-Length: 40
> Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=UTF-8
< Content-Length: 76
< Connection: close

{"exception": "java.lang.ArrayIndexOutOfBoundsException: 4", "duration": 16}
```

This would make the usage of the API more intuitive and client libraries simpler.

**Comment by todofixthis** [comment]
I think that one should be a 500, since it's caused by a server-side error.

Might be covered by #9, though that is for 400's.

**Comment by davassi** [comment]
The current release is giving 400.

> curl -v --data '{"command": "getTrytes", "hashes": [""]}' http://127.0.0.1:14265
> * Rebuilt URL to: http://127.0.0.1:14265/
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port 14265 (#0)
> > POST / HTTP/1.1
> > Host: 127.0.0.1:14265
> > User-Agent: curl/7.47.0
> > Accept: */*
> > Content-Length: 40
> > Content-Type: application/x-www-form-urlencoded
> > 
> * upload completely sent off: 40 out of 40 bytes
> < HTTP/1.1 400 Bad Request
> < Connection: keep-alive
> < Transfer-Encoding: chunked
> < Content-Type: application/json
> < Date: Tue, 06 Dec 2016 14:19:18 GMT
> < 
> * Connection #0 to host 127.0.0.1 left intact
> 

@knarz which version are you using? not the last one.
@todofixthis yes a 500 would be even better.
