### ISSUE TITLE
Transition buffer between LOCAL_SNAPSHOTS_INTERVAL_UNSYNCED and LOCAL_SNAPSHOTS_INTERVAL_SYNCED

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1209]
### Description
The transition between `LOCAL_SNAPSHOTS_INTERVAL_UNSYNCED` and `LOCAL_SNAPSHOTS_INTERVAL_SYNCED` is now immediate in snapshotMilestone == latestMilestone. We could implement a buffer of 1-3 milestones in between the transition instead. 
UNSYNCED -> SYNCED transition. Maybe a "buffer" of 1-3 milestones would be better instead of snapshotMilestone == latestMilestone

**We agreed on a buffer of 5.**

**Comment by DyrellC** [comment]
Without a buffer I've noticed that the pruning inconsistently jumps back and forth between the synced and unsynced intervals, which makes the snapshots happen at irregular and inconsistent intervals. Sometimes the expected 10 milestones apart but more often than not it is delayed by over 20, and in some cases I've had my node not take a snapshot for over 400 (yikes). While investigating it appears that in almost all cases, a buffer of 2 milestones would overcome this issue. @jakubcech
