### ISSUE TITLE
Have maven update version automatically

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1220]
### Description
We need a way to bump versions automatically each time we build a new IRI version.
We want the process to be integrated together with how we deploy artifacts in buildkite.

### Motivation
We only want to do a manual version change when we do a release. For each artifact deployed by buildkite there should get a certain version name. Each jar created by a local build should get another version name.

## Requirements
1. Each artifact created by buildkite should have the first 5 characters of the git commit hash.
2. Each artifact created by buildkite which is on a release branch should also have RC-{$BUILD NUMBER} appended.
3. A release artifact should not have the above appended. Only the word RELEASE should be appended.
4. A jar that was created by locally running maven should be differentiated by appending a special suffix. TBD.
4. The base version should not be hardcoded in java code. It may be hardcoded in `pom.xml`. This can be achieved by adding the version to the Jar manifest.

### Implementation Details
The maven `Build Helper` plugin can help parse and inject the version values from the outside.
The version should be added to the jar manifest.

### Open Questions (optional)
1. Can a release candidate artifact be promoted to release? Currently it seems like we have to rebuilt.
2. Should we inject to the pom the version via buildkite? Same for the build number.

### Relevant reading material
https://blog.codecentric.de/en/2015/01/continuous-delivery-microservices-jenkins-job-dsl-plugin/
https://www.mojohaus.org/build-helper-maven-plugin/usage.html
http://www.mojohaus.org/buildnumber-maven-plugin/usage.html (less relevant probably)
https://maven.apache.org/plugins/maven-jar-plugin/examples/manifest-customization.html

https://github.com/git-commit-id/maven-git-commit-id-plugin (also talk about git build #)
https://blog.philipphauer.de/version-numbers-continuous-delivery-maven-docker/

**Comment by alon-e** [comment]
re: (4.) I think that it's buildkite which need to add a step - in this case, add a suffix (or you can remove a suffix, but that sound unnecessary)
side note - why is (4.) important? -> for example if you pull the code, but make uncommitted changes, you would want the build to not confuse you as if it was built using the original pulled code.

**Comment by GalRogozinski** [comment]
(1) -By each artifact I meant only `dev` artifacts (Non RC or release)
(2) - Buildkite will be responsible for incrementing the build number. @geminoz will investigate. In the meantime we opt for inserting the build # manually.
(3) We need to run the entire pipeline on the release.
(4) Only do that if it is easy. Append `dev` and commit hash. Nice to have: append `dev` if `git status` has changed tracked files that should be committed.
(5) - The major part of the version (x.x.x) will be hard coded in the `pom`.

**Comment by GalRogozinski** [comment]
Currently I have set up that by default the version will be
X.X.X-DEV-{$git_hash_abbrev}

The CI should perform the following operations:
```
 # get the version
VERSION = mvn git-commit-id:revision help:evaluate -Dexpression=project.version | grep -E '^[0-9.]+'
#For example 1.6.1-DEV- was outputted.

# awk/sed $VERSION to change it to 1.6.1-SNAPSHOT-de19c44 or 1.6.1-BETA or 1.6.1-RELEASE

#Now inject the new version to maven:
mvn versions:set -DnewVersion=$VERSION

#continue with CI/CD process
```

**Comment by GalRogozinski** [comment]
On the release branch:
Each version should be named `X.X.X-RC#`
Once we release the version should be named `X.X.X-RELEASE`

**Comment by nuriel77** [comment]
I have a question: why not drop the -RELEASE tag?
If no tag then == official release.

**Comment by GalRogozinski** [comment]
Also possible.
We decided to add the `RELEASE` tag to help us identify official release jars. It was before we decided on having the `-DEV` tag on non official builds and before adding the git hash abbreviation on daily artifacts.

We can decide that something named `X.X.X` is an official release. However, I personally like being explicit and the `RELEASE` tag serves this purpose.

Do you have strong feelings against it?

**Comment by nuriel77** [comment]
I can live with it :) Thanks for the info.

**Comment by GalRogozinski** [comment]
Opened #1415 for some farther changes
