### ISSUE TITLE
ZMQ publishes to TCP and IPC instead of just one of them

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1231]
### Bug description
Currently IRI's zmq socket binds to both TCP (non configurable) and IPC (by default configuration).
This seems to be confusing. Some people may not want TCP, or not need IPC by default.
We need to be able to configure all the sockets that ZMQ publishes to.
 
### IRI version
1.5.5

### Expected behaviour
One can configure exactly what sockets the ZMQ streams publish to.

### Actual behavior
TCP is always being published to and is non-configurable.

**Comment by legacycode** [comment]
@GalRogozinski: I want to solve this issue, but i think there is a lot of refactoring needed before. I see following problems:

- ATM MessageQ is alwas instantiated, also if ZMQ is not enabled.
- ZMQ has not much todo with the PersistanceProvider.
- MessageQ is an implementation class. There is no abstraction and it can't be changed easily atm.

These are only a few points. I have solved them by generating a MessageQueueProvider that can be set in the Tangle.class and removed the MessageQ injections from the classes. It is now much clearer what happens and only one check for ZmqConfig.isEnables is needed.

It would be great, if you could have a look at my commit comments at https://github.com/legacycode/iri/commit/812acb55d3780669873ce1ee8f0daef2bec16a8a in my branch https://github.com/legacycode/iri/commits/dev-zmq-optimization1

If you like these changes i will go on solving this issue.
Best regards.

**Comment by GalRogozinski** [comment]
Hey,
I will look at your code probably next week but for now I will answer your comments:

> ATM MessageQ is always instantiated, also if ZMQ is not enabled

True and very unfortunate

> ZMQ has not much todo with the PersistanceProvider.

True, a shame that the ZmqPublishProvider inherits from it

> MessageQ is an implementation class. There is no abstraction and it can't be changed easily atm.

True and unfortunate

> I have solved them by generating a MessageQueueProvider that can be set in the Tangle.class and removed the MessageQ injections from the classes

I currently view `Tangle.class` (and it's accompanying, currently imaginary, interface) as something that will enable various DB providers and should not be in charge of ZMQ.
I suppose you view ZMQ as something that should report on DB events (if I understood you correctly).
If so, it is less inline with the vision depicted in #716

**Comment by th0br0** [comment]
Just a nit; the methods the MQP exposes should be typed, or you should use helper models to transform to on-wire (zmq) format.
Also, the Provider itself shouldn't know anything about Persistables if you want to have a clear separation.
