### ISSUE TITLE
I want the previousEpochSpentAddresses file to be up-to-date on local snapshot nodes

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1241]
### Description
We need to make sure the wereAddressesSpentFrom API and getInclusionStates calls return correct results on local snapshot nodes. We should have a deterministic solution until there is quorum implemented in Trinity, at which point we can switch to a cuckoo filter. 

### Motivation
There is a reliance on a (deterministic) way of retrieving all the spent addresses, via the wereAddressesSpentFrom API and getInclusionStates calls. For example, Trinity relies on this. 

### Requirements
- [ ] I'm able to retrieve spent addresses deterministically from a local snapshot node via `wereAddressesSpentFrom` and `getInclusionStates`.

#### Implementation details
- [ ] Have an internal db column that tracks all the new spent addresses in-between the local snapshot intervals. 
- [ ] The DB column is flushed on a local snapshot interval and the `localSnapshotSpentAddresses` is appended. 
- [ ] The file that gets an appended is an empty `localSnapshotSpentAddresses` file that is included in the release. 
- [ ] The `localSnapshotSpentAddresses` file needs to be saved in the `LOCAL_SNAPSHOTS_BASE_PATH` directory with other local snapshot files, and needs to readable/accessible by the user. The file needs to be share-able easily. The file will be affected by the `LOCAL_SNAPSHOTS_BASE_PATH` configuration.
- [ ] The file should be created if it's not present in the folder on write.

**Comment by GalRogozinski** [comment]
@jakubcech
We won't fix the `getInclusionStates` scenario. We need to talk to the trinity team about it.
