### ISSUE TITLE
IRI needs to read the localSnapshotSpentAddresses for spent address scenarios

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1244]
### Description
Right now, IRI is relying on `previousEpochSpentAddresses1` and `previousEpochSpentAddresses2` files to infer which addresses were spent from, for scenarios like the wereAddressesSpentFrom call. 
IRI should also read a new file, `localSnapshotSpentAddresses` defined in #1241 in addition to the previousEpochSpentAddresses. 

The `localSnapshotSpentAddresses` will be written to running IRI instance on every snapshot interval. 

### Motivation
We need the information served by IRI on which addresses were already spent from to be up to date with the node's latest data. 

### Requirements
- [ ] The `wereAddressesSpentFrom` and `getInclusionStates` calls return data from `localSnapshotSpentAddresses`, `previousEpochSpentAddresses1`, `previousEpochSpentAddresses2`, `previousEpochSpentAddresses3` 
- [ ] The `localSnapshotSpentAddresses` will be written to by a different thread on a regular interval, we need to handle the access. 
- [ ] Where the `localSnapshotSpentAddresses` file is stored should be read from the `LOCAL_SNAPSHOTS_BASE_PATH` configuration.

**Comment by GalRogozinski** [comment]
`getInclusionStates ` will not be affected

**Comment by jakubcech** [comment]
Implemented as in #1258
