### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [iotaledger/iri#1246]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support IOTA on our service for a long time and we have been exchanging IOTA for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by tylerw1369** [comment]
I would try iota discord there are normally many IF memebers online at one time.
https://discord.gg/NaAy8k7

**Comment by jakubcech** [comment]
Hi Nicolas, yes, please try Discord as suggested. And close this issue, please. :) 

Thanks @tylerw1369

**Comment by SimpleSwap** [comment]
Noted with thanks.
