### ISSUE TITLE
getTrytes 500 internal server error

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#126]
What i tried:

1. get all used addresses from BZ seed
2. findTransactions with addresses
3. getTrytes from [trx hashes](https://gist.githubusercontent.com/pinpong/a3de603c2effd51959db9eb21300d056/raw/5b536bd2f4ab0a93f08f551dcb53768a103e1d8d/getTrytes) end up in 500 internal error

**Comment by jakubcech** [comment]
Reopen if this reoccurs, we changed the mechanism so it shouldn't occur anymore
