### ISSUE TITLE
addresses-spent-from-db folder should be configurable

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#1268]
related to #1263

https://github.com/iotaledger/iri/pull/1263/files#diff-00b87997de984ba006b56ba75ae03cd5R42 
hard-coded folder, users (like in docker) sometimes move the data it a persistent folder. this should be configurable.

**Comment by GalRogozinski** [comment]
We should note that when people will share the sent-addresses folder they will have to rename it
