### ISSUE TITLE
1.1.3.10 Node crash while starting spamming

### ISSUE THREAD

**Issue by Nyrsta** [iotaledger/iri#128]
Info
4 core 8gb VPS
IRI v 1.1.3.10
-Xmx1g -Xms1g

Started the spammer

Sun May 21 2017 08:47:41 GMT-0400 (EDT) RUNNING REPEATER: false, RUNNING VALUE SPAMMER: true
Sun May 21 2017 08:47:41 GMT-0400 (EDT)*INFO  Synchronized! Latest milestone idx: 4392. Latest solid milestone idx: 4392
Sun May 21 2017 08:47:42 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:47:42 GMT-0400 (EDT)*INFO  Synchronized! Latest milestone idx: 4392. Latest solid milestone idx: 4392
Sun May 21 2017 08:47:43 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:47:45 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:47:45 GMT-0400 (EDT)Error: Invalid Response:
+++++++++++++ spammer crashed ++++++++++++++++
+++++++++++++ trying a restart ++++++++++++++++
Sun May 21 2017 08:47:50 GMT-0400 (EDT) RUNNING REPEATER: false, RUNNING VALUE SPAMMER: true
Sun May 21 2017 08:47:50 GMT-0400 (EDT)*INFO  Synchronized! Latest milestone idx: 4392. Latest solid milestone idx: 4392
Sun May 21 2017 08:47:51 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:47:52 GMT-0400 (EDT)*INFO  Synchronized! Latest milestone idx: 4392. Latest solid milestone idx: 4392
Sun May 21 2017 08:47:53 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:47:55 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:47:55 GMT-0400 (EDT)Error: Invalid Response: Error: read ECONNRESET
    at exports._errnoException (util.js:870:11)
    at TCP.onread (net.js:544:26)
+++++++++++++ spammer crashed ++++++++++++++++
+++++++++++++ trying a restart ++++++++++++++++
Sun May 21 2017 08:48:00 GMT-0400 (EDT) RUNNING REPEATER: false, RUNNING VALUE SPAMMER: true
Sun May 21 2017 08:48:00 GMT-0400 (EDT)*INFO  Synchronized! Latest milestone idx: 4392. Latest solid milestone idx: 4392
Sun May 21 2017 08:48:01 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:48:02 GMT-0400 (EDT)*INFO  Synchronized! Latest milestone idx: 4392. Latest solid milestone idx: 4392
^CSun May 21 2017 08:48:03 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
^CSun May 21 2017 08:48:04 GMT-0400 (EDT) *INFO  Checking the seed for any balance...
Sun May 21 2017 08:48:05 GMT-0400 (EDT) *Attachting stopped
+++++++++++++ spammer crashed ++++++++++++++++
+++++++++++++ trying a restart ++++++++++++++++
Sun May 21 2017 08:48:10 GMT-0400 (EDT) RUNNING REPEATER: false, RUNNING VALUE SPAMMER: true
Sun May 21 2017 08:48:10 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:11 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:12 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:13 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:14 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:15 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:16 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:16 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:17 GMT-0400 (EDT) *INFO  Waiting for iri connection.
xSun May 21 2017 08:48:18 GMT-0400 (EDT) *INFO  Waiting for iri connection.
cccSun May 21 2017 08:48:19 GMT-0400 (EDT) *INFO  Waiting for iri connection.
Sun May 21 2017 08:48:20 GMT-0400 (EDT) *INFO  Waiting for iri connection.
^CSun May 21 2017 08:48:21 GMT-0400 (EDT) *Attachting stopped with error
Sun May 21 2017 08:48:21 GMT-0400 (EDT)Error: Invalid Response: Error: connect ECONNREFUSED 127.0.0.1:14700
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

In fact the node crashed at the moment 

Exception in thread "Solid TX cascader" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "Tip Solidity Rescan" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "XNIO-1 task-8" java.lang.OutOfMemoryError: GC overhead limit exceeded

There was also a .log file generated

[hs_err_pid15272.txt](https://github.com/iotaledger/iri/files/1017005/hs_err_pid15272.txt)

**Comment by alon-e** [comment]
value spammer was requesting too many transactions.
fixed in 6712662d726e97e4dc1967d44c8f21b903f299b0
