### ISSUE TITLE
As a node operator, I want to synchronize my node from up-to-date local snapshot files

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1280]
### Description
We need to set up a way for node operators to get local snapshot files (including the spent addresses one) from a reliable source.

### Motivation
Allow node operators to get an updated set of local snapshot files they can synchronize their nodes from. 

### Requirements
- [x] I'm able to download snapshot files from the same URL every time. 
- [x] The snapshot files are generated on a regular basis, <= 24h.
- [x] The snapshot files are generated by an IF node.

**Comment by zoran** [comment]
> The snapshot files are generated by an IF node.

won't that lead to a "centralized" discussion? Would it perhaps be possible to somehow certify third parties such as iota.partners (db.iota.partners) or Nuriel's server? After all, these have been the most important download sources for databases for a year now.

**Comment by jakubcech** [comment]
This is supposed to be just one source. So that we know something's available at all times. It's the same thing with DBs that we also upload ourselves, but others upload them as well. We definitely want others to upload these files as well. Esp., iota.partners and Nuriel since you guys have a really good reputation in the community. It's all reputation-based, and there definitely aren't any restrictions on this. :)
