### ISSUE TITLE
Regression test: Bootstrapping an LS-enabled node from DB and from local snapshot files 

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1281]
### Description
We want to have a regression tests that verifies a node bootstraps correctly from both the DB and local snapshot files. 

### Motivation
We need to make sure that both approaches of starting up a node work, and that snapshots are being taken. 

### Scenarios
DB:
1. I start up a new node from an existing DB. 
2. The node starts up and starts taking local snapshots. 

Local snapshot files:
1. I start up a new node from local snapshot files.
2. The node starts up and starts taking local snapshots.

### How to test for this
1. Start up a permanode. 
2. Start a node with default configuration that is connected to node. The node starts from an existing DB. 
3. Start a node with default configuration that is connected to node. The node starts taking local snapshots.  
4. (DB only node) The snapshot files are created. 
5. Changes are written to the snapshots.meta and snapshots.state files.
6. Changes to the DB are written. 
7. Compare the DB and snapshot files.

**Comment by jakubcech** [comment]
What's the review status here btw.?

**Comment by DyrellC** [comment]
@GalRogozinski The machine6 PR is passing and ready for final review. No more `kube` commands. This logic has been replaced with an `IXI` module to fetch the snapshot state and meta data straight from the node's `SnapshotProvider`. https://github.com/iotaledger/iri/pull/1349
