### ISSUE TITLE
CPU spiking making the node unresponsive 

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1287]
### Bug description
CPU spiking has been reporting by 1.6.0 when the node becomes unresponsive. The node keeps on running. Need to investigate whether this is 

@DyrellC, have you seen this on any of your nodes?

### IRI version
1.6.0

### Hardware Spec
TBFI

**Comment by DyrellC** [comment]
@jakubcech  Yes I've been having a few problems with my nodes today, i'm investigating them further right now. You and @galrogo  will be updated when/if I can find the causes.

**Comment by coinfalcon-github** [comment]
same here, 6 core node maxed out, node out of sync. Another node synced with db snapshot stuck at 978698. Few people are reporting same issue in docker `fullnodes` channel. It seems like that it is not related to iri version.

**Comment by coinfalcon-github** [comment]
@jakubcech are you sure that it is related to 1.6.0? Did you try to downgrade again?

**Comment by GalRogozinski** [comment]
@coinfalcon-github 
I assume you are on 1.5.6? Nothing older?

**Comment by KnobbyB** [comment]
Hey, I did a total reload of my OS and iri and now my sync and CPU spiking has solved itself.

**Comment by jakubcech** [comment]
**Dyrell** says this is mainly caused by:

`LocalSnapshotManager`
`TransactionPruner` - the serialized job. 
`MilestoneSolidifier` - latestMilestonTracker implementation, collectNewMilestoneCandidates - loading of the addressViewModels for loading of the milestone candidates. ProcessSolidificationQueue.

**Comment by DyrellC** [comment]
High cpu usage appears to be attributed primarily to the `transactionPruner`, the `spentAddresses`, and `milestoneSolidification` threads. The first two have been addressed and the new release will show significant reduction in cpu usage. The `milestoneSolidification` thread usage is most prominent during syncing intervals, and usage drops once the node is synced (surprising I know /s). There are still small rises in usage during rescan intervals (as the threads are being respawned) and local snapshots (the additional processes simply require additional usage, but usage is minimal and short lived), but neither of these instances appears to be detrimentally disrupting.
