### ISSUE TITLE
Local snapshots and compass depth

### ISSUE THREAD

**Issue by geminoz** [iotaledger/iri#1290]
I am not sure how to categorise this ticket. It could be a bug, it could be a feature request or it could even be more related to compass than IRI.

As soon as I introduced IRI 1.6.0 to spamnet (with LS and pruning enabled), compass failed to generate milestones due to a low depth error. 

It looks like that the IRI.ini "MAX_DEPTH" (set to 1000) configuration option is overridden by the LS functionality and possibly by LOCAL_SNAPSHOTS_DEPTH (initially set to 100).

The temporary "fix" was to disable pruning.

I am now testing the following configuration: LS enabled, pruning enabled and LOCAL_SNAPSHOTS_DEPTH to 1000.

This ticket is to assess if there is anything to be done on the IRI side.

**Comment by jakubcech** [comment]
Thanks Giorgio, we'll have a look.

**Comment by jakubcech** [comment]
@geminoz, this was resolved if I understood the discussion that happened later correctly?
