### ISSUE TITLE
Minor issue: wrong quote characters are indicated in printUsage 

### ISSUE THREAD

**Issue by alfredch** [iotaledger/iri#13]
PrintUsage() prints the following string when starting IRI with incomplete arguments:
INFO com.iota.iri.IRI - Usage: java -jar IRI-1.1.2.jar [{-p,--port} 14265] [{-r,--receiver-port} 14265] [{-c,--enabled-cors} *] [{-h}] [{--headless}] [{-d,--debug}] [{-n,--neighbors} '&lt;list of neighbors&gt;'] 

This is wrong, the &lt;list of neighbors&gt; must be enclosed in double quotes, not single quotes.
The parser does not recognize the list if it is in single quotes.

**Comment by davassi** [comment]
Which os/ enviroment/ shell?

**Comment by alfredch** [comment]
This error occurs on Windows 10, ordinary CMD shell.
java version "1.8.0_112"

**Comment by davassi** [comment]
It is an issue related to the window enviroment and how CLI parses command line. On ubuntu both versions are working , either with "" or ''. Thanks I will update the PrintUsage()
