### ISSUE TITLE
Convert from trytes to ascii String

### ISSUE THREAD

**Issue by lhfbc** [iotaledger/iri#1301]
### Description
Add one method in Converter to translate trytes to ASCII text.

### Motivation
In Converter, there is a method called 'asciiToTrytes' to translate ASCII text to trytes, and the reverse method is missing.

### Requirements
translate trytes to ASCII text

### Open Questions (optional)
All the UTs for these conversions are missing, shall we add these UTs?

### Am I planning to do it myself with a PR?
Yes.

**Comment by GalRogozinski** [comment]
Question about the motivation:

Who will call use your new method?

**Comment by lhfbc** [comment]
It is a reverse tool to 'asciiToTrytes' and may be used by some validation.

I have a scenario.  I wanted to make some experiment, like putting some secret ASCII string in a 'Transaction', and when I wanted to get it out and check it, I didn't find the corresponding method. So I write one.

**Comment by GalRogozinski** [comment]
> All the UTs for these conversions are missing, shall we add these UTs?

This will be nice,
It is better to do it in a different PR though
