### ISSUE TITLE
API call rate limiting

### ISSUE THREAD

**Issue by georgmittendorfer** [iotaledger/iri#1304]
### Description

It might make sense to add API call rate limiting to IRI so that spammers cannot push too many transactions via the API. As a side effect it would also help to prevent to DOS the node.

See #1293 and `Come-from-Beyond Today at 9:51 AM it should also include IP filtering for API`

### Motivation

Currently spammers can easily flood the network and bring nodes down with too many requests.

### Requirements

It should be possible to rate limit every IRI API command on a per IP basis. It should be possible to specify the `command`, the `period` and the `limit`.

Optionally a `timeout` (time to wait until an error occurs if the incoming command cannot be immediately processed because it needs to wait because of the specified limit).

It should be possible to specify the period and the timeout as `java.time.Duration` at least in minutes, seconds and millis.

It might be necessary to clear the rate limiters from time to time.

Configuration could look like this for example, if someone might want to limit broadcasting transactions to 5 calls per 30 sec with a 10 sec timeout:

```
rate.broadcastTransactions.limit=5
rate.broadcastTransactions.period=30s
rate.broadcastTransactions.timeout=10s
```

### Open Questions (optional)

Not sure if rate limiting should be IRI core functionality. Alternative approach would be to rate limit in a proxy in front of IRI. That would have the advantage that IRI wouldn't be bothered with these tasks and that it wouldn't be necessary to develop this feature. The downside would be that many people wouldn't use this feature if it is not enforced and therefore the network would be more vulnerable to spam attacks.

For implementation I would suggest to use a library like resilience4j (http://resilience4j.github.io/resilience4j/). This would mean an additional dependency but make implementation easier (hopefully - didn't try it with non-reactive code yet). Would that be a viable option?

Is there someone within the IRI team that can be directly contacted for implementation details?

### Comment

I already implemented something similar (but with reactive code). See code at (https://gitlab.com/georg.mittendorfer/piri/blob/master/src/main/java/com/mio/piri/service/IriApiHandler.java#L103) and how to configure it (https://gitlab.com/georg.mittendorfer/piri/wikis/configuration). Could be used for inspiration.

### Am I planning to do it myself with a PR?

Maybe, but not immediately. If someone else is willing to do it: please go on!

**Comment by jakubcech** [comment]
Hi @georgmittendorfer, thanks for the issue. I think the broader discussion to be had here ties to your first point in Open Questions. I'm inclined to say this should be handled by proxies in front of IRI. Then of course what the specifics options for filtering should be as well.

For the latter (the limits themselves), I would propose things similar to:
- Maximum of concurrent API connections
- Minimum delay between API connections
- Delay after an API call
- Queue settings for burst handling

I like how Nginx handles rate limiting for example. Maybe we should make using one of the `already-out-there proxy solutions` a recommendation when setting up a node. 

Happy to hear what others think regarding this.
