### ISSUE TITLE
Nightly test: syncing a node from scratch

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1318]
### Description
Nightly test for a measuring that a node successfully syncs from different sources that we provide.

### Motivation
Test that nodes are syncing by various means. 

#### Sync from the latest local snapshot file scenario
1. Set up a node with the latest snapshot files from the IOTA db-files site.
2. Check that the node syncs via ZMQ. 

#### Sync from the latest database (without local snapshot files)
1. Set up a node with the latest DB from the IOTA db-files site.
2. Check that the node syncs via ZMQ.

#### (Last to implement scenario) Sync from an ancient DB
1. Set up a node with a database that is at least X, last coo snapshot days old. 
2. Check that the node syncs via ZMQ.
3. If it doesn't sync before the next instance of this nightly test is run then the test failed.

**Comment by DyrellC** [comment]
@GalRogozinski In each of these test cases, is it expected for the nodes to sync up with the network as a whole? Or just to sync with one another from a set db state? If the former, how do you propose we connect these nodes to other testnet nodes, considering there will need to be a mutual pairing of neighbors? And if not, where do you propose we store/pull the day to day db package that will be used as the benchmark?

**Comment by GalRogozinski** [comment]
just to sync with one another from a set db state

We can store it in the same s3 bucket. We can also use an existing DB. The point is that we have a constant DB, so that we know that only code changes affected performance.

**Comment by DyrellC** [comment]
@GalRogozinski  @jakubcech 
https://github.com/iotaledger/iri-regression-tests/pull/13

**Comment by jakubcech** [comment]
Blocked by solidification issues. Otherwise this is finished.

**Comment by GalRogozinski** [comment]
@DyrellC can you add a legend to the x-axis and the y-axis in the graph please?

**Comment by DyrellC** [comment]
https://github.com/iotaledger/iri-regression-tests/pull/13 
Although the version being used in buildkite is https://github.com/iotaledger/iri-regression-tests/pull/24 which includes all the integration details for buildkite purposes. 

The general flow for this test is as follows: 
3 nodes are started up connected to one another. 2 of these nodes are synced with a db at milestone index 2005, and the third is started up without a db present. After the nodes are given a moment to startup and connect properly, the 2006 milestone is sent to the first of the synced nodes. This triggers a sync from the other 2 nodes. The other synced node will quickly sync from 2005 to 2006, while the other one will start the request cycle backwards trying to sync from 0 to 2006. Once all 3 nodes are registering the same solid milestone index the test is concluded. 

```
NodeA: 2005 -> 2006
NodeB: 2005 -> 2006
NodeC: 0 -> 2006
```

@GalRogozinski Yes I can add legends to the graph, i'll add those today. I will also have it not print out a graph should the sync state start from 2005 on `nodeB` so nobody gets confused by why that one is syncing (even though it is syncing the 1 milestone as intended, no need for a graph to pop up) just as it excludes a graph for `nodeA` as well.

**Comment by DyrellC** [comment]
The DB being used is a standard db that contains 2005 milestones and a total of 235k transactions all of which are zero value transactions. I will be additionally adding another node to the test that will start from a local snapshot at the default depth to use for comparison, as well as to satisfy the final requirement to the issue.
