### ISSUE TITLE
Nightly test: node performance

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1328]
### Description
[Reconsider the estimate during planning if GTTA test is done by then]

A nightly test running on a node on the Spamnet that measures some basic values on a syncing and synced node. 

We measure CPU load, memory load, network load, I/O. 

This needs to be measured against a baseline so that we know when things have degraded. The first run of this test will be used to set up a baseline (we'll talk abt the results). 

We integrate this into TIAB first, once that is done, we move it to spamnet and we can add spammers. Right now we test for the performance of a node that is syncing and synced, not that is spammed or anything like that. 

### Motivation
Evaluate every change with regards to performance on a live node with specific set up. 

### Scenario
1. We fire up a node that starts syncing and let it run after it has been synced for some time.
2. We keep logging the values for CPU load, memory load, network load, and I/O. 
3. (Step that is part of the initial set up: we scrutinize the results of the first run and make a baseline out of that)
4. We parse the results and if we ever go through above the baseline, we send an email.

#### Sync from the latest local snapshot file scenario
1. Set up a node with the latest snapshot files from the IOTA db-files site.
2. We wait for the node to sync and log the values for CPU load, memory load, network load, and I/O. 
3. The node syncs and then we log the values for CPU load, memory load, network load, and I/O on the synced node.

**Comment by DyrellC** [comment]
I've started putting pieces of a python test together that monitors cpu/memory/IO/network load using the `psutil` module. As discussed in the call, I have not organised this test to run with aloe for now. Instead there will be utility modules and a main script to run the testing portion.

**Comment by GalRogozinski** [comment]
This is perfectly fine.
When we start properly running the nightly tests we will understand what is the best way to approach the aloe question.

**Comment by DyrellC** [comment]
@GalRogozinski @jakubcech 
https://github.com/iotaledger/iri-regression-tests/pull/12

**Comment by GalRogozinski** [comment]
#1318  accomplishes enough
