### ISSUE TITLE
Regression test: DB Pruning works correctly on a pruning enabled node

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1337]
### Description
We want to have a regression tests that verifies that a node is pruning data below pruning delay and doesn't prune data within the delay. 

Note: this regression test is running into the issue of having to reach the set PRUNING_DELAY first. 

### Motivation
We need to make sure that the data configured by the node to present in the DB is always present, not more, not less. 

### Scenarios
1. I start up a new node from local snapshot files.
2. The node synchronizes and the DB holds the transaction data specified by the PRUNING_DELAY + DEPTH interval.

### How to test for this
1. Start up a permanode. 
2. Start a node with default configuration that is connected to the permanode. The node synchronizes and starts taking local snapshots at the SYNCED interval.
3. The node doesn't hold more transactions transactions than defined by PRUNING_DELAY + DEPTH, given the current PRUNING_INTERVAL. 
4. The node holds all transactions in its DB that are within PRUNING_DELAY + DEPTH. Query at different portions of the interval.

**Comment by GalRogozinski** [comment]
Hmm looking at the test again:
```
Scenario: Old transactions are pruned
    Takes a node with a large db and transaction pruning enabled, and checks to make sure that the transactions below
    the pruning depth are no longer present.

    Given "checkConsistency" is called on "nodeD" with:
      |keys                       |values                   |type             |
      |tails                      |LS_PRUNED_TRANSACTIONS   |staticValue      |

    Then the response for "checkConsistency" should return null`
```

Maybe we should add another scenario in the beginning that checks that the pruned transactions really exist?
There is a requirement to check at different intervals

**Comment by GalRogozinski** [comment]
I am not closing until the above comment will be addressed

**Comment by GalRogozinski** [comment]
@DyrellC ^

**Comment by DyrellC** [comment]
#1775 does the test in intervals now rather than just a checkConsistency call.
