### ISSUE TITLE
Investigate the cost of implementing parallel hashing

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1357]
### Description
We want to improve the performance of hashing incoming transaction as described in #1325. There are two approaches to this;

- Implement this on the current stack, with the use of callbacks/futures. Or some other 'make this work' approach.
- Rewrite a portion of the networking stack to allow for implementing this in a proper queue-based set up. 
- Other approach?

This issue should investigate the possible approaches further and result in:

- Possible approaches (if different from above), with more detail and comparison to how and if the processing would differ
- Cost of implementation
- Recommendations, with regards to the debt introduced by different/not too nice approaches

### Motivation
Help us decide whether it makes sense to wait for queue based networking set up, write the set up ourselves now without waiting for the networking refactor, or implement a possibly less costly solution with a certain or same/similar performance benefit. 

### Requirements
- [ ] Summary and comparison of possible approaches
- [ ] Cost of implementation for each summary

**Comment by jakubcech** [comment]
We can look scope this to investigating implementing this on the current stack first and seeing what the solution would be like. Timeboxing the investigation to a few days and proposing the best solution. We can decide if we want to wait for different networking config once we have that in front of us, but we might not want to.

**Comment by GalRogozinski** [comment]
We started working on #1072. If we see it gets delayed we shall think about trying to hack it to the current stack
