### ISSUE TITLE
Review TLV based packets implementation

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1377]
### Description
Allow IRI to understand the data a peer is sending.  

### Motivation
Allow for extensibility of the protocol and for dynamic packet sizes. For example, allowing to send truncated transactions to neighbors. Enable scenarios like health-check packets. 

### Requirements

**Comment by luca-moser** [comment]
My changes currently use a 4 byte header for each transmitted message.
* 1 byte denoting the protocol version (up to 256)
* 1 byte denoting the message type (up to 256)
* 2 byte denoting the message size (up to 65,536 kilobytes)

As we will read data from the socket, we want to have a message reader instance which has enough space allocated for the expected message. My implementation defines max sizes for message types.

TLVs denoted messages become handy when I truncate transaction payloads by removing zero bytes from the signature message fragment before transmitting them. The recipient of such messages can allocate appropriate buffers as the message length is known. In the best case, this allows a size reduction of 81.7% (1312 / 1604 bytes) and in most cases this will also allow transaction gossip messages to fit in the MTU of the Internet (1,5 kilobytes).

In case we actually need to support legacy TCP connections there will be separate code, which handles the logic of dealing with such connections.
