### ISSUE TITLE
headless option of Testnet-1.1.2.jar

### ISSUE THREAD

**Issue by Nyrsta** [iotaledger/iri#14]
Testnet IRI 1.1.2
-h option does not seems to work when trying to start the jar
-h option for headless not formulated the same as the other options in below example
adding --headless as option is working

usage: java -jar IRI Testnet-1.1.2.jar [{-p,--port} 14265] [{-r,--receiver-port} 14265] [{-c,--enabled-cors} *] [{-h}] [{--headless}] [{-d,--debug}] [{-n,--neighbors} '<list of neighbors>

**Comment by davassi** [comment]
-h only displays help CLI command usage.
--headless is still WIP (Iota ascii art logo is not loaded yet, but it will be *very* soon)
