### ISSUE TITLE
Not correct balance when I send many times

### ISSUE THREAD

**Issue by xiaocaipi** [iotaledger/iri#1408]
The issue tracker is only for reporting bugs or submitting feature requests.
If you need technical assistance for running a node please consult the #fullnode channel on Discord (https://discord.gg/jrxApWC) or https://forum.helloiota.com/Technology/Help.
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, https://helloiota.com/, or browse Discord channels (https://discord.gg/C88Wexg).

### Bug description
A general description of the bug.
in private network ,i send 5 transfer to 5 address that generated by one seed,but when I get balance from seed,the balance of my seed is 1.

### IRI version
What version are you running?
1.6.1
### Hardware Spec
On what hardware is the node running on?
i7+8g+512g ssd

### Steps To Reproduce
1. First, I use my seed  to generate 100 address 
2. Do a for loop ,to send 5 Transfer with 1 value ,and  different 5 address, and the same message
3. when I check my seed balance ,there is only 1 

### Expected behaviour
I hope when I send 5 times to my address with 1 value , there is 5 in my balance

**Comment by xiaocaipi** [comment]
In my private network ,I find  one milestone can confirm one transaction.I
If the interval of milestone is 10s . how can confirm mutile transaction  in  10 s

**Comment by GalRogozinski** [comment]
The issue tracker is only for reporting issues or requesting features.
For help visit https://forum.helloiota.com/ or join the IOTA discord server https://discord.gg/sqeasN
