### ISSUE TITLE
Test the DaF CW calculation against the current one

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1428]
### Description 
We should experiment with the other implementation of the CW algo and compare how it behaves compared to the one we currently have.

Paul may have tried and discarded the implementation. Any other issues than the recursion point? 

CW = the size of the subgraph 

### Requirements
- [ ] Implement the changed CW calculation - for each tx in a subgraph we perform a scan BFS or DFS and udpdate the CW for the root transaction.  
- [ ] DFS can be without recursion if that is an issue. 
- [ ] Benchmark it against the current one

**Comment by GalRogozinski** [comment]
See comments in #1451 to see the results of the benchmark.
It was 3x faster
