### ISSUE TITLE
Create a backfilled spent-address-dbs from different sources into one DB

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1430]
### Description
We should have a way of creating a backfilled `spent-addresses-db`. This might or might not require merging of different `spent-addresses-db`. This will be for a one-off job that will allow us to create a `spent-addresses-db` merged with local snapshot files that has the records from the previous epoch, as well as a current record up until today.

Do a dry run before a release and then do this again during the release. 

### Motivation
Create a backfilled `spent-addresses-db` that has a `full` record of spent address without having duplicates. That can be used for the initial local snapshot/spent address db merger release. 

### Requirements
- [ ] I'm able to download a local snapshot/spent-addresses DB that has a reliable record of spent addresses.
- [ ] The DB is compatible with what will be released in #1443
- [ ] We need to use spent address DBs with data from all the previous epochs in which we've been using separate spent-address-DBs to create the initial database.
- [ ] For the initial release, this needs to be done on the day of the release so that we provide a good transition.

**Comment by luca-moser** [comment]
We can now also use https://github.com/luca-moser/iri-ls-sa-merger, to merge different `spent-addresses-db` and text files containing spent addresses into one database.

**Comment by GalRogozinski** [comment]
Before this can be closed we need to migrate the above tool to an official IF repo

**Comment by GalRogozinski** [comment]
@jakubcech I guess you are the one who can create this repo and close the issue ;-)

**Comment by GalRogozinski** [comment]
Repo created:
https://github.com/iotaledger/iri-ls-sa-merger
