### ISSUE TITLE
TCP connexion doesn't work

### ISSUE THREAD

**Issue by tiresias54** [iotaledger/iri#144]
I tried with several testers to enable TCP (with and without) mutual tethering but no success. We have this getNeighbors output: 

> "address":"xx.xx.xx.xx:15777"
> "numberOfAllTransactions":0
> "numberOfRandomTransactionRequests":0
> "numberOfNewTransactions":0
> "numberOfInvalidTransactions":0
> "numberOfSentTransactions":0
> "connectionType":"tcp"

Note that udp worked with all the testers.

**Comment by alfredch** [comment]
Are you sure inbound and/or outbound TCP connections on port 15777 are not blocked by your firewall setting?
We cannot reproduce this behavior with version 1.1.3.10

**Comment by tiresias54** [comment]
i have no firewall. I will try to investigate further on mainnet when the next version is released.

**Comment by curVV** [comment]
I've also tried with one of my neighbours, no joy.
Disabled FW, port forwarded and tested.
No tx came through on either side.

**Comment by paulhandy** [comment]
Is this with the docker image?
