### ISSUE TITLE
Local snapshot files and spent-addresses-db single DB integration

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1444]
### Description
Local snapshots + Spent addresses are persisted in RocksDB as one DB/folder. The LS files and `spentaddresses-db` should be tied together. 

`localsnapshots-db` is the name of the folder 

### Motivation
Local snapshots and spent addresses DB are tied together so that it's less likely that users who bootstrap their node use a spent addresses DB that doesn't have the historical spent addresses. 

### Requirements
- [ ] The spent addresses DB folder to local snapshots and make sure they use the same rocksDB provider.
- [ ] The column families should be derived from what we use with snapshot.meta and snapshot.state files. 
- [ ] Users with local snapshots disabled read spent addresses from the `spent-addresses-db` in the local snapshots folder as well. 
- [ ] The folder is configurable, just like the mainnetdb path is.

**Comment by luca-moser** [comment]
File contents:
* `xxx.snapshot.meta`:
   * hash to which the snapshot belongs to
   * index of the milestone to which the snapshot belongs to
   * timestamp to which the transaction belongs to
   * number of solid entry points
   * number of seen milestones

* `xxx.snapshot.state`: ledger state

**Comment by luca-moser** [comment]
The jar contains a built in local snapshot file from the last global snapshot and a signature file.

**Comment by luca-moser** [comment]
> Users with local snapshots disabled read spent addresses from the spent-addresses-db in the local snapshots folder as well.

I don't think there should be a `spent-addresses-db` folder inside `localsnapshots-db`, instead, the .sst files should both contain the spent addresses and the persisted local snapshot.

**Comment by jakubcech** [comment]
sounds good to me

**Comment by GalRogozinski** [comment]
I think what the requirement meant @luca-moser is that we have one db like you are planning to do and we should still use it if local snapshots are disabled

I guess it wasn't written clear enough, it is confusing I admit

**Comment by GalRogozinski** [comment]
Fixed by #1584
