### ISSUE TITLE
Map out and investigate the current gossip protocol/syncing mechanism

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1446]
### Description
Map out the gossip protocol. This can also help us investigate syncing issues and such. 

### Motivation
Map out the inner workings of the gossip protocol/syncing mechanism. 

### Requirements 
- [ ] A set of beautiful diagrams describing how the current gossiping mechanism in IRI works
- [ ] Host in iotaledger/diagrams repo

**Comment by luca-moser** [comment]
https://github.com/iotaledger/diagrams/blob/master/out/activity/network_comm.svg
