### ISSUE TITLE
[add/removeNeighbors] unexpected behavior

### ISSUE THREAD

**Issue by tiresias54** [iotaledger/iri#145]
when running IRI, i have this getNeighbors output:

> "address":"<Hostname address>:14441"
> "numberOfAllTransactions":6099
> "numberOfRandomTransactionRequests":224
> "numberOfNewTransactions":4106
> "numberOfInvalidTransactions":0
> "numberOfSentTransactions":27799
> "connectionType":"udp"
> "duration": 0

I remove the neighbor using removeNeighbors: 

> "removedNeighbors":1,"duration":156

Then getNeighbors gives: 

> "address":"<IP address>:14441"
> "numberOfAllTransactions":12
> "numberOfRandomTransactionRequests":0
> "numberOfNewTransactions":6
> "numberOfInvalidTransactions":0
> "numberOfSentTransactions":77
> "connectionType":"udp"  
> "duration":0

So the neighbor isn't removed, and the field "address" contains the IP address and not the hostname address and numberOfSentTransactions and other fields looks to be reset.

**Comment by alon-e** [comment]
are you running in strict multi tethered mode? i.e you don't have --max_peers X set?
b/c if you are running w/ one-sided tethering this is normal behavior, your neighbor sent you a tx, so he is re-added to the list.
Re: hostname, 
hostnames are resolved every 30 mins. to check if ip has changed. the hostname will update then.

**Comment by tiresias54** [comment]
yes indeed i had MAX_PEERS = 10. I tried with MAX_PEERS = 0 and it works normally. Solved.
