### ISSUE TITLE
Make a tool that exports the LS/Spent address rocksDB into a format usable by Heracles/cIRI

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1450]
### Description
Create a mechanism that exports the spent addresses stored in IRI rocksDB into a general format. Such as a text file. For other node software to be able to le import. 

### Motivation
Other node software needs a way to supply their own spent addresses DB and they need to get historical records from IRI. 

This can also cover for the need of merging existing records if export/re-import is a feasible way to go. 

### Requirements
- [ ] I'm able to take the IRI `spent-addresses-db` and export it to a general file format
- [ ] The format is the same as with the previousEpochSpentAddresses.txt files - human readable.
- [ ] Filename is `spentAddresses.txt`
- [ ] File contains a `timestamp` at the top to indicate when it was created/compare to LS files
- [ ] Store with a checksum
- [ ] **Use IXI** - I trigger the export with a `generateSpentAddressesFile` IXI API call*
- [ ] The call returns the amount of addresses

*The generation exports the state of the `spent-addresses-db` at the time of the call, it doesn't guarantee that any new spent addresses will be there that come in between the start and the end of the call

### Details
This will mainly support a one-time operation. cIRI/Heracles use this as a one-time solution for import in their own DB.

**Comment by muXxer** [comment]
Can't we use the old code to save everything to a file? Maybe add an option to the config to activate that (and don't split it into several files)

**Comment by GalRogozinski** [comment]
It is possible to use the old file format

**Comment by kwek20** [comment]
IXI is here for now: https://github.com/kwek20/iri-extensions
Implementation can still change

Will be moved over to an iotaledger repo soon.

**Comment by GalRogozinski** [comment]
Currently Brord is returning the hash in the response.
I think this is fine. It is just that the requirement is ambiguous.

**Comment by kwek20** [comment]
nono, we also append on the end!

**Comment by GalRogozinski** [comment]
yeah at the end of the response
When I said "hash" I meant "checksum"

**Comment by GalRogozinski** [comment]
I was looking a the old repo.
The code is here: https://github.com/iotaledger/iri-extensions

@muXxer @thibault-martinez 
Are you fine with the hash is appended at the end?
My problem is that it will not be the hash when of the `sha256sum` of the file because here we hash the checksum. Not a big deal if we know to always remove the last line before check summing I suppose...

**Comment by jakubcech** [comment]
They said yesterday they're fine with it :D I think about it as the hash of the addresses if they were stored in a .txt file. 😅

**Comment by thibault-martinez** [comment]
I'm fine with it.

I agree with @jakubcech, can't it be a Curl-P-27 checksum of the addresses or something like that ?

**Comment by GalRogozinski** [comment]
no

**Comment by thibault-martinez** [comment]
ok

**Comment by GalRogozinski** [comment]
I am closing this @jakubcech
