### ISSUE TITLE
Neighbor DNS Refresher Thread Exception

### ISSUE THREAD

**Issue by necropaz** [iotaledger/iri#146]
I got this Error with Version 1.1.3.10 in testnet after a while.. When i restart the node the error was gone.. The error doesn't harm the other functionality..

May 30 09:15:45 vmi111313.contaboserver.net java[22975]: 05/30 09:15:43.723 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Checking Neighbors' Ip...
May 30 09:15:45 vmi111313.contaboserver.net java[22975]: 05/30 09:15:43.723 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'xxxxxxx' with 'xxx.xxxx.xxx.xxx'
May 30 09:15:45 vmi111313.contaboserver.net java[22975]: 05/30 09:15:43.723 [pool-2-thread-3] INFO  com.iota.iri.network.Node - xxxxxxxx.com seems fine.
May 30 09:15:45 vmi111313.contaboserver.net java[22975]: 05/30 09:15:43.723 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'ALONS DNS' with 'xx.xxx.xxx.xxx'
May 30 09:15:45 vmi111313.contaboserver.net java[22975]: 05/30 09:15:43.723 [pool-2-thread-3] INFO  com.iota.iri.network.Node - CHANGED IP for ALONS DNS! Updating...
May 30 09:15:45 vmi111313.contaboserver.net java[22975]: 05/30 09:15:43.724 [pool-2-thread-3] ERROR com.iota.iri.network.Node - Neighbor DNS Refresher Thread Exception:
May 30 09:15:45 vmi111313.contaboserver.net java[22975]: java.lang.IllegalArgumentException: port out of range:-1
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143) ~[na:1.8.0_131]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224) ~[na:1.8.0_131]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at com.iota.iri.network.Node.removeNeighbor(Node.java:647) ~[iri-1.1.3.10.jar:na]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at com.iota.iri.network.Node.lambda$null$6(Node.java:171) ~[iri-1.1.3.10.jar:na]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at com.iota.iri.network.Node.lambda$null$7(Node.java:170) ~[iri-1.1.3.10.jar:na]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_131]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at com.iota.iri.network.Node.lambda$null$8(Node.java:158) ~[iri-1.1.3.10.jar:na]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890) ~[na:1.8.0_131]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at com.iota.iri.network.Node.lambda$spawnNeighborDNSRefresherThread$9(Node.java:156) ~[iri-1.1.3.10.jar:na]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_131]
May 30 09:15:45 vmi111313.contaboserver.net java[22975]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_131]

**Comment by alon-e** [comment]
Duplicate as #136
