### ISSUE TITLE
We check for the existence of spent-addresses-db by looking for sst files

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1461]
### Bug description
We check for the existence of spent-addresses-db by looking for sst files. This is a problem because all the data may be in WAL and we may see no sst files

### IRI version
1.7.0

### Steps To Reproduce
1. Run IRI with compass for a short time and get some transactions confirmed. Make sure local snapshots are activated and one was taken
2. Stop IRI and restart
3. The node should report an empty spent address db -> bug

**Comment by jakubcech** [comment]
We should read from the and if we get a value/check the DB is not empty we assume the DB is there.

**Comment by GalRogozinski** [comment]
Duplicate of #1360

**Comment by GalRogozinski** [comment]
See https://github.com/iotaledger/iri/issues/1429

**Comment by GalRogozinski** [comment]
The check will be disabled for testnet mode since testnets may have no value transactions.
In mainnet we will read the actual database and not look for sst files.
