### ISSUE TITLE
Merge spent addresses DBs from different sources

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1462]
### Description
I want to be able to merge different spent address DBs from different sources.
This will use the export built here #1450

We will use an IXI.  

### Motivation
Be able to have a representation of the `spent-addresses-db` that takes addresses from multiple sources. 

### Requirements
1.  I take a `spentAddress.txt` files generated by individual nodes (#1450)
2. I merge the files into one `spent-addresses-db`, leaving out duplicates (the rocksDB bloom filter should satisfy the duplicates requirement)
3. I'm able to use the DB in any node

**Comment by kwek20** [comment]
IXI is here for now: https://github.com/kwek20/iri-extensions
Implementation can still change

Will be moved over to an iotaledger repo soon.

You can also add multiple files in one go by supplying files=["file1.txt", "file2.txt"]

**Comment by jakubcech** [comment]
Closing. Sadjy merged on internal nodes.
