### ISSUE TITLE
Regression test: Milestone candidate processing

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1464]
### Description
We need a regression test that ensures that candidate milestone processing behaves correctly. 

### Motivation
Describe why the regression test is needed.

### Issues / Scenarios
Describe the issues/scenarios addressed by this test
1. A node that does X and Y crashes. 
2. Blowballs are being formed when... 

### How to test for this
Provide the steps on creating the actual test.

**Comment by GalRogozinski** [comment]
We have other regression tests plus a syncing test in the works that replaces this
