### ISSUE TITLE
Clean up initialization code and inject dependencies

### ISSUE THREAD

**Issue by georgmittendorfer** [iotaledger/iri#1470]
### Description

IRI initialization code should be improved to make testing of classes easier and the current code easier to read.

For that classes should get all their dependencies via their constructor and the current initialization code should be refactored to do that in an uniform way.

That is mainly relevant for the `main` method and the `Iota` class  but in a wider sense also for all other classes that (statically) reference methods (random example: `SnapshotServiceImpl` and `DAGHelper`).

### Motivation

Currently IRI initialization is a bit messy (creation of instances, calling of init methods, public fields). Although it has already been refactored and the major issues (static member access from different places) are already resolved it is still possible to improve the initialization code and the way how dependencies get into the right classes to

- Make initialization code easier to understand.
- Make code easier to test by injecting all relevant dependencies.

### Requirements

- There should be an uniform way how the classes are created on startup.
- Classes should get all relevant dependencies via their constructor (constructor injection).
- Public fields in `Iota` class should be removed.

### Open Questions / Discussion

- DI can be done manually or via some framework (Guice is in discussion).

- I suggest that the scope of the issue is in simply cleaning up the `main` method and `Iota` class code. After that it is easier to refactor other classes (e.g. by replacing static dependencies with injection).

### Am I planning to do it myself with a PR?

Yes, but if someone else wants to do it that is OK for me. Please contact me in this case so that we don't do duplicate work.

**Comment by lukazd** [comment]
Maybe this should be part of a separate issue, but I think it would be a good idea to start using builders for some of these classes rather than constructors of all parameters. Classes like API have such a large number of parameters it would improve readability and make future changes easier, especially if any parameters are optional, but I don't know if that is the case.

**Comment by georgmittendorfer** [comment]
The large constructors are a code smell. I think it is better not to hide code smells but to fix the classes so that the large constructors are not needed anymore.

But that is not in scope here and could be done in a separate issue.
