### ISSUE TITLE
Investigate the `repairing corrupted milestone` issue - follow-up

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1493]
### Description
We've timeboxed the investigation here: https://github.com/iotaledger/iri/issues/1435
Closing that in favor of a new issue so the investment can be tracked better.

We should try reproducing the issue now with this fix in:
https://github.com/iotaledger/iri/pull/1492

**Comment by tylerw1369** [comment]
I don't know if this helps but I believe I was able to find out why my corrupt milestones were happening.  I believe when I changed my kernel using Ubuntu to 5.1.* I started to get them.  Since I changed back I haven't gotten one.  *knock on wood*  just though maybe you could try that to test getting corrupted milestones.

**Comment by zoran** [comment]
on one of my perma nodes the problem has usually appeared within a few days after an IRI restart. I started this node with the fix of @luca-moser a week ago and the problem seems to be fixed.

**Comment by jakubcech** [comment]
Please re-open if we see the issue again.

**Comment by cyclux** [comment]
@jakubcech Unfortunately I experienced this issue again. IRI 1.8.0 default settings (with snapshotting enabled). Can provide example logs via DM but they do not seem to reveal anything further except the `[Latest Solid Milestone Tracker] INFO  MilestoneServiceImpl:554 - resetting corrupted milestone #xxxxxxxx` line.

**Comment by jakubcech** [comment]
Darn :/, maybe different, less common race condition now? Thanks for letting us know. What's the DB size on the node?

**Comment by cyclux** [comment]
@jakubcech Unfortunately I can not tell the exact size now as I had to fix it quickly (production system). However, with default settings (+snapshotting) and current TPS I assume it was not too big. If I remember correctly default snapshot settings was around 30 days of history.

**Comment by jakubcech** [comment]
Thanks Cyclux.

Let's wait and see if this pops up for anyone else.

**Comment by jakubcech** [comment]
Closing for now.
