### ISSUE TITLE
Make the codacy bot not duplicate the same message

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iri#1499]
### Description
The codacy bot currently analyzes the code of PRs up on each push to the given branch. Unfortunately the bot doesn't seem to be clever enough to understand, that it already left a given message/analysis at the same line of code, creating duplicated messages N * commits.

![image](https://user-images.githubusercontent.com/1385611/59599085-fe5acd00-90fd-11e9-9b11-e5af1fb198cd.png)

![image](https://user-images.githubusercontent.com/1385611/59599099-031f8100-90fe-11e9-9fc2-c590104bdc52.png)

### Motivation
Without this fixed, it makes PRs hard to review because of unnecessary spam from the bot.

### Requirements
* Let the bot only write a given message once on the same line of code.

### Am I planning to do it myself with a PR?
No.

**Comment by GalRogozinski** [comment]
I have talked with codacy support about this, and they opened an internal bug. I will keep in contact with them. In the meanwhile, if it happens again, it is better not to delete the extra comments so they can investigate

**Comment by GalRogozinski** [comment]
I believe the issue is now resolved.
There was a problem since Alon's permissions on IRI were revoked in github but not on codacy.
