### ISSUE TITLE
Fix: Change logging level of existing tx removal

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iri#1509]
### Description
This logging happens too often, and spams the console. This makes me miss other, more important, messages.

Example: 
```
07/11 02:55:40 [pool-1-thread-1] INFO TransactionRequester:145 - Removed existing tx from request list: ADIJF9BHADBFH9OB9ADFHDAH...CPIAHS9FDJHQEGHPQBDV9IPQ9HBEPGB
```

### Motivation
I dont like spam in my console

### Requirements
Changing the log on the following line to a less verbose level
https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/network/TransactionRequester.java#L145

### Open Questions (optional)
no

### Am I planning to do it myself with a PR?
Yes.

**Comment by GalRogozinski** [comment]
You want to change it to DEBUG? or you wanted to something else?
