### ISSUE TITLE
1.8 IrI Node Install help

### ISSUE THREAD

**Issue by dlapc** [iotaledger/iri#1514]
Hello I am running a vsp install.

I successfully cloned the Github Iri.

When I go to run 
Root"""target# Java -jar iri 1.8.1.RELEASE.1 -p 14265 

It responds with an error. Apologize if the code isnt spelled accurately but there is where I am failing in my node install. The guide I am using has an old version of Iri and I feel like the port number is not correct either. Can someone help my find/lookup my port and the correct java code to get the new iri to install and or start.  When I run PX I get a bunch of info I dont quite understand. 

I am using Ubunutu, with Putty connecting to my VPS.

It's my first crack at it. The Nuriel77 iri github wasnt working at first. Yesterday I made it all the way to the IrI install I just couldnt test whether or not its working. I need to figure out the max and min ports to write the Nano file which is the very next step so I can have my Iri execute the Nano parameters.

I apologize upfront if the terminology is off, I am new at this. I am willing to learn if someone can point me towards a good guide etc..

I appreciate your time, I look forward to running several nodes, I believe in Iota.

Best

**Comment by kwek20** [comment]
Hello @dlapc 

Thank you for your ticket!
If you need support for setting up a node, discord is a better place to find help.
You can try our `fullnodes` channel.
https://discordapp.com/channels/397872799483428865/398599962377846784

Once you got it set up, also check out the `nodesharing` channel, to find some neighbours!

From a quick glance, the following command should work: `java -jar iri-1.8.0-RELEASE.jar -p 14265`. (Port 14265 is set by default, so you dont actually need to specify it)

Please check out discord for further assistance

**Comment by dlapc** [comment]
I cannot get into the discord channel to ask for help.

The error I get is that iri.18.RELEASE.jar not found

Hector Lorenzo CPA
Drosos Lorenzo & Associates PC
77 Union Street, Dover, NJ 07801
Office: 973-512-4030
Fax:     973-512-4031
