### ISSUE TITLE
UI.notify: Ledger balance incorrect: -87

### ISSUE THREAD

**Issue by achim-heiniger** [iotaledger/iri#152]
Running a spammer (Nostalgia) and logging into the GUI (2.2.4) at the same time results in some error popups being displayed in the GUI:
"UI.notify: Ledger balance incorrect: -87"

**Comment by paulhandy** [comment]
Have you updated to 2.2.5 / 1.1.4.2?

**Comment by alon-e** [comment]
fixed in 1.1.4.3
