### ISSUE TITLE
Update spent address import and export IXIs to support new spent address DBs

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1525]
### Description
Update the IXIs that import and export to support new spent address DBs. Might just work. Might not work. :) 

### Motivation
Import and export IXIs support the new DB schema. 

### Requirements
- [ ] I can use the import IXI without with the merged local snapshot + spent address DB
- [ ] I can use the export IXI without with the merged local snapshot + spent address DB

**Comment by GalRogozinski** [comment]
Since we have https://github.com/iotaledger/iri-ls-sa-merger/ I am closing this.
It may reopen if we see that we need this tool (maybe for regression tests)
