### ISSUE TITLE
Make a cache benchmark 

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iri#1527]
### Description
In order to get measurable results for the cache, we need a benchmark.

Should be an JMH test.

### Motivation
We want to know if it increases/decreases various loads of a node. 

### Requirements
- [ ] We run the JMH test with and without the caching changes. Monitor the I/O, Memory, CPU consumption.
- [ ] Add persistBatch to the existing `rocksDB` tests that we have.
- [ ] Run it a couple times on a Hetzner node.

### Open Questions (optional)
Any other  things we should test?
How do we want to test this specifically, without having to mimic natural network interaction

**Comment by GalRogozinski** [comment]
Duplicate of #1628
