### ISSUE TITLE
Tangle DB should _not_ be stored in %APPDATA% on Windows.

### ISSUE THREAD

**Issue by MicahZoltu** [iotaledger/iri#153]
On Windows, `%APPDATA%` roams across the network on login/logout.  Files written here should be measured in KB, not in GB.  For user-specific cache files like the Tangle DB, they should be written to `%LOCALAPPDATA%` instead.

Having the tangle DB written to `%APPDATA%` can destroy a network since it will sync on login/logout and it can render a user's account inoperable until an admin manually addresses the issue.  Users in a corporate/school network also often have a quota and filling it with the tangle DB will make it so none of their _actual_ roaming data will sync until the tangle is deleted.

**Comment by alon-e** [comment]
hey,
good point, but this is a GUI Wallet issue,
IRI itself doesn't write to %APPDATA%
can you re-open the ticket on https://github.com/iotaledger/wallet/issues ?

**Comment by MicahZoltu** [comment]
Sorry, I assumed this was an IRI issue.  https://github.com/iotaledger/wallet/issues/83
