### ISSUE TITLE
getNeigbors 'domain' attribute should contain IP if empty

### ISSUE THREAD

**Issue by codepleb** [iotaledger/iri#1536]
### Description
`getNeighbors` returns IPs and domains. Sometimes, for whatever reason, `domain` is not there. It should IMHO always be there and contain the IP in those cases.

### Motivation
On the tooling side, this causes a lot of nullchecks, that somehow look so unnecessary.

### Requirements
`IF domain === undefined THEN domain = address`

### Am I planning to do it myself with a PR?
No

**Comment by jakubcech** [comment]
Is the domain field missing completely or is the issue with the returned value being domain="" ?

**Comment by TeeVeeEss** [comment]
The domain field is missing completely, causing confusing output in tools like Iota peer manager. As soon as the domain name is not in the json, ipm shows 2 graphs of the neighbor: 1 with the ip-address as title and 1 with the dns-name as title. The one with the dns-name is shown as dead neighbor with 0 tx. The node operator acting on this visual sign could take the wrong conclusion and will delete a healthy nbr.

**Comment by jakubcech** [comment]
+ regression test fixes.

**Comment by jakubcech** [comment]
#1580

**Comment by luca-moser** [comment]
I will apply following logic to the fix:
* if the neighbor is connected and there's no mapping to a domain, the IP address will be set in the `domain` field
* if the neighbor is connected and there's a mapping to a domain, the domain will be set in the `domain` field
* if the neighbor is not connected, the neighbor was added using an URI with a domain (tcp://example.com:15600) and during the call to `getNeighbors()` the domain can't be resolved to an IP address, the `domain` field will contain the domain name and the `address` field will be empty
* if the neighbor is not connected, the neighbor was added using an URI with an IP address (tcp://1.1.1.1:15600), the `domain` field will contain the IP address and the `address` field will contain the IP address + port combination
* if the neighbor is not connected, the neighbor was added using an URI with a domain (tcp://example.com:15600) and during the call to `getNeighbors()` the domain could be resolved to an IP address, the `domain` field will contain the domain name and the `address` field will contain the IP address + port combination.

Tools using `getNeighbors()` should check whether the given neighbor is connected and be agnostic to that. A peer/neighbor manager should map the domain to an IP address as the identifier for the object representing the connection and if there's no IP address to be resolved, use the domain or another mechanism as a placeholder. If the underlying IP address of a domain changes, you need to update the key of your tool which identifies the connection.

**Comment by GalRogozinski** [comment]
Each one of the above bullet points is a regression test
