### ISSUE TITLE
Output of address and domain in getNeighbors is confusing

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/iri#1558]
The handling of _domain_ and _address_ in `getNeighbors` is somewhat confusing since V1.8.0. Adding a neighbor is usually done by the dns name like tcp://example.com:15600. Iri resolves this to the ip-address and shows both in `getNeighbors` : 
```
{
  "neighbors": [
    {
      "address": "666.77.888.999:15600",
      "domain": "example.com",
      "numberOfAllTransactions": 123456,
     ...
```
However: if the dns name example2.com of another neighbor by whatever reason can't be resolved , the _address_ will be the dns name and _domain_ is not shown in the output:
```
...
    {
      "address": "example2.com:15600",
      "numberOfAllTransactions": 0,
    ...
 ```
This is probably creating problems when other programs are parsing the output of ``getNeigbors`` and expect to always find _address_ and _domain_.

**Comment by GalRogozinski** [comment]
Related to #1536

**Comment by jakubcech** [comment]
Thanks, we'll use #1536 to resolve this. Both fields should always be returned. If the DNS name cannot be resolved, it should just be empty.
