### ISSUE TITLE
Wrong data length calculation in AbstractHash

### ISSUE THREAD

**Issue by spangin** [iotaledger/iri#1566]
### Bug description
The class AbstractHash has the line in the constructor:

`System.arraycopy(source, sourceOffset, dest, 0, sourceSize - sourceOffset > source.length ? source.length - sourceOffset : sourceSize);`

It looks like a misspelling: "sourceSize - sourceOffset" instead of  "sourceSize + sourceOffset"

### IRI version
1.5.6 - 1.8.1

**Comment by GalRogozinski** [comment]
I don't think it is a typo...
I think this whole condition is weird...

`sourceSize` is the expected size of the hash

`sourceOffset` is where we start reading from a huge list of bytes (see `Hashes#read`) and it can theoretically be very big...
Not sure why we should add or subtract them at all...

Anyhows the expected result should always be `sourceSize` or `Hash.SIZE_IN_BYTES`

**Comment by kwek20** [comment]
Yes after double checking it, its correct, we count "backwards" to check if we can copy, instead of "regular ways"

**Comment by spangin** [comment]
Yes, the condition is weird.
Besides, this condition is not enough to prevent incorrect input data. Also if the hash is created with incorrect input data, it will be hard to find a reason of the problem.

At this moment NullPointerException is a result of the constructor call if `source` is null. So maybe it's better to remove the condition and have ArrayIndexOutOfBoundsException as a result if `sourceOffset` and `sourceSize` are incorrect. What do you think of it?

**Comment by GalRogozinski** [comment]
Did you see a NullPointerException happen?
Or you're just talking theoretically?

I agree with you though...
In my opinion IRI works fine with this bug, meaning we maybe can just delete the condition and always use `sourceSize`.

**Comment by spangin** [comment]
I didn't see NullPointerException with real data. But it's easy to write a test function to get this exception from AbstractHash or HashFactory. E.g. in HashTest.java:
```
@Test
public void nullSourceTest() {
  Hash hash = HashFactory.TRANSACTION.create(null, 0, Hash.SIZE_IN_BYTES);
}
```
The result of this test will be NullPointerException from AbstractHash constructor at line:
`System.arraycopy(source, sourceOffset, dest, 0, sourceSize - sourceOffset > source.length ? source.length - sourceOffset : sourceSize);`

**Comment by GalRogozinski** [comment]
Ok
Just wanted to make sure it didn't happen in real lif

**Comment by jakubcech** [comment]
"The expected result should always be sourceSize or Hash.SIZE_IN_BYTES"

This should be the solution. Would you like to make a PR for this @spangin ? :)

**Comment by spangin** [comment]
PR was created:
https://github.com/iotaledger/iri/pull/1589

**Comment by spangin** [comment]
> `sourceSize` is the expected size of the hash

To avoid misunderstanding... The expected size of the hash is always `Hash.SIZE_IN_BYTES`.
Probably you mean source data size. I agree in this case and suggest: to cut data if the data is too big and add zeros to the end if the data is too short.
 
> `sourceOffset` is where we start reading from a huge list of bytes (see `Hashes#read`) and it can theoretically be very big...

The data source can be big, but the hash stores `Hash.SIZE_IN_BYTES` bytes maximum and ignores other bytes. (and I suggest to implement the same behavior for the constructor with parameters)
We can see correct data reading in `read `method:
https://github.com/iotaledger/iri/blob/6769054eb05b07639d714d67eeb34d022e5fe1bd/src/main/java/com/iota/iri/model/AbstractHash.java#L63

**Comment by GalRogozinski** [comment]
This is old code.

To be honest with you I am not sure in what cases the input to the `read` method should ever have `bytes.length > dest.length` and probably we should be throwing an Exception here as well.

To be even more honest, this `read` method is a blasphemy. The `Hash` objects should be immutable.

**Comment by spangin** [comment]
>The `Hash` objects should be immutable.

I agree, and it's easy: methods `bytes()` and `trits()` have to return a copy of data, but it's bad for memory and performance.

> To be honest with you I am not sure in what cases the input to the `read` method should ever have `bytes.length > dest.length` and probably we should be throwing an Exception here as well.
> To be even more honest, this `read` method is a blasphemy.

Sure, Hash-objects have to be created via `HashFactory`. It could be implemented in `RocksDBPersistenceProvider `easily instead of using `read()`.

>This is old code.

Yeah. As usually there is no time and money for refactoring during the development to have a good code.
If you don't mind and need a good code for Hash-classes, I could make a refactoring.
