### ISSUE TITLE
Latest release said it was a testnet version

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/iri#157]
I was updating to the latest release and when I ran `mvn package` it mentioned the testnet and I was confused because I wanted to download the mainnet version
![image](https://user-images.githubusercontent.com/19519564/26855151-68a9f8f2-4ae7-11e7-876c-669fe965e0dc.png)

**Comment by rajivshah3** [comment]
I fixed this in pull request #158

**Comment by paulhandy** [comment]
#158 merged
