### ISSUE TITLE
URW tip explosion test

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1594]
### Description
We want to try different attacks on nodes using URW on a private network before we perform tests on ICC/Mirrornet/Devnet. 

### Motivation
1. Evaluate the safety URW against known attacks. 
2. Compare behavior to the current approach. 

### Requirements
- [ ] Set up a private network with 1 node and Compass (e.g., with TIAB)
- [ ] Conflicting value transactions / Tip explosion attack 
      - Emit a single transaction that you aim to censor.
      - Surround the transaction constantly with conflicting transactions.
      - If the transaction gets ignored then you've succeeded.
- [ ] Post the results for each attack (on Confluence), compare to the current implementation of IRI. We can use the Splitting page on Confluence for a motivation on results summary. 
- [ ] Perform the same tests on an unchanged version IRI for comparison as well. Same conditions, DB, machine, TPS, calls.

**Comment by kwek20** [comment]
Transactions are able to be censored progressively easier as you make more tips/conflicting transactions on the network. This is just like the current situation.
![Screenshot (16)](https://user-images.githubusercontent.com/1417565/65824461-e0a71300-e269-11e9-9107-2c7744cf554a.png)

Same like the splitting attack, which is almost siliar, reposting to make it easier to look back
![Screenshot (12)](https://user-images.githubusercontent.com/1417565/65824466-fddbe180-e269-11e9-9ceb-4fb3835f9881.png)
