### ISSUE TITLE
Generate new DBs for the spent addresses test to pass

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1595]
### Description
Our regression tests with local snapshot files. The way the files work is now changing with in #1584, and we need to create new DB(s) for the tests to work. 

A tool that converts spent address files and local snapshot files to RocksDB data. 
Update the regression tests to use the DB. 

### Motivation
Regression tests pass. 

### Requirements
- [ ] A tool that converts spent address files and local snapshot files to RocksDB data. 
- Update the regression tests to use the DB.

**Comment by luca-moser** [comment]
Tool is now available under: https://github.com/luca-moser/iri-ls-sa-merger
