### ISSUE TITLE
ZMQ documentation is not up to date...

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1597]
### Description
While closing #1072 we accidentally stopped publishing the following ZMQ topics:

* `rts` information about walk terminations
* `dnscv` neighbor DNS validations
* `dnscc` neighbor DNS confirmations
* `dnscu` neighbor DNS updates
* `hmr` for the hit to miss ratio
* `antn` for added non-tethered neighbors ( testnet only )
* `rntn` for refused non-tethered neighbors
* `rstat` for information about the tips requester
* `rtl` for transactions randomly removed from the request list 

### Requirements
We need to decide between:
1. Restoring them
2. Deleting from documentation because lack of complaints means that no one uses them

**Comment by muXxer** [comment]
Better delete that. :) 
We didn't implement them in HORNET.
I think they are not used.

**Comment by GalRogozinski** [comment]
Will delete

**Comment by GalRogozinski** [comment]
Need to make sure that https://docs.iota.org/docs/node-software/0.1/iri/references/zmq-events is up to date as well
