### ISSUE TITLE
Invalid Transaction Error

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#16]
> 14:56:08.322 [pool-1-thread-1] ERROR com.iota.iri.service.Node - Invalid Transaction Error:
> java.lang.IndexOutOfBoundsException: null
> 	at java.nio.Buffer.checkIndex(Buffer.java:540)
> 	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
> 	at com.iota.iri.service.storage.Storage.setAnalyzedTransactionFlag(Storage.java:147)
> 	at com.iota.iri.service.storage.Storage.transactionToRequest(Storage.java:103)
> 	at com.iota.iri.service.Node.lambda$spawnReceiverThread$5(Node.java:124)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> 14:56:08.336 [Latest Milestone Tracker] ERROR com.iota.iri.service.TipsManager - Error during TipsManager Milestone updating
> java.lang.IndexOutOfBoundsException: null
> 	at java.nio.Buffer.checkIndex(Buffer.java:540)
> 	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
> 	at com.iota.iri.service.storage.Storage.setAnalyzedTransactionFlag(Storage.java:147)
> 	at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:113)
> 	at com.iota.iri.service.TipsManager.lambda$init$0(TipsManager.java:43)
> 	at java.lang.Thread.run(Thread.java:745)

**Comment by pinpong** [comment]
While getting this error few times the node freeze and its not possible to get a response.

**Comment by davassi** [comment]
This is not a bug, you received an invalid transaction.

**Comment by domschiener** [comment]
@pinpong can you recreate the issue of the node freezing? If the node freezes, no API calls work anymore right?

**Comment by pinpong** [comment]
I don't think so. This 2 errors spams the log and not allow any response from the node.

**Comment by davassi** [comment]
@pinpong about The invalid transaction error:
"it's caused by a peer. getting this error several times check result of "getNeighbors", only 1 or 2 neighbors will have non-zero invalid tx counters probably remove them from the list of neighbors" (quote from @Come-from-Beyond)

**Comment by davassi** [comment]
TipsManager error should be fixed by now in dev. Are you still experiencing node freeze? (I never experienced such condition...yet)

**Comment by davassi** [comment]
Hum can I close this issue now?

**Comment by pinpong** [comment]
Can be closed.
