### ISSUE TITLE
How to add a neighbor?

### ISSUE THREAD

**Issue by abyssal0** [iotaledger/iri#1603]
I can't find  the #nodesharing channel on Discord,How to get a neighbor???

Add the URLs or IP addresses of your neighbor IRI nodes to the NEIGHBORS configuration parameter.
What is the writing format for multiple URLs or IP???
NEIGHBORS =

**Comment by jakubcech** [comment]
We'll add an example to the topic I think it is due. :)

**Comment by abyssal0** [comment]
Thanks. I have solved the problem
