### ISSUE TITLE
Can't run docker Image 

### ISSUE THREAD

**Issue by yehia67** [iotaledger/iri#1605]
I follow this tutorial : https://docs.iota.org/docs/getting-started/0.1/tutorials/run-your-own-iri-node
and when I write this command to run the docker image: `docker run --name iri iotaledger/iri:latest --remote -p 14265`

it gave me this error
```
yehia@yehia-Iaptop:~$ docker run --name iri iotaledger/iri:latest --remote -p 14265
Logging - property 'logging-level' set to: [INFO]
09/09 09:34:03.541 [main] ERROR IRI$IRILauncher:183 - There was a problem parsing commandline arguments: "--remote": couldn't convert "-p" to a boolean
```
Do you know what could cause this error.
Thanks in advance.

**Comment by HBMY289** [comment]
You need to pass a boolean argument for the option remote:
`--remote true`
