### ISSUE TITLE
Stop submitting tasks for zero value bundles into the SpentAddressService

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iri#1613]
### Bug description
During ledger balance diff computation bundles are submitted to the SpentAddressService for spent addresses persistence. We don't need to do that for zero value bundles. Under high load, this simply taxes the CPU for no good reason.

![image](https://user-images.githubusercontent.com/1385611/64705861-edc5b300-d4b0-11e9-8b99-77d40aed3d03.png)

### IRI version
Everything

### Hardware Spec
A desktop machine

### Steps To Reproduce
1. do `getTransactionsToApprove`
2. plugin your profiler
3. see this issue taking up unnecessarily CPU

**Comment by GalRogozinski** [comment]
Fixed by #1614
