### ISSUE TITLE
Create an RC with URW changes

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1619]
### Description
Create a version of IRI with URW, perform the tests that are part of the release process and release an RC version of it. 

### Motivation
Have a testable version of IRI with the first changes to tipsel. 

### Requirements
- Perform steps and tests up to step 5 of the release process.

**Comment by GalRogozinski** [comment]
ICC TEST #1:
We had 3 gtta spammers spamming different nodes plus a zmq spammer with heavy spam.
The result was that each spammer created chains including compass.

Farther investigation is needed.
We believe that the heavy spam caused nodes to not solidify.
So we should put #1484 merge in priority. We should also make sure that any updates to transaction metadata (solidity) should become immediately visible (currently it goes through RocksDb).
