### ISSUE TITLE
ICC tests for 1.8.2-RC-1

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iri#1640]
### Description

Comparison between zero value `α` and non zero `α` (0.001 - default per 1.8.1):
* **Test Zero Value Transaction GTTA Throughput (ZVGT)**: The amount of throughput all the nodes in the ICC network are able to issue by simply using `getTransactionsToApprove` at depth 3 with zero value transactions. Gives us a baseline for future improvements and also shows how much faster the zero `α` is (or allegedly is). 
**How this test is executed:** We run a single spammer instance, which each targets a single node and we let them all execute simultaneously. Example: We have 7 nodes in the ICC network and we let 7 spammer instances each use a separate node for the `getTransactionsToApprove` calls. The test will run for 10 minutes.
* **Test Value Transaction GTTA Throughput (VTGT)**: Like ZVGT but with value transaction spam/bundles which use security level 3 (in order to have heavier signature verification), meaning bundles which resolve to a zero sum but don't spend any actual balance from an address -> Spending 5 Ti from address A and depositing it to address A in the same bundle. The value bundle is pre-created and used sub-sequentially for each issuance so that signing the bundle doesn't take any time.
* Resource usage difference between zero `α` and non zero `α` (0.001) on a node on which `getTransactionsToApprove` is getting called on **Test ZVGT** and **Test VTGT**:
  * CPU usage (delta %)
  * Memory usage (delta %)
* **Test Maximum Sustainable Throughput (MST)**: At which throughput the node to which Compass connects to, will be unable to deliver the tips in 60 seconds using zero value transactions. We ramp up the TPS continuously until we reach the limit. - **can only be tested if we create a spammer which can create a 'good' cone in which the IRI node to which Compass connects to, walks the graph.**

We will use Brord's Grafana dashboard to get charts for:
* CPU/Memory usage
* TPS and milestone issuance rates

At the end we will post the charts showing the difference between the two `α` values.
The overall time for the tests will approx. take 1.5 hours.

**Comment by kwek20** [comment]
Test ZVGT results:
![Screenshot (19)](https://user-images.githubusercontent.com/1417565/66666729-96eaff00-ec51-11e9-8d11-e759ee1b4a65.png)
![Screenshot (20)](https://user-images.githubusercontent.com/1417565/66666733-994d5900-ec51-11e9-8ab4-ed8028cf65ea.png)

**Comment by kwek20** [comment]
Test VTGT results:
Alpha 0:
![Screenshot (21)](https://user-images.githubusercontent.com/1417565/66668962-c2241d00-ec56-11e9-8261-41e80110711a.png)
![Screenshot (22)](https://user-images.githubusercontent.com/1417565/66668963-c3554a00-ec56-11e9-8d76-8d5dfa774536.png)

**Comment by luca-moser** [comment]
Zero value transaction: zero alpha vs. non zero alpha: 140%
