### ISSUE TITLE
How to connect to a neighbor

### ISSUE THREAD

**Issue by love386** [iotaledger/iri#1648]
{
  "appName": "IRI",
  "appVersion": "1.8.2-RELEASE",
  "jreAvailableProcessors": 4,
  "jreFreeMemory": 2093481960,
  "jreVersion": "1.8.0_222",
  "jreMaxMemory": 3221225472,
  "jreTotalMemory": 2362441728,
  "latestMilestone": "DDAZVKKBLOVOZMECPJERLBNELHDZEULMPQOUPFZIAJBYYNLJJXHEGSOCG9JCJZGX9HGBDHVNSOZP99999",
  "latestMilestoneIndex": 1224689,
  "latestSolidSubtangleMilestone": "DDAZVKKBLOVOZMECPJERLBNELHDZEULMPQOUPFZIAJBYYNLJJXHEGSOCG9JCJZGX9HGBDHVNSOZP99999",
  "latestSolidSubtangleMilestoneIndex": 1224689,
  "milestoneStartIndex": -1,
  "lastSnapshottedMilestoneIndex": 1224689,
  "neighbors": 0,
  "packetsQueueSize": 0,
  "time": 1572320704499,
  "tips": 0,
  "transactionsToRequest": 49,
  "features": [
    "dnsRefresher"
  ],
  "coordinatorAddress": "EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9",
  "duration": 0
}

os:ubuntu18.04

**Comment by love386** [comment]
![image](https://user-images.githubusercontent.com/45838695/67744215-e1df8180-fa5b-11e9-96c2-b662c9c10125.png)

![image](https://user-images.githubusercontent.com/45838695/67744228-e99f2600-fa5b-11e9-8ae1-8b8e282c43fb.png)

**Comment by kwek20** [comment]
Getting neighbors is not happening automatically.

You are free to join our node operators channel on discord: https://discord.iota.org/
Join channel #nodesharing
