### ISSUE TITLE
Create an initial framework for caching

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1659]
# Description
Create a design for caching support

### Motivation
First step to add caching.

### Requirements
The `Tangle` class should have a `CacheManager`.
A `CacheManager` should store a collection `Caches`.
A `Cache` is a thread-safe map an a `CachingPolicy`.

`CachingPolicy` is a collection of properties that tell us:
1. The max size of each cache
2. An eviction policy: LRU, FIFO
3. How many elements to evict at a certain time.
4. Usage of weak/soft references
5. Flag that will force elements to be read from the DB for reading variable values that will never be completely in cache. (Need to think about it, maybe we never cache such long values).

### Open Questions (optional)
Will add them in a meeting :-)

**Comment by GalRogozinski** [comment]
Look for guava's MapMaker

**Comment by GalRogozinski** [comment]
This issue is not about implementing caching yet...
Just adding the initial support

**Comment by acha-bill** [comment]
@GalRogozinski should there be an option for the `Cache` to store `null` values?
Something like `isNullAllowed`

**Comment by GalRogozinski** [comment]
I think currently we shouldn't allow nulls or at least we make sure that they don't cause data to be deleted from the db

**Comment by GalRogozinski** [comment]
Extra requirements:
1. We must have the concept of "fresh" entries. "Fresh" entries are transactions that were never written to the DB so they must be evicted to it.
2. We must have a concept of "dirty" entry. Meaning that when a mutable entry has been changed in the metadata (i.e. solidity, snapshot index) then it must be updated in the
3. We need to make sure that dirty entries are being rewritten to the DB.

**Comment by acha-bill** [comment]
@GalRogozinski maybe we want to come back to using a `ValueWrapper` that will hold the entrys' state in addition to its value?

**Comment by GalRogozinski** [comment]
Resolved by #1672
