### ISSUE TITLE
Improve API error response of storeTransactions

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iri#1679]
### Description
Better feedback on what went wrong with the storeTransactions call

### Motivation
`Invalid trytes input` is the current feedback, whilst we actually have the reason, but mask it

### Requirements
API `storeTransactions` method should add the message of the thrown error in the ErrorResponse.create, preferably in the following format:

`"Invalid trytes input:  " + e.getMessage()`

### Open question
Should we change the return of `TransactionValidator.runValidation` at the MWM check from "Invalid transaction hash" to "Invalid weight magnitude"

**Comment by GalRogozinski** [comment]
> Should we change the return of TransactionValidator.runValidation at the MWM check from "Invalid transaction hash" to "Invalid weight magnitude"

good idea
