### ISSUE TITLE
Enhancement: jgitflow over git flow

### ISSUE THREAD

**Issue by bluedigits** [iotaledger/iri#168]
I would like to make a proposal on using jgitflow (https://bitbucket.org/atlassian/jgit-flow) instead of standard git flow. It has some edges over the standard git flow which you could leverage, since the IRI project is maven-based:

- It is configurable. You can configure in your pom, how your tags should be prefixed, same applies for feature-, bugfix- and hotfix branches
- You don't have to manual push the finished branches/releases
- It runs the tests before finishing a feature/release so you never integrate branches accidentally, if the unit tests get red
- It includes a release plugin, which manages your pom versions (configurable) and tags your finished release
- Even submodule autoversioning would be feasible

Of course, jgitflow wouldn't restrict you from anything the original git flow branching model offers. 

I want to give you an usage example: You want to open a feature branch based on the integration branch (i.e. 'dev' normally) and want to checkout this new branch. Additionally, more than one developers are involved in that particular feature, thus, you might want to push it, so that all developers could start at the same time:
`mvn jgitflow:feature-start`, and that's it!

Or a little comparison:
We want to open a release branch and finish it right afterwards.

**Release start with manual git flow:**
`git checkout develop`
`git pull origin develop`
`git checkout -b releas­e/­rel­eas­e-v­ersion`

Now, you have to man­ually update your code version to release branch naming conven­tio­ns

**Release finish with manual git flow:**
sta­rting from releas­e/­rel­eas­e-v­ersion branch
`git commit -am "your release changes comment here"`
`git pull origin releas­e/­rel­eas­e-v­ersion`
`git checkout develop`
`git pull origin develop`
`git merge releas­e/­rel­eas­e-v­ersion`

Now, you normally would man­ually update your code version to stable version naming conven­tio­ns. Followed by:

`git commit -am "­re­lea­se-­ver­sio­n"`
`git checkout master`
`git pull origin master`
`git merge releas­e/­rel­eas­e-v­ersion`
`git commit -am "­re­lea­se-­ver­sio­n"`
`git tag relea­se-­ver­sion`
`git push origin master --tag`
`git checkout develop`

Now, you have to man­ually update your code version to next develop version naming conven­tio­ns.

`git commit -am "­ne­xt-­ver­sio­n"`
`git push origin develop`
`git branch -D releas­e/­rel­eas­e-v­ers­ion`

A lot of overhead, right?

Now, I can show you, how you would do the same with jgitflow.

**Release start with jgitflow:**
`mvn jgitfl­ow:­rel­eas­e-start`

Followed by:

**Release finish with jgitflow:**
`mvn jgitfl­ow:­rel­eas­e-f­inish`

That's all!

With jgitflow you get:
- A new release/hotfix/feature branch, which follows the naming convention of a configured prefix (e.g. "feature-") and a task name you are prompted for, e.g. "improveTxHandling". Your final branch name would look like: feature-improveTxHandling
- You're already on this branch after creation
- The new branch was pushed already to the remote origin

Probably, that would fit your needs?

**Comment by GalRogozinski** [comment]
We will be using a custom flow with buildkite that suits our needs
