### ISSUE TITLE
Make caching optional and configurable.

### ISSUE THREAD

**Issue by acha-bill** [iotaledger/iri#1700]
### Description
Make caching optional and configurable.

### Motivation
To be able to benchmark the tangle w/o caching. #1628

### Requirements
Provide the following CLI options

- `--cache=boolean` : Enable or disable caching. If not, all other options are ignored. Default is `true`
- `--cache-max-size=int` : max number of elements in cache. Default is `1000`.
- `--cache-eviction-count=int`: The number of elements to evict at a time. Default is `10`.
- `--cache-concurrency-level=int`  : Concurrency level of cache map. Default is `5`.
- `--cache-milestones-max-size=int`  : Max number of elements in milestone cache. Default is `30`.
- `--cache-milestones-eviction-count=int` : The number of elements to evict from milestone cache at a time. Default is `30`.

### Open Questions
- Is this the best way to configure caching?
- Are there more options?
- Are these names cool?

### Am I planning to do it myself with a PR?
Yes

**Comment by GalRogozinski** [comment]
Do we need to provide CLI options?
I mean we will have different types of caches for certain data types...

Maybe we can make it grammatically configurable?

**Comment by acha-bill** [comment]
>Maybe we can make it grammatically configurable?

How so?
Any sample usage?

**Comment by GalRogozinski** [comment]
When you do the jmh benchmark you can inject the configs that you need

**Comment by acha-bill** [comment]
Revised configs are as follows

`--tx-cache-size`: The size of the tangle cache for transactions
`--tx-cache-release-count`: The number of transactions to release from the cache
`--milestone-cache-size`: The size of the tangle cache for milestones
`--milestone-cache-release-count`: The number of milestones to release from the cache
