### ISSUE TITLE
allow reversed order for attachToTangle

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/iri#1708]
### Bug description
If you send the attachToTangle API call with the txs of a bundle not reversed (index 0 first element) IRI will do the PoW in the wrong order, resulting in a invalid consistency for the bundle index 0:<https://thetangle.org/transaction/MDGEQZZMQGECFLCZLNKRCZHHWA9AJWQILEM9KXXJZOVGNEJFYZTZGDUMBXOJCEIBXKRNDGJHCFID99999> children tx is index 1, but it should be the trunk tx

### IRI version
1.8.4-RELEASE

### Steps To Reproduce
1. Send attachToTangle request with multiple txs and tail txs as first element

### Expected behaviour
IRI should reverse the order before doing the PoW

### Actual behaviour
IRI does the PoW in the wrong order

**Comment by GalRogozinski** [comment]
Fixed
