### ISSUE TITLE
Add more unit tests for caching

### ISSUE THREAD

**Issue by acha-bill** [iotaledger/iri#1734]
### Description

We need to cover more unit tests scenarios for caching.

### Motivation
We currently seeing some new bugs.
We could see these bugs earlier if our unit tests maybe covered a broader range of scenarios.

### Requirements
The following tests can be added

1. Check that cache size never grows past max configured size
2. A tx that is updated in the cache should be evicted to DB before being released from cache.
3. After prunning the DB with cache on, the DB shouldn't grow slowy i.e txs that have been deleted from DB shouldn't be written back from cache.
4. etc.

### Open Questions (optional)
What other tests can we add?

**Comment by GalRogozinski** [comment]
@acha-bill, if you are done with this move it to done please
