### ISSUE TITLE
Regression: Stitching test doesnt check for step response

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iri#1736]
# Bug description
In `reference_stitch_transaction` step in features/steps/transaction_steps, we have an options object with `trunk`  and `branch`  parameters. These are wrong and should be called `trunk_transaction`  and `branch_transaction`.
when calling `attach_to_tangle`, through `attach_store_and_broadcast`, an error is logged when calling `pool.fetch_results`, but we do not act on this error and the test succeeds.

Related: pool responses aren't set properly, causing multiple fails on our tests; like checkConsistency failing.
https://github.com/iotaledger/iri/pull/1666

### IRI version
1.8.4

### Steps To Reproduce
1. start machine4 regression tests
2. read log
3. see a warning

### Expected behaviour
Test succeeds without warning, or better the test should fail

### Actual behaviour
test succeeds and this is logged:
```
INFO:util.threading_logic.pool_logic:attach_to_tangle() got an unexpected keyword argument 'branch'
```

**Comment by GalRogozinski** [comment]
The INFO log should turn into an Error @DyrellC
