### ISSUE TITLE
Login Button wrong label

### ISSUE THREAD

**Issue by romansemko** [iotaledger/iri#176]
Version: 1.2.1
Steps to reproduce:

1. Open the app
2. Click on "Login", leaving the the seed field empty.
3. An error message is displayed "X Seed is required".
4. Click on the message to hide it and show the login button again.
5. FAIL. The login button is called "LOGGING" now.

Expected behaviour:
"Login" is displayed again.

I suppose this happens, because the label already changed to "Logging in" behind the scenes, but the width of the label is kept, so that only "LOGGING" is displayed, which might be very confusing for the user.

Greetings from Leipzig ^^

**Comment by paulhandy** [comment]
Please post this to iotaledger/wallet
