### ISSUE TITLE
Add node feature "WereAddressesSpentFrom" to "getNodeInfo"

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iri#1779]
### Description
We need a way to know if the node supports the api call "wereAddressesSpentFrom".

### Motivation
This way we can have nodes that don't care about the spent addresses. This is needed for small devices like raspberry pi, otherwise it's almost impossible to create a local snapshot (because disk IO is too much).

### Requirements
Return the feature "WereAddressesSpentFrom" in "getNodeInfo" "features"

### Am I planning to do it myself with a PR?
Yes.

**Comment by GalRogozinski** [comment]
Done
