### ISSUE TITLE
How do I get all the transaction information under a MilestoneIndex?

### ISSUE THREAD

**Issue by wshhz** [iotaledger/iri#1785]
I want to get transaction data through MilestoneIndex, but the provided API can only get related transactions through the address, are there other APIs that can get transaction information through MilestoneIndex?

**Comment by GalRogozinski** [comment]
This question should go to Discord/Stack Exchange

But the milestone index is on the `Obsolete_Tag` so you can search via tags. Just convert the index to trytes first.
