### ISSUE TITLE
Using my seed gives "Connection refused", others are fine

### ISSUE THREAD

**Issue by Polve** [iotaledger/iri#179]
Today I started using the light wallet, version 2.3.0 using an external node I setup.

I correctly generated a seed, a receiving address, and I also received my first transaction with a few Gi.

But when I tried to login again I had a "Connection Refused" error after a few seconds, and that happens non only using my node, but also with all the others I tried (for example the Bitfinex one).

When using another seed everything is fine (both on my node and others).

I'm now locket out my wallet without understanding what I can do to solve the problem: any hint?

**Comment by janimator0** [comment]
Are you still having the issue?
