### ISSUE TITLE
Add heartbeat to message protocol

### ISSUE THREAD

**Issue by kwek20** [iotaledger/iri#1792]
### Description
Relays the neighbor last and first solid milestone indexes. The first one depends on what the pruning settings are. This is used to help a syncing node know what data their neighbor has.

### Motivation
Limiting network usage by requesting transactions from nodes which actually have those (as seen by milestones)

### Requirements
1. Add a new message type named HEARTBEAT in ProtocolMessage
2. Update MessageReader to read this message
3. Update NeighborImpl to handle the message

According to the following details: https://github.com/iotaledger/protocol-rfcs/blob/d16a3815271cdb4b53ff3c234ea706bf764e1847/text/0001-protocol-messages/0001-protocol-messages.md#heartbeat

**Comment by GalRogozinski** [comment]
Let's Broadcast it every minute
