### ISSUE TITLE
How do I get the status of a transaction?

### ISSUE THREAD

**Issue by wshhz** [iotaledger/iri#1801]
I used getTrytes to get the data of a transaction. How can I tell if the status of the transaction is pending or confirmed?

**Comment by wshhz** [comment]
oh,i know

**Comment by kwek20** [comment]
For those wondering; You can use `getInclusionStates` API call to query confirmation. 
Information: [Here](https://docs.iota.org/docs/node-software/0.1/iri/references/api-reference#getinclusionstates)
