### ISSUE TITLE
getTransactionsToApprove | IRI 1.1.2

### ISSUE THREAD

**Issue by mettenian** [iotaledger/iri#19]
{"command":"getTransactionsToApprove","depth":3} 
from time to time the result is just {"duration": xxxx}, no error message or branch and trunk tx. Never saw this with 1.1.1.1.

**Comment by davassi** [comment]
Checking it....

**Comment by davassi** [comment]
It happens when the subtangle is not solid. Or the db is not sync yet.

**Comment by davassi** [comment]
@mettenian fixed in dev branch.
