### ISSUE TITLE
IRI light wallet?

### ISSUE THREAD

**Issue by eukaryote31** [iotaledger/iri#190]
Is it possible to use iri as a light node?

**Comment by alfredch** [comment]
How do you define a light node?

**Comment by eukaryote31** [comment]
Doing PoW on the client but not syncing the Tangle; preferably with multiple light wallet nodes, to prevent any one of them providing misleading information.

**Comment by alfredch** [comment]
Why not use the existing light wallet for that? Why do you want to do PoW with IRI? Although you could use IXI to do PoW with an offline IRI, you would still not have most of the other required functionality of a wallet, like creating bundles.
