### ISSUE TITLE
No. of Tips Constantly Growing

### ISSUE THREAD

**Issue by bluedigits** [iotaledger/iri#214]
Hi @alon-e, hi @paulhandy,

With the new tip selection it seems the no. of tips is growing continuously. Maybe there's a way to cap them.

![grafik](https://user-images.githubusercontent.com/3186610/27930768-1fc5e592-6298-11e7-93aa-12903296893f.png)

The no. increases by ~30k per day.

Thanks!

**Comment by alfredch** [comment]
You should add these 3 lines to your INI file:
P_REMOVE_REQUEST = 0.20
P_REPLY_RANDOM_TIP = 1.0
P_PROPAGATE_REQUEST = 0.05
If you still have growing transactionsToRequest, you can set P_Propaget_REQUEST = 0.01
That are metrics we have from our 18 nodes.

**Comment by bluedigits** [comment]
Thank you, Alfred. I'll give it a shot.
