### ISSUE TITLE
Should reject broadcast of double-spend?

### ISSUE THREAD

**Issue by lvella** [iotaledger/iri#215]
I've submitted to a public node a chain of transactions ultimately verifying a double spend (my last transaction was `ODTDCPQQJNEIUYJMIITMJXTSLUTZITM9OKYKFJSUNJBADAOGDIQEPNTRNOFHWOWMTQOUQIIXPJSR99999`. Follow trough trunk until reach `JFRDHCLSCWEL9VPJYMLQHCLUEXLMXVXYQBMOX9CHDSKZLRWSJDP9JBPWWOWNPNADGUGOEUYXIKZK99999`, which is the double spend). Shouldn't the node have denied propagation of any of these transactions? This would not be a problem if it was a private node, but since it is public, there should at least be an option to be more strict when accepting transactions broadcast from JSON api, because broadcasting anything could place the node in bad position with the others.

**Comment by Come-from-Beyond** [comment]
IOTA protocol doesn't require that to work reliably. Also, what is a doublespending now can become a legitimate transfer later.

**Comment by jmarcus13** [comment]
@Come-from-Beyond 
Please if you will expand on how "doublespending now can become a legitimate transfer later." Not following that line of thought.
