### ISSUE TITLE
mainnet accepting `minWeightMagnitude` of 15

### ISSUE THREAD

**Issue by lvella** [iotaledger/iri#216]
According to everywhere I read, including IRI's own 'README.md', minimum acceptable `minWeightMagnitude` for testnet is 15, and `minWeightMagnitude` for mainnet should be 18. But at least Android wallet and Bitfinex are sending their transaction to mainnet with `minWeightMagnitude` of 15 instead of 18. Either IRI should be fixed to only accept `minWeightMagnitude` of 18 on mainnet, or `README.md` and other documentation should be updated to clarify that, for the time being, `minWeightMagnitude` is 15 no matter the setting `--testnet` is given or not. Specially [`attachToTangle`](https://iota.readme.io/docs/attachtotangle) API documentation, which says the minimum is 18.

**Comment by paulhandy** [comment]
It's supposed to be 15 - fixed with #217
