### ISSUE TITLE
CORS not working

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#22]
Fetch API cannot load http://*********.info:14265/. The 'Access-Control-Allow-Origin' header contains the invalid value 'node.iotawallet.info'. Origin 'null' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

java -jar /opt/iota/IRI.jar --port 14265 --receiver-port 14265 --neighbors '*******'  --debug --enabled-cors '******.info'

**Comment by pinpong** [comment]
Its working with Wildcard

**Comment by tedjames** [comment]
Hey @pinpong, how did you resolve this issue?
