### ISSUE TITLE
IRI MessageQ - uppercase topic

### ISSUE THREAD

**Issue by frohal** [iotaledger/iri#220]
"All topic must be lowercase (to not clash with "Address" containing the topic title - like TXCR9... & TX)"
Topic called 'RSTAT' is not lowercase.

**Comment by paulhandy** [comment]
SHAME!
Sorry -
shame.

**Comment by frohal** [comment]
How do I specify the topic for an address ?

**Comment by paulhandy** [comment]
just use the address hash in question
