### ISSUE TITLE
IRI MessageQ - subscribe to addresses..

### ISSUE THREAD

**Issue by frohal** [iotaledger/iri#221]
Probably this section was ment to make it  possible to subscribe to addresses, but the only 'address' it's possible to subscribe to, is '9999999'        

             messageQ.publish("%s %s %d sn", transactionViewModel2.getAddressHash(), transactionViewModel2.getHash(), index);
                    messageQ.publish("sn %d %s %s %s %s %s", index, transactionViewModel2.getHash(),
                            transactionViewModel2.getAddressHash(),
                            transactionViewModel2.getTrunkTransactionHash(),
                            transactionViewModel2.getBranchTransactionHash(),
                            transactionViewModel2.getBundleHash());

When subscribing to topic '9' I get those messages :
999999999999999999999999999999999999999999999999999999999999999999999999999999999 FQB9LYBEOBQVJZXSYIALWOUHPODRYQMTITROYYQHQGARZSC9PVLLUVJ9NMYMHHLWTSMHTEMPOGBM99999 105335 sn
999999999999999999999999999999999999999999999999999999999999999999999999999999999 JZIVEIGONOGOYKYXNAWFIVK9PZEMABSEBDYBUDJLPHNSJBKBSUZOKNHUUHXHPDBUDDSIKMSCAXET99999 105335 sn

**Comment by paulhandy** [comment]
if you would like to subscribe to an address, I would suggest subscribing to the _full_ 81-character string of it, and not to the character '9'

**Comment by frohal** [comment]
There is amost nothing coming in that field except 81 9's
I rarely get anything else, and why does the message end with 'sn' ?

When I subscribe to 'sn' I can see what data I could have received directly from  transactionViewModel2.getAddressHash() , and most of the lines is 81 9's 
And anyway, it's not the IOTA-address that is published, which it should have been in order to make it possible to listen for address-events.

**Comment by alon-e** [comment]
`KPWC...` is the address issuing milestones & `999..` is the default address for non-value transfers.
by "actual" transactions, you are referring to value transfers, there are more non-value transfers that ppl use to record data, or transfer messages.

for future readers,
the best way to test this imo, is to make a value transfer & subscribe to your address.
once the transaction in confirmed, you will get a notification.
