### ISSUE TITLE
Duplicate neighbour when changing IP.

### ISSUE THREAD

**Issue by frohal** [iotaledger/iri#241]
Start-config:
1:  one neighbor is added via dns-name, and has only a IPV6-address in dns. This is resvoled and works fine.
2: remove the neighbor from list (via API).
3: Change DNS to only have the IPV4 address for the same name.
4. Add the neighbor again using the DNS-name. neighbor is added succesfully.
5. When DNS-updater runs, it discovers that the IP-address for the node has changed, and updates internally. Seems to work fine, but it actually adds a second neighbor based only on IP.

the result is two instances of the same neighbor in nieghbor-list, one with the name, and one with the ip-address.

They do not have the same 'counters', so it's apparent thateIRI looks at them as separate neighbors.

**Comment by scott79** [comment]
Similar reported issue to: https://github.com/iotaledger/iri/issues/291

Patch was submitted, pending review.

**Comment by alon-e** [comment]
duplicate
