### ISSUE TITLE
checkSolidity method of getTransactionsToApprove API command cost long time response

### ISSUE THREAD

**Issue by yillkid** [iotaledger/iri#242]
The API command getTransactionsToApprove request cost a long time response especially in the checkSolidity method. For example, do the API request on my node as below:

${"trunkTransaction":"9UIHYJUEZVIUDTUQRE9CBHLIQQEWJDFRWCLIJNZPTBZIYKLTUBCMQFVM9VF9UFFFRFJNVEBMZJFY99999","branchTransaction":"VKBELLAOJKGCIXWUMOHPUTDHJDXSSWRWAOGZSHLGLWDRAFWWRAFQYEDBOFGWVNXOEOQSGQODWZTN99999","duration":633944}

The API cost 633944 milliseconds for response but checkSolidity take up 633929 milliseconds after measuring into the method ( checkSolidity/getTransactionsToApprove : 633929/633944).

Any idea to Improve the performance ?

Hardware specification:
description: Computer
width: 64 bits
capabilities: smp vsyscall32
*-core
description: Motherboard
physical id: 0
*-memory
description: System memory
physical id: 0
size: 7983MiB
*-cpu:0
product: QEMU Virtual CPU version 2.5+
vendor: Intel Corp.
physical id: 1
bus info: cpu@0
width: 64 bits
capabilities: fpu fpu_exception wp de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx x86-64 rep_good nopl xtopology pni ssse3 cx16 sse4_1 sse4_2 x2apic hypervisor lahf_lm xsaveopt xsavec
*-cpu:1
product: QEMU Virtual CPU version 2.5+
vendor: Intel Corp.
physical id: 2
bus info: cpu@1
width: 64 bits
capabilities: fpu fpu_exception wp de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx x86-64 rep_good nopl xtopology pni ssse3 cx16 sse4_1 sse4_2 x2apic hypervisor lahf_lm xsaveopt xsavec
*-cpu:2
product: QEMU Virtual CPU version 2.5+
vendor: Intel Corp.
physical id: 3
bus info: cpu@2
width: 64 bits
capabilities: fpu fpu_exception wp de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx x86-64 rep_good nopl xtopology pni ssse3 cx16 sse4_1 sse4_2 x2apic hypervisor lahf_lm xsaveopt xsavec
*-cpu:3
product: QEMU Virtual CPU version 2.5+
vendor: Intel Corp.
physical id: 4
bus info: cpu@3
width: 64 bits
capabilities: fpu fpu_exception wp de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx x86-64 rep_good nopl xtopology pni ssse3 cx16 sse4_1 sse4_2 x2apic hypervisor lahf_lm xsaveopt xsavec

**Comment by alon-e** [comment]
What depth are you using?
Could your node still be syncing?

This ofc isn't the normal case, 
On my node it takes about  ~100ms up to depth 100.

Please provide more details like the API call & the node log surrounding the call. 
Thanks.

**Comment by yillkid** [comment]
Using depth 3 as below:

curl http://localhost:14265 \
  -X POST \
  -H 'Content-Type: application/json' \
  -d '{"command": "getTransactionsToApprove", "depth": 3}'

The node still syncing but not fully-syncup : 

{
    "appName": "IRI",
    "appVersion": "1.2.4",
    "duration": 1,
    "jreAvailableProcessors": 4,
    "jreFreeMemory": 66528680,
    "jreMaxMemory": 1020067840,
    "jreTotalMemory": 779091968,
    "jreVersion": "1.8.0_131",
    "latestMilestone": "TFLHJCXIAKEUWMXOVDVHLLBFKRHUKUDQPUZXZFKEVNM9VIQALWUNYCNWFWSLYWYCOBONZQOAJGTC99999",
    "latestMilestoneIndex": 133646,
    "latestSolidSubtangleMilestone": "ACFDEHNKSVDHNJTGCJOAKHCOHIYLVKXJAWXEIRY9WEMLGMKPRCQGLZHIVSYUKMTEAQCGJKXXDVCU99999",
    "latestSolidSubtangleMilestoneIndex": 132534,
    "neighbors": 9,
    "packetsQueueSize": 0,
    "time": 1501257375806,
    "tips": 31476,
    "transactionsToRequest": 1
}

**Comment by yillkid** [comment]
request again (with IRI debug log):

{"trunkTransaction":"IURFDLNWEANCIHD9MJXTKXJTYARUMJUXGCJKIRLPZTXCMYWXCLOKVGISA9ILKWYUOGKQIQZWSKPN99999","branchTransaction":"9NQSBASHBWLUQDMXGBFNIKGASSASTXHBGLNKLLHXCSQGVTMFGOIPADDTCIRJHHVQFYYSSEGHOU9R99999","duration":1852135}ubuntu@devorg:~/tools/script_restful_api$

OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
07/29 01:23:28.391 [main] DEBUG com.iota.iri.conf.Configuration - Setting CONFIG with iota-deploy/configs/node_deviceproof_org.config
07/29 01:23:28.419 [main] DEBUG com.iota.iri.conf.Configuration - Setting PORT with 14265
07/29 01:23:28.419 [main] DEBUG com.iota.iri.conf.Configuration - Setting NEIGHBORS with 
07/29 01:23:28.419 [main] DEBUG com.iota.iri.IRI - The following api calls are not allowed : removeNeighbors, addNeighbors, attachToTangle, findTransactions, getBalances, getTips, getTransactionsToApprove, getInclusionStates 
07/29 01:23:28.419 [main] DEBUG com.iota.iri.conf.Configuration - Setting REMOTE_LIMIT_API with removeNeighbors, addNeighbors, attachToTangle, findTransactions, getBalances, getTips, getTransactionsToApprove, getInclusionStates
07/29 01:23:28.420 [main] DEBUG com.iota.iri.conf.Configuration - Setting API_HOST with 0.0.0.0
07/29 01:23:28.420 [main] DEBUG com.iota.iri.conf.Configuration - Setting SKIP_LOAD_TIPS_ON_INIT with true
07/29 01:23:28.420 [main] DEBUG com.iota.iri.conf.Configuration - Setting SKIP_NULL_TX_ON_GET_INCLUSION_STATES with true
07/29 01:23:29.540 [main] DEBUG com.iota.iri.service.API - Binding JSON-REST API Undertown server on 0.0.0.0:14265
07/29 01:23:34.812 [XNIO-1 task-1] DEBUG com.iota.iri.service.API - # 1 -> Requesting command 'getTrytes'
07/29 01:24:00.330 [XNIO-1 task-4] DEBUG com.iota.iri.service.API - # 2 -> Requesting command 'getNodeInfo'
07/29 01:24:31.025 [XNIO-1 task-6] DEBUG com.iota.iri.service.API - # 3 -> Requesting command 'getNodeInfo'
07/29 01:25:02.581 [XNIO-1 task-8] DEBUG com.iota.iri.service.API - # 4 -> Requesting command 'getNodeInfo'
07/29 01:25:29.773 [XNIO-1 task-9] DEBUG com.iota.iri.service.API - # 5 -> Requesting command 'getTrytes'
07/29 01:26:15.267 [XNIO-1 task-10] DEBUG com.iota.iri.service.API - # 6 -> Requesting command 'getTransactionsToApprove'
07/29 01:29:39.304 [XNIO-1 task-13] DEBUG com.iota.iri.service.API - # 7 -> Requesting command 'getTrytes'
07/29 01:31:09.309 [XNIO-1 task-15] DEBUG com.iota.iri.service.API - # 8 -> Requesting command 'getNodeInfo'
07/29 01:32:02.864 [XNIO-1 task-17] DEBUG com.iota.iri.service.API - # 9 -> Requesting command 'getNodeInfo'
07/29 01:32:56.144 [XNIO-1 task-18] DEBUG com.iota.iri.service.API - # 10 -> Requesting command 'getNodeInfo'
07/29 01:33:39.810 [XNIO-1 task-21] DEBUG com.iota.iri.service.API - # 11 -> Requesting command 'getTrytes'
07/29 01:34:10.517 [XNIO-1 task-23] DEBUG com.iota.iri.service.API - # 12 -> Requesting command 'getNodeInfo'
07/29 01:35:38.436 [XNIO-1 task-26] DEBUG com.iota.iri.service.API - # 13 -> Requesting command 'getNodeInfo'
07/29 01:35:42.769 [XNIO-1 task-27] DEBUG com.iota.iri.service.API - # 14 -> Requesting command 'getNodeInfo'
07/29 01:36:07.443 [XNIO-1 task-29] DEBUG com.iota.iri.service.API - # 15 -> Requesting command 'getNodeInfo'
07/29 01:36:17.268 [XNIO-1 task-31] DEBUG com.iota.iri.service.API - # 16 -> Requesting command 'getNodeInfo'
07/29 01:36:17.291 [XNIO-1 task-32] DEBUG com.iota.iri.service.API - # 17 -> Requesting command 'getTrytes'
07/29 01:36:17.376 [XNIO-1 task-1] DEBUG com.iota.iri.service.API - # 18 -> Requesting command 'getNodeInfo'
07/29 01:36:31.947 [XNIO-1 task-3] DEBUG com.iota.iri.service.API - # 19 -> Requesting command 'getTrytes'
07/29 01:36:51.831 [XNIO-1 task-4] DEBUG com.iota.iri.service.API - # 20 -> Requesting command 'getNodeInfo'
07/29 01:36:57.424 [XNIO-1 task-5] DEBUG com.iota.iri.service.API - # 21 -> Requesting command 'getNodeInfo'
07/29 01:38:04.499 [XNIO-1 task-6] DEBUG com.iota.iri.service.API - # 22 -> Requesting command 'getNodeInfo'
07/29 01:38:15.174 [XNIO-1 task-8] DEBUG com.iota.iri.service.API - # 23 -> Requesting command 'getNodeInfo'
07/29 01:38:51.440 [XNIO-1 task-11] DEBUG com.iota.iri.service.API - # 24 -> Requesting command 'getTrytes'
07/29 01:45:17.317 [XNIO-1 task-12] DEBUG com.iota.iri.service.API - # 25 -> Requesting command 'getNodeInfo'
07/29 01:45:49.932 [XNIO-1 task-15] DEBUG com.iota.iri.service.API - # 26 -> Requesting command 'getNodeInfo'
07/29 01:46:33.484 [XNIO-1 task-16] DEBUG com.iota.iri.service.API - # 27 -> Requesting command 'getNodeInfo'
07/29 01:46:40.366 [XNIO-1 task-17] DEBUG com.iota.iri.service.API - # 28 -> Requesting command 'getNodeInfo'
07/29 01:47:36.085 [XNIO-1 task-19] DEBUG com.iota.iri.service.API - # 29 -> Requesting command 'getTrytes'
07/29 01:47:59.424 [XNIO-1 task-22] DEBUG com.iota.iri.service.API - # 30 -> Requesting command 'getNodeInfo'
07/29 01:48:00.889 [XNIO-1 task-23] DEBUG com.iota.iri.service.API - # 31 -> Requesting command 'getTrytes'
07/29 01:48:43.025 [XNIO-1 task-24] DEBUG com.iota.iri.service.API - # 32 -> Requesting command 'getNodeInfo'
07/29 01:49:55.529 [XNIO-1 task-26] DEBUG com.iota.iri.service.API - # 33 -> Requesting command 'getNodeInfo'
07/29 01:50:19.375 [XNIO-1 task-28] DEBUG com.iota.iri.service.API - # 34 -> Requesting command 'getNodeInfo'
07/29 01:52:24.881 [XNIO-1 task-30] DEBUG com.iota.iri.service.API - # 35 -> Requesting command 'getNodeInfo'
07/29 01:52:57.947 [XNIO-1 task-31] DEBUG com.iota.iri.service.API - # 36 -> Requesting command 'getNodeInfo'
07/29 01:53:20.514 [XNIO-1 task-2] DEBUG com.iota.iri.service.API - # 37 -> Requesting command 'getNodeInfo'
07/29 01:53:21.115 [XNIO-1 task-5] DEBUG com.iota.iri.service.API - # 38 -> Requesting command 'getNodeInfo'
07/29 01:55:00.261 [XNIO-1 task-7] DEBUG com.iota.iri.service.API - # 39 -> Requesting command 'getNodeInfo'
07/29 01:55:00.408 [XNIO-1 task-8] DEBUG com.iota.iri.service.API - # 40 -> Requesting command 'getNodeInfo'
07/29 01:55:16.596 [XNIO-1 task-12] DEBUG com.iota.iri.service.API - # 41 -> Requesting command 'getNodeInfo'
07/29 01:56:21.121 [XNIO-1 task-16] DEBUG com.iota.iri.service.API - # 42 -> Requesting command 'getNodeInfo'
07/29 01:57:18.493 [XNIO-1 task-18] DEBUG com.iota.iri.service.API - # 43 -> Requesting command 'getNodeInfo'
07/29 01:57:22.872 [XNIO-1 task-22] DEBUG com.iota.iri.service.API - # 44 -> Requesting command 'getNodeInfo'
07/29 01:57:46.287 [XNIO-1 task-25] DEBUG com.iota.iri.service.API - # 45 -> Requesting command 'getNodeInfo'
07/29 01:59:42.551 [XNIO-1 task-28] DEBUG com.iota.iri.service.API - # 46 -> Requesting command 'getNodeInfo'
07/29 01:59:52.861 [XNIO-1 task-30] DEBUG com.iota.iri.service.API - # 47 -> Requesting command 'getTrytes'
07/29 02:00:08.909 [XNIO-1 task-31] DEBUG com.iota.iri.service.API - # 48 -> Requesting command 'getNodeInfo'
07/29 02:00:11.529 [XNIO-1 task-2] DEBUG com.iota.iri.service.API - # 49 -> Requesting command 'getNodeInfo'
07/29 02:01:44.115 [XNIO-1 task-7] DEBUG com.iota.iri.service.API - # 50 -> Requesting command 'getNodeInfo'
07/29 02:03:33.851 [XNIO-1 task-9] DEBUG com.iota.iri.service.API - # 51 -> Requesting command 'getNodeInfo'
07/29 02:03:43.976 [XNIO-1 task-12] DEBUG com.iota.iri.service.API - # 52 -> Requesting command 'getNodeInfo'
07/29 02:06:01.688 [XNIO-1 task-14] DEBUG com.iota.iri.service.API - # 53 -> Requesting command 'getNodeInfo'
07/29 02:06:56.210 [XNIO-1 task-15] DEBUG com.iota.iri.service.API - # 54 -> Requesting command 'getTrytes'
07/29 02:07:07.429 [XNIO-1 task-16] DEBUG com.iota.iri.service.API - # 55 -> Requesting command 'getNodeInfo'

**Comment by yillkid** [comment]
I am fully-synced now, and I try to get transaction to approve again, I fin I get very good performance as below:  (But I can find any association with source code, any idea ? )

curl http://localhost:14265 \
  -X POST \
  -H 'Content-Type: application/json' \
  -d '{"command": "getTransactionsToApprove", "depth": 3}'

{"trunkTransaction":"AGSHKBHYP9TREOLDKU9JJDLOCCZASODRCKMASIMJRLBCFOBRQWCWSBBEQEJQKPNCINGHVPUKAEMU99999","branchTransaction":"DDSJKECVYNCYHKNQXAMKZTB9RN9NOXXBGSGEYWLAF9MJIWFDHXOCTMCYZFRYPRAJDSKLHTKVWPFD99999","duration":382}
