### ISSUE TITLE
Transaction resolves to incorrect ledger balance: -550000000

### ISSUE THREAD

**Issue by dhughesbc** [iotaledger/iri#243]
Not sure if this is a bug or just some kind of one-time glitch, but my Ubuntu 16.04 VPS node running 1.2.4 spontaneously died after running fine for about 32 hours. The only recent changes I have made are:

- switched from HDD to SSD
- switched from openjdk8 to Oracle jdk 8
- added '--revalidate' to the start command

I redirect output to a log and yesterday these unusual lines started appearing:
```
07/25 19:40:04.279 [Latest Milestone Tracker] INFO  com.iota.iri.Milestone - Latest milestone has changed from #129985 to #129986
07/25 19:40:14.592 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 10 , toReply = 0 / totalTransactions = 3480629
07/25 19:40:17.435 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Transaction resolves to incorrect ledger balance: -550000000
07/25 19:40:17.481 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Transaction resolves to incorrect ledger balance: -550000000
07/25 19:40:17.514 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Transaction resolves to incorrect ledger balance: -550000000
```
There are about 200K lines like this logged over ~28 hours. Then it died:
```
07/26 23:17:25.888 [Solid Milestone Tracker] INFO  com.iota.iri.Snapshot - Transaction resolves to incorrect ledger balance: -550000000
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000079a157000, 636129280, 0) failed; error='Cannot allocate memory' (errno=12)
#


# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 636129280 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/iota/deploy/hs_err_pid2921.log
```

**Comment by dhughesbc** [comment]
[hs_err_pid2921.log.zip](https://github.com/iotaledger/iri/files/1184280/hs_err_pid2921.log.zip)

**Comment by b166er** [comment]
any news? have same issue!

**Comment by kushkush2** [comment]
I had the same issue yesterday. I believe you were downloading the Testnet. Make sure you're using the MainNet at this url: https://github.com/iotaledger/iri/releases

Mainnet v1.4.1.2 is the current version. Hope this helps.

**Comment by b166er** [comment]
> I had the same issue yesterday. I believe you were downloading the Testnet. Make sure you're using the MainNet at this url: https://github.com/iotaledger/iri/releases
> 
> Mainnet v1.4.1.2 is the current version. Hope this helps.


YES! that is the solution! thanks for the hint, it's resolving my issue! 
it would be better, if the Mainnet-iri stay at top of releases-page in github.
