### ISSUE TITLE
Fatal Error causing IRI to crash (SIGSEGV (0xb) )

### ISSUE THREAD

**Issue by bahamapascal** [iotaledger/iri#245]
Following error already accoured several times on some of my servers causing the IRI to crash.
IRI log:

`07/28 06:33:50.211 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 49879 , toReply = 0 / totalTransactions = 3961388

A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007f42ce6adb42, pid=10737, tid=0x00007f4279ffc700

JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
Problematic frame:
V  [libjvm.so+0x6d1b42]  jni_SetByteArrayRegion+0xc2

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

An error report file with more information is saved as:
/opt/iota/hs_err_pid10737.log`

If needed I can supply the "hs_err_pid10737.log" file

**Comment by alon-e** [comment]
yes @bahamapascal , please supply the hs_err.log file.
thanks!

and can you format this issue so it doesn't all appear as Headers? :)

**Comment by bahamapascal** [comment]
[hs_err_pid10737.txt](https://github.com/iotaledger/iri/files/1184970/hs_err_pid10737.txt)

Already fixed the formatting...had intended to format the error log as code but somehow didn't quite work as I had hoped :D

**Comment by patrickwieth** [comment]
Roughly one week ago:

> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x00007fb62a84acc2, pid=3309, tid=0x00007fb5d67fc700
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
> # Problematic frame:
> # V  [libjvm.so+0x6d3cc2]  jni_SetByteArrayRegion+0xc2
> #
> # Core dump written. Default location: /home/wieth/IOTA/core or core.3309
> #
> # An error report file with more information is saved as:
> # /home/wieth/IOTA/hs_err_pid3309.log
> #
> # If you would like to submit a bug report, please visit:
> #   http://bugreport.java.com/bugreport/crash.jsp
> #
> /usr/bin/iri: line 2:  3309 Aborted                 (core dumped) java -jar /usr/lib/iri/iri.jar --port 14265

[hs_err_pid3309.txt](https://github.com/iotaledger/iri/files/1314268/hs_err_pid3309.txt)

And the second occasion a few days ago:

> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x00007f4423c10cc2, pid=7467, tid=0x00007f43cb8f8700
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0_144-b01) (build 1.8.0_144-b01)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode linux-amd64 compressed oops)
> # Problematic frame:
> # V  [libjvm.so+0x6d3cc2]  jni_SetByteArrayRegion+0xc2
> #
> # Core dump written. Default location: /home/wieth/IOTA/core or core.7467
> #
> # An error report file with more information is saved as:
> # /home/wieth/IOTA/hs_err_pid7467.log
> #
> # If you would like to submit a bug report, please visit:
> #   http://bugreport.java.com/bugreport/crash.jsp
> #
> /usr/bin/iri: line 2:  7467 Aborted                 (core dumped) java -jar /usr/lib/iri/iri.jar --port 14265

[hs_err_pid7467.txt](https://github.com/iotaledger/iri/files/1314272/hs_err_pid7467.txt)
