### ISSUE TITLE
Option to enable Monte Carlo Walk?

### ISSUE THREAD

**Issue by eukaryote31** [iotaledger/iri#249]
There should be an option for monte carlo walk (i.e no more using milestones to determine inclusion) in the config. That should reduce dependency on the coordinator to a quick flag/config change, rather than a rewrite.

**Comment by paulhandy** [comment]
Are you perhaps mixing terms here a bit? There already is random walk, and it is used for tip selection. By default, it starts from the milestone, though you can give it a chosen reference transaction to start from.
Confirmation calculations are done on client-side libraries, and could indeed not use milestones as a reference.

**Comment by eukaryote31** [comment]
Oh, okay. I get it now. Thanks!
