### ISSUE TITLE
Latest solid subtangle milestone does not update properly while syncing

### ISSUE THREAD

**Issue by goligo** [iotaledger/iri#250]
When restarting the node while it is still syncing (which is a common scenario, as you usually update the configuration file and restart for adding neighbors), the latestSolidSubtangleMilestoneIndex jumps to something close to the current latestMilestoneIndex. This gives the impression that the sync process is almost complete, but this is not the case, instead it keeps staying there for several hours (no "Solid Milestone Tracker" messages in the log), until the sync really is at this point. 

This means after restarting the node, you are no longer able to track the sync progress and it feels like the node is malfunctioning, as the latestSolidSubtangleMilestoneIndex is never updated.

**Comment by dashengSun** [comment]
I got the same issue, re-delete the db and mainlog, not working.

**Comment by jjmiranda** [comment]
The same issue with this data:
"latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
 "latestSolidSubtangleMilestoneIndex": 151000,

**Comment by paaland** [comment]
Same here.  After a restart this is the node info for several hours:

`{
	"appName": "IRI",
	"appVersion": "1.3.2",
	"jreAvailableProcessors": 4,
	"jreFreeMemory": 307762056,
	"jreVersion": "1.8.0_141",
	"jreMaxMemory": 7635730432,
	"jreTotalMemory": 1484259328,
	"latestMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
	"latestMilestoneIndex": 151000,
	"latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
	"latestSolidSubtangleMilestoneIndex": 151000,
	"neighbors": 9,
	"packetsQueueSize": 0,
	"time": 1504773223450,
	"tips": 226,
	"transactionsToRequest": 266,
	"duration": 0
}`

**Comment by janfiedler** [comment]
With "S B" on iotatangle.slack.com we figure out problem is when you use UDP port, when you switch to TCP communication with neighborhoods all is running and syncing.

**Comment by janfiedler** [comment]
Update:
With TCP start working syncing. But now same problem. I am 4 - 40 Milestones from actual and can´t catch last. And still get error: The subtangle is not solid  when i want use light wallet to log in.

**Comment by paaland** [comment]
Same here. Using tcp neighbors only it starts to sync, but seems to stop when getting really close to being i full sync.

**Comment by zoran** [comment]
My node is finally synchronized (Ubuntu 16.04 @ aws). I had to delete my db (and log) folder and change from openjdk 8/9 to oracle jdk 8. after a few hours the node was synchronized without any intervention (restart).

**Comment by daniaoren** [comment]
Is there any update on this issue? How can we fix this?

**Comment by PatrickHuetter** [comment]
That's bad because so it's not possible to restart the node because after each restart you've to sync everything again.

**Comment by GhostTyper** [comment]
I didn't observe this and i'm restarting my node every night. Are you guys mainly using docker?

**Comment by goligo** [comment]
For clarification, what I experienced is just a wrong reporting of the latestSolidSubtangleMilestoneIndex, you can still safely restart the node and it will continue syncing and eventually catch up.

**Comment by alon-e** [comment]
fixed with #486
