### ISSUE TITLE
Missing protocol version property in IRI JSON messages

### ISSUE THREAD

**Issue by goligo** [iotaledger/iri#266]
When nodes are communicating using the JSON messages, there currently is no possibility to detect version differences, so if something is changed (like the current crypto switch) the server has no possibility to detect that the client is outdated.

My proposal is to include a protocol version into every JSON message, like
```
{
    "version": "1.2.4",
    "command": "getNeighbors"
}
---->
{
    "version": "1.3.0",
    "duration": 37,
    "neighbors": [
        {
...
```

This gives the server, as well as the client, the possibility to fail gracefully, in case they are talking to a peer which they don't support (yet or anymore). 
This would have avoided issues during the current transition, where people were attaching lots of addresses to the tangle with the old wallet in the hope to see their balance again. 
This would also help to fade out old IRI versions in full nodes in case people are not upgrading, as a newer versions could just ignore and drop all communication from outdated nodes.

**Comment by paulhandy** [comment]
Nodes do not communicate with peers using JSON.

**Comment by goligo** [comment]
Whatever protocol is used in node to node communication, it should be able to include a version in there as well. From my perspective for the JSON API it would be more important, as it is used for the light wallet and other software like tangle explorers.

I am not even sure whether it should be the IRI version used there, other whether it would make sense to have a protocol version independent of the IRI version.

**Comment by paulhandy** [comment]
This is not a good idea - there's not even a way of enforcing correctness of version messages, so it will only pollute transaction data. We will not be supporting this in the current or any future version of IOTA.
One may already check the node version through the http api.

**Comment by goligo** [comment]
Yes, the client can check the node version using the getNodeInfo command, but the server cannot get the client version. But this is just a proposal, maybe you can think about it, instead of ruling it out categorical for "any future versions of IOTA".
