### ISSUE TITLE
Master branch does not contain the latest release

### ISSUE THREAD

**Issue by goligo** [iotaledger/iri#267]
I know this is not a mandatory requirement, but every project can deal with releases as they like to and there are different philosphies on how to do it right. However it makes sense to use common practice, as it makes it easier for people coming new to the project.

From my perspective it would be helpful, if you would update the master branch to the latest released version, for every release, also patches. This way people who want to build from the source can just checkout master and build, and don't need to research first what the current version might be.

In addition to that when looking into your GitHub you immediately see the latest updates, I remember several people in Slack asking why there is no development on IOTA, as the 1.2.0 was several month old and no updates were pushed to the master branch.

**Comment by paulhandy** [comment]
rebased
