### ISSUE TITLE
Missing MD5/SHA256 checksums on download page

### ISSUE THREAD

**Issue by goligo** [iotaledger/iri#268]
As IRI is usually run on a server system together with other services, it would be great if you could check the integrity of your download first with a MD5 or SHA256 hash. This is common practice for other cyrptos as well, e.g. https://github.com/ethereum/mist/releases .

**Comment by alon-e** [comment]
(signed) sha256sums were added to the latest release: https://github.com/iotaledger/iri/releases/tag/v1.5.0
this will be integrated to the Travis deployment for the next release.
Thanks!

**Comment by jakubcech** [comment]
We still need to make sure we are signing all the binaries, the checksum files with detached signatures.
