### ISSUE TITLE
Intermittently losing track of latest solid subtangle milestone

### ISSUE THREAD

**Issue by goligo** [iotaledger/iri#269]
After IRI is running stable for some days, occasionally without any error message or other indicator in the logfile, the Solid Milestone Tracker stops working and the latestSolidSubtangleMilestone doesn't increase anymore. 

If this happens I just need to restart IRI and shortly after latestSolidSubtangleMilestone is on track again.

**Comment by rajivshah3** [comment]
I have the same issue, running IRI with `--revalidate` fixes it for me

**Comment by alon-e** [comment]
fixed with #486
