### ISSUE TITLE
Remote flag is not parsed when passed by config file

### ISSUE THREAD

**Issue by culnamo** [iotaledger/iri#274]
Dear Team,

I just noticed that the remote flag is only parsed when the remote flag is passed as startparameter not when it is passed by config file. When I set REMOTE = true nothing happens. I think there was simply one line forgotten in iri.java.

Best regards
Tobias (@culnamo)

**Comment by flyingvince** [comment]
Hi,

I also observed this issue on IRI 1.3.1. Using start parameter allowed to remotely connect the light wallet to the full node.

**Comment by TeeVeeEss** [comment]
Use `API_HOST=0.0.0.0` in your ini file to enable remote connection to your node.

**Comment by scott79** [comment]
Submitted the following patch for this: https://github.com/iotaledger/iri/pull/315

**Comment by jakubcech** [comment]
Fixed as part of #724
