### ISSUE TITLE
Cannot run a full node behind a proxy

### ISSUE THREAD

**Issue by ThomasBouquet95** [iotaledger/iri#282]
Hello everyone. Almost all companies are behind a proxy. If we want that IOTA become the backbone of IOT and micro payment we have to allow companies to use it. For now, it is impossible to run a full node behind a proxy.  We need to find a way for companies to run full node and then join IOTA project behind it !

**Comment by scott79** [comment]
Hey ThomasBouquet95,

When you state proxy, in what context do you mean? Proxy (such as squid proxy) or outbound nat'd? 

Thanks
