### ISSUE TITLE
Restarts from tangle 15100 when process is restarted

### ISSUE THREAD

**Issue by paaland** [iotaledger/iri#288]
Every time I restart the process it seems to go back to tangle 15100 and start from there.
Before I shutdown the process it was at 195464. Added a new neighbor and started again. 
Last solid tangle went down to 15100 and it's now hours away from being in sync again.

Probably related to [Issue 250](https://github.com/iotaledger/iri/issues/250)

Running with --revalidate option since it does not seem to sync at all without.

**Comment by PatrickHuetter** [comment]
Same problem here.

**Comment by alon-e** [comment]
this is exactly what `--revalidate` does: deletes the stored validation points and recalculates all milestones.
