### ISSUE TITLE
 Not able to spend from address already spent from

### ISSUE THREAD

**Issue by frohal** [iotaledger/iri#289]
After last change in tip-selection, it is no longer possible to send from an address you have already sendt from before.
I consider this a major change in behaviour, and it will result in a whole bunch of IOTA's in addresses that are possible to sign, but impossible to get confirmed...

Note also that this will have enormous impact for ppl that double-sends, and not all wallets will actually give a warning about this...
Those using double-spend for stopping a wrong tx will also be impacted by this change. 

...
And how is this ment to work after snapshots ?  If all old transactions is deleted, how can this feature detect an insecure key reusage ?

**Comment by Pomyk** [comment]
What if someone already made a double spend but none of the transactions confirmed. Is it possible to reattach such bundle?
