### ISSUE TITLE
totalTransactions keeps jumping back 50000

### ISSUE THREAD

**Issue by hapklaar** [iotaledger/iri#290]
On a good running in sync Windows headless node with iri 1.3.2, totalTransactions keep jumping back 50000 transactions. For example:

09/11 13:26:52.677 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2 , toReply = 0 / totalTransactions = 1524987
09/11 13:27:02.679 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 1471869

this happens all the time. Restarting changes the totalTransactions number, but doesn't fix it. --revalidate doesn't fix it.

**Comment by hapklaar** [comment]
Just spotted it's also jumping forwards sometimes:

09/11 13:53:56.161 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 1 , toReply = 0 / totalTransactions = 1426717
09/11 13:54:06.163 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2 , toReply = 0 / totalTransactions = 1426725
09/11 13:54:16.165 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 1426734
09/11 13:54:26.167 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 1596875
09/11 13:54:36.168 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 2 , toReply = 0 / totalTransactions = 1596881
09/11 13:54:46.170 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 1 , toReply = 0 / totalTransactions = 1596890
09/11 13:54:56.172 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 3 , toReply = 0 / totalTransactions = 1596900

**Comment by alon-e** [comment]
see https://github.com/iotaledger/iri/issues/446#issuecomment-354609702 for more details.
