### ISSUE TITLE
Design flaw in IRI UDP listener

### ISSUE THREAD

**Issue by alfredch** [iotaledger/iri#30]
When a system is spamming, then - in my Windows 10 office PC - 30% of transactions are dropped! And this is even the case when repeaters are active in the neighborhood!
Elapsed time measurements show, that frequently the latency of the UDP listener (until socket.receive(receivingPacket); is entered again) is above 2 seconds (probably up to 10-20 seconds) most of the elapsed time. This design will not be able to handle high transaction input.

Important: it's not that the packages are not arriving on the PC, but due to ever limited system buffer size, they are dropped when the application is not receiving them fast enough

Here a quote from http://stackoverflow.com/questions/1507475/winsock-udp-packets-being-dropped that expresses what I would do in this situation:

> The default socket buffer size in Windows sockets is 8k, or 8192 bytes. Use the setsockopt Windows function to increase the size of the buffer (refer to the SO_RCVBUF option).

> But beyond that, increasing the size of your receive buffer will only delay the time until packets get dropped again if you are not reading the packets fast enough.

> Typically, you want two threads for this kind of situation.

> The first thread exists solely to service the socket. In other words, the thread's sole purpose is to read a packet from the socket, add it to some kind of properly-synchronized shared data structure, signal that a packet has been received, and then read the next packet.

> The second thread exists to process the received packets. It sits idle until the first thread signals a packet has been received. It then pulls the packet from the properly-synchronized shared data structure and processes it. It then waits to be signaled again.

**Comment by Come-from-Beyond** [comment]
Two threads approach was used in previous versions of IRI. It was changed to single thread one to mimick real IoT more closely. I would suggest to stick to the current design and to find a better way to solve the issue (e.g. smart broadcasting strategy).

**Comment by alfredch** [comment]
I will contribute a protocol-aware proxy server that does the buffering and re-requesting transactions where there is a gap in the tangle.
Obviously, that will require an option in IRI so that the node.java listener can receive packages internally via TCP/IP with a minimal handshaking.

**Comment by alfredch** [comment]
More evidence:
As soon as I turn off 'the sprayers' alias Repeater in the testnet, the hole confirmation scheme collapses:
Left side of graph: with Repeater,  right side: Repeater shut down.
However, the repeater is, in my opinion, just a too primitive method to compensate missing handshaking and the long lock-outs in the receiver thread.
![image](https://cloud.githubusercontent.com/assets/7837789/21266424/79ba4070-c3a6-11e6-8056-12f3cab04606.png)

**Comment by alfredch** [comment]
The tip selection has changed in the new version. There is no point to keep that issue report open.
