### ISSUE TITLE
Restrict --remote flag to opt-in sensitive API calls instead of opt-out

### ISSUE THREAD

**Issue by cyclux** [iotaledger/iri#306]
A few days ago some of us on Slack discussed a potential issue with the handling of `--remote` flag of IRI. By default it opens the door to `getNeighbors`, `addNeighbors` and `removeNeighbors` if you don't set to restrict them by `--remote-limit-api`. We came to the conclusion that it might be better to *opt-in* those sensitive API calls for `--remote` instead of *opt-out* them because the average user does not know or care about it and opens unintentionally the door for potential harmful operations (gathering IPs, tampering with neighbors). Additionally a lot of users post their IPs on slack despite the warning not to do so. We think that most users of `--remote` don't use those API calls and the low effort to change this is worth the improvement of security.

**Comment by scott79** [comment]
Created the following pull request: https://github.com/iotaledger/iri/pull/320

**Comment by paulhandy** [comment]
I agree. @th0br0 what do you think?

**Comment by jakubcech** [comment]
We'll look at creating a secure default remote limit API parameter to address this issue.
