### ISSUE TITLE
PearlDiver Threading Issue

### ISSUE THREAD

**Issue by domschiener** [iotaledger/iri#31]
I run the testnet version on a two core DigitalOcean VPS (Ubuntu 16.04, 2GB RAM,40gb ssd). It seems that PearlDiver leads to an incorrect output in about 25% of the time. What I mean with that specifically, is that when doing `attachToTangle`, one of the transactions in the bundle usually has an invalid transaction hash, as well as an all 9's nonce. 

Here is an example output on two different machines, with the exact same input (trytes, branch and trunk, as well as minWeightMagnitude):

4 cores, MacOS: http://pastebin.com/Du5JfZWG 

2 cores, Ubuntu 16.04: http://pastebin.com/zV7h51Dc

Considering that PearlDiver / Curl uses n - 1 cores, this is probably related with doing POW on a single core machine. Any thoughts?

**Comment by paulhandy** [comment]
It sets the number of threads to 1 if there is only a single core. Threading in this case would just result in the main process being paused while the child process is executed.
