### ISSUE TITLE
Build Failure when packaging on ARM-based SbC

### ISSUE THREAD

**Issue by tuddman** [iotaledger/iri#312]
`v1.4.0`

```
$ mvn package
...

Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.485 sec <<< FAILURE! - in com.iota.iri.storage.TangleTest
get(com.iota.iri.storage.TangleTest)  Time elapsed: 0.465 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni4242487589553788365.so: /tmp/librocksdbjni4242487589553788365.so: cannot open shared object file: No such file or directory (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.storage.TangleTest.setUp(TangleTest.java:37)

save(com.iota.iri.storage.TangleTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.storage.TangleTest.setUp(TangleTest.java:37)

getKeysStartingWithValue(com.iota.iri.storage.TangleTest)  Time elapsed: 0.007 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.<init>(RocksDBPersistenceProvider.java:28)
	at com.iota.iri.storage.TangleTest.setUp(TangleTest.java:37)

```

possibly relevant link:  https://github.com/facebook/rocksdb/issues/678

**Comment by tuddman** [comment]
`mvn clean compile` works and results in a successful build.

`mvn package` throws the RocksDB errors when conducting the tests as part of maven't packaging step.

**Comment by jserv** [comment]
@tuddman, FYI.
I maintain Aarch64-friendly branch of RocksDB, which manipulates packaging issues and provides ARM64-specific optimizations: https://github.com/jserv/rocksdb
You should be able to execute [BUILD.sh](https://github.com/jserv/rocksdb/blob/deviceproof-5_8/BUILD.sh) and [DEPLOY_MAVEN.sh](https://github.com/jserv/rocksdb/blob/deviceproof-5_8/DEPLOY_MAVEN.sh) for customized `rocksdbjni`.
Corresponding IRI: https://github.com/jserv/iri

**Comment by Citrullin** [comment]
@jserv Already created a pull request for rocksDB? Would be great. I currently try IRI on a scaleway machine. I also have a bunch good board here. :)

**Comment by Citrullin** [comment]
@jserv I would recommend to add that your rocksDB only supports Ubuntu. Tried it on a clean Debian and had some issues. On Ubuntu it seems to working fine. :)

**Comment by jserv** [comment]
In order to run IRI perfectly on ARMv8-A or ARMv7-A machines, more aggressive optimizations against RocksDB are necessary, otherwise we would suffer from various resource problems such as ouf-of-memory (OOM).

I am still seeking for feasible solutions, and that is the reason why I didn't submit PR against RocksDB.

**Comment by Citrullin** [comment]
@jserv Node is up and running. Added some full nodes but I don't know if it ever synchronizes. I get the following message the whole time:
```
INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 0 , toReply = 0 / totalTransactions = 0
```
I added 5 neighbors.

**Comment by mlouielu** [comment]
How about using API?

$ curl http://localhost:14265 -X POST -H'Content-type: application/json'
-H'X-IOTA-API-VERSION: 1.4.1' -d '{"command": "getNodeInfo"}'

2017-12-14 21:21 GMT+08:00 Philipp <notifications@github.com>:

**Comment by Citrullin** [comment]
@mlouielu 
```
{"appName":"IRI","appVersion":"1.4.1.2","jreAvailableProcessors":6,"jreFreeMemory":62851672,"jreVersion":"1.8.0_151","jreMaxMemory":919076864,"jreTotalMemory":461373440,"latestMilestone":"999999999999999999999999999999999999999999999999999999999999999999999999999999999","latestMilestoneIndex":243000,"latestSolidSubtangleMilestone":"999999999999999999999999999999999999999999999999999999999999999999999999999999999","latestSolidSubtangleMilestoneIndex":243000,"neighbors":4,"packetsQueueSize":0,"time":1513259913823,"tips":0,"transactionsToRequest":0,"duration":1}
```

**Comment by jserv** [comment]
Cc. @yillkid, who maintains various ARMv8-A / ARMv7-A nodes.

**Comment by Citrullin** [comment]
I already got it. As I read both parties needs to add them as neighbors.

**Comment by mlouielu** [comment]
@Citrullin ah, yes. You will need both side to add as neighbors. and tcp to tcp, udp to udp.

**Comment by imakiro** [comment]
Hello,
Are there any updates as of the progression of the arm build possibility?
I don't mind having to recompile but that roocksdbjni dependency is still messing the packaging up.

**Comment by Citrullin** [comment]
@imakiro Nope, still a mess and complicated. I would recommend to wait until they implemented it in C. They don't want to stick to Java.

**Comment by jserv** [comment]
@imakiro, please check the instructions: https://medium.com/biilabs/deploy-iota-fullnode-on-asus-tinker-board-fcd2cff8331f # feel free to contact @yillkid, who maintains ARM build of IRI-powered nodes.

**Comment by Citrullin** [comment]
@jserv Intersting. Interesing. Is there a need for modification for armv8?

**Comment by jserv** [comment]
@Citrullin, You should execute [BUILD-iri.sh](https://github.com/deviceproof/iota-deploy/blob/master/scripts/iri/BUILD-iri.sh) to prepare ARMv8-A build out of box.

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
