### ISSUE TITLE
what():  std::bad_alloc

### ISSUE THREAD

**Issue by janfiedler** [iotaledger/iri#323]
Hi, after month, node stop working and after restart i get this error in loop.
Linux Debian 9. I try uninstall java and install brand new. No help. 
Is possible it is bug in IRI, ofc i use last one 1.4.0? Thanks

`Oct 15 18:00:59 iota1 java[15565]: terminate called after throwing an instance of 'std::bad_alloc'
Oct 15 18:00:59 iota1 java[15565]:   what():  std::bad_alloc
Oct 15 18:00:59 iota1 systemd[1]: iota.service: Main process exited, code=killed, status=6/ABRT
Oct 15 18:00:59 iota1 systemd[1]: iota.service: Unit entered failed state.
Oct 15 18:00:59 iota1 systemd[1]: iota.service: Failed with result 'signal'.
Oct 15 18:00:59 iota1 systemd[1]: iota.service: Service hold-off time over, scheduling restart.
Oct 15 18:00:59 iota1 systemd[1]: Stopped IOTA node.
Oct 15 18:00:59 iota1 systemd[1]: Started IOTA node.
`

**Comment by tuddman** [comment]
observing same error in `1.4.1.1`

**Comment by brenzi** [comment]
Same error here, 1.4.1.1

**Comment by brenzi** [comment]
Even worse, iri clutters `/tmp` with files like `librocksdbjni12772173036282430841.so` after every such crash. jammed my fs

**Comment by brenzi** [comment]
On slack I was told this is an out-of-memory issue. As I had 14 neighbors and only 2GB RAM, that could be the issue

**Comment by rajivshah3** [comment]
Seeing this on 1.4.1.2 as well
Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by paulhandy** [comment]
I've heard someone mention something about over-allocating memory with the `Xmx` argument, which relates to the amount of available RAM on the system.

**Comment by glumb** [comment]
Same issue with 8 neighbors 5GB RAM for Java.
```
IRI 1.4.1.2
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
What is the expected size for the database directory?

**Comment by timeofmind** [comment]
I'm seeing this same bug in v1.4.1.4

Linux vps163888 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

/usr/bin/java -Xmx5G -XX:+DisableAttachMechanism -jar /opt/iota/IRI.jar --revalidate -p 14700 -c /opt/iota/iri.ini

Before starting the process:

Mem:        7985056       54660     6472540       28532     1457856     7671428

Plenty of memory.

**Comment by timeofmind** [comment]
I decresed the jvm heap size to 4GB (-Xmx4G) and monitored memory usage. The jvm heap size seems to have very little to do with the amount of memory the java process uses do to c libraries it employs. I'm running this on a VPS instance that runs nothing other than the IOTA node. Obviously 8GB of memory is just not enough to run a full IOTA node. I'll try upgrading to a 12GB VPS and hope that it will be enough.

**Comment by curVV** [comment]
I am also getting this now. It happened after updating to 1.5.0, but reverting back to 1.4.2.4 now it also happens, but instantly after starting IRI. With 1.5.0 it happens after about 10 minutes or so. The node has 16GB of RAM. I used to run with -Xmx8000. I've now tried with no memory flags and also -Xmx10000, all with same `what(): std::bad_alloc` crash.
