### ISSUE TITLE
Is it ever planned to use C++ for full nodes to increase the performance (TPS)?

### ISSUE THREAD

**Issue by AlexeyAB** [iotaledger/iri#327]
Is it ever planned to use C++ for full nodes, or in library for full nodes, to increase the performance (TPS) of the Tangler?

**Comment by paulhandy** [comment]
Not necessarily ++, but at least C, yes.

**Comment by alon-e** [comment]
Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
