### ISSUE TITLE
Race condition in PearlDiver (iri version 1.1.2.2 dev)

### ISSUE THREAD

**Issue by alfredch** [iotaledger/iri#33]
There is this severe problem in PearlDiver which causes a sporadic return of 99999999... nonce:
The flag 'state' controls the inner and outer thread(s) in the search() function.
When one of the inner threads finds a success (minWeightMagnitude  counted down to 0), then it set state = COMPLETED and notifyALL().
That causes the main thread to terminate and the function search to return.
However, the inner thread continues to run because the function search() is called again in the mean time. 
Probably (not checked by myself) the same instance of PearlDiver is used for a multi-tx bundle. So the new call to search(...) can set state = RUNNING again before the old inner thread executes the 'while (state == RUNNING)' check. So that one continues and messes up the work of the regular diver thread.

If in doubt, trace the situation with log.debug within the diver thread. I did it and it happens every so often (Maybe you have to repeat a 4tx bundle' attachToTangle 20 times until that overlapping is visible, but on a average it happen every 4th time).

**Comment by alfredch** [comment]
The IRI-version that I was referring to is 1.1.2.2-dev, not 1.2.2.2-dev.

**Comment by davassi** [comment]
is it related to #31?

**Comment by alfredch** [comment]
Yes - it's the same. Dominik asked for help - sorry I didn't see he had already created an issue.

**Comment by alfredch** [comment]
I have identified 2 problems related to that issue:
1) PearlDiver search() function is not thread-safe because of in-out-argument 'transactionTrits' and the usage thereof in the internal worker threads.
2) The internal worker threads are not controlled safely by the state flag. There is a time window where a caller can re-establish state RUNNING before the worker thread tests for the actual state. That means the inner threads will potentially continue executing also the intention was that they terminate.
I will make a PR request with the minimal fixes, avoiding a major re-coding of the class.
