### ISSUE TITLE
Invalid API Version - 1.4.1.1

### ISSUE THREAD

**Issue by SanderEliteEngineering** [iotaledger/iri#334]
This error is received from the IRI 1.4.1.1 using a basic Postman call to getNodeInfo, getTips, and other API calls. This could be breaking a lot of integrations with the IRI. I would hate to assume this is what is preventing Bitfinex and Binance from deposits and withdraws at the moment.  This seems very urgent.

**Comment by mlouielu** [comment]
Please add `X-IOTA-API-VERSION: 1.4.1` to your headers.

**Comment by SanderEliteEngineering** [comment]
I see that here now, thanks. https://github.com/iotaledger/iri/blob/master/src/main/java/com/iota/iri/service/API.java#L159
It doesn't seem to care what version value is sent though, its just looking for the header name.

That would fix the issue in Postman, but my iota.js.lib which is on 0.4.2 still gets the error. I see the makeRequest adds the header in 0.4.2, so I wonder what is going on here.
