### ISSUE TITLE
Bug: IRI returns HTTP 400 when given address with checksum.

### ISSUE THREAD

**Issue by eukaryote31** [iotaledger/iri#342]
IRI should remove address checksums.

**Comment by th0br0** [comment]
Client libraries should not send addresses with checksums.
`iota.lib.js` `v0.4.3` fixes this. A similar fix for java is forthcoming.

**Comment by th0br0** [comment]
Checksums are a user-facing feature, not something that IRI knows or cares about (e.g. search for `checksum` in the IRI tree, you won't find any references)

**Comment by alon-e** [comment]
>You can't rely on the client to send sane inputs.
IRI doesn't "sanitize" inputs, it validates inputs according to whitelist rules and rejects otherwise. like non 81-tryte addresses.

>IRI should remove address checksums.
imo removing checksum w/o validating it gives a false sense of security/integrity.
