### ISSUE TITLE
NoClassDefFoundError when running v1.4.1.2 with --rescan and jdk9

### ISSUE THREAD

**Issue by nimearo** [iotaledger/iri#344]
javax.xml.bind classes are now included in a module since java 9. 
As a workaround iri can be started with an additional jvm option 
> --add-modules java.xml.bind

For details see link below:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by nayanmshah** [comment]
This should be fixed after https://github.com/iotaledger/iri/pull/379 is merged. Tested with jdk 1.8 and 1.9. It works fine.

**Comment by alon-e** [comment]
fixed in 948b8d0
