### ISSUE TITLE
[CI] Add iota.lib.js, iota.lib.py to CI test

### ISSUE THREAD

**Issue by mlouielu** [iotaledger/iri#346]
Sometime, IRI update will break iota.lib.js, iota.lib.py

Could CI test add this two package to test, too?

Thanks.

**Comment by Alcemaria** [comment]
Gostei muito só que não consigo min era iota

**Comment by paulhandy** [comment]
We're working on setting up a proper CI environment precisely for this currently.

**Comment by jakubcech** [comment]
The '.js' version of this is being worked on here: https://github.com/iotaledger/iri/issues/650
Thanks for reporting mlouielu!
