### ISSUE TITLE
Snapshots should include the information of used addresses

### ISSUE THREAD

**Issue by MirAGAiN** [iotaledger/iri#349]
Current snapshots are only include the balance of each address of which the balance is not zero.
This can be serious problem when it comes to preventing double spending.

For example, if the address have been used by outgoing transaction before a snapshot, current nodes cannot reject but confirm the addtional transaction after the snapshot since the node doesn't know the address have been used.
However, the part of the private key of the address is already revealed, so the address is very vulnerable to replay attacks.
In conjunction with the seed-based wallet which does not generate all of the addresses which were generated before the snapshot, the problem worsens.

In fact, my address was recently hacked by a replay attack.
I accidentally sended some iotas from bitfinex to my address which already been used.
2 hours after the bitfinex's confirmation, deposited iotas have gone to unknown address.
I have not seen the recipant address before, so I think the private key of the address have been compromised.
The hacked address is:
https://iotasear.ch/address/RLBRWTILUHBCNRCAKJPRZHUKCLRMJHKHODXXEBXYHALSRFDFFQBMATBFTFHHVRUSCL9KTDASEJFKUBYAXDWVSPUYZC

In addition, if the snapshot contains the information of used addresses, it can have big benefit to current seed-based wallet.
It is able to solve the zero-balance issue after snapshot since the wallet knows how many addresses should be generated.

**Comment by pRizz** [comment]
I was wondering if this was a feasible attack vector. If you were truly hacked because of this, then we are in a bad situation. Following your addresses transactions and addresses leads to these addresses, totalling over 140Gi's!

https://iotasear.ch/address/UVSOVYYFWJPIEEIJCRQWYIEZ9QDFVLMWPOCYHPXRCNFGZXNBPSPDHVLCBCHWQWGHLGLNMMCDRTSD9RZPD
https://iotasear.ch/address/SNADUFCJEQDTGB9CXEUNZACSNTYJ9BLSDNKIYTTAKOIUINGWJTLMSZQH9IBNWMKLZFKCXRTDTFFDMVHIC

**Comment by MirAGAiN** [comment]
If you follow the transaction reversely, you can find another victim very easily:
https://iotasear.ch/address/HADRP9WGAVICBMFWPNXLRPWDFPHTVVLE9UXFTTMSHECOMUAGTRCPJZOHVOOJOBTUXTAZCWRUGCZTPLZJZ
Since the address is also double-spended, I think the attacker have been bruteforcing the private key of some used address. There was enough time to do that.

Maybe the seed was leaked, but the possibility is very low since I made the seed myself and I have never wrote the seed in plain text.

**Comment by maxmbed** [comment]
This is something we really need to care if it is really effective.

**Comment by alon-e** [comment]
has been adopted as a temporary measure till stateful wallets are common: #504
