### ISSUE TITLE
minimum specification for the server 

### ISSUE THREAD

**Issue by helxsz** [iotaledger/iri#353]
Hi, if I am going to run https://github.com/iotaledger/iri, what is the minimum specification for the server ?

**Comment by ixidion** [comment]
The machine should have at least 8GB RAM or more, 4 cores and a SSD.

**Comment by devender-yadav** [comment]
I don't think at least 8GB RAM is needed. It's good if you can manage 8 GB. You can start with 4 GB.

**Comment by ixidion** [comment]
#422 It's reported that Nodes are running into problems with only 4 GB.

**Comment by devender-yadav** [comment]
@ixidion, thanks for the reference!
