### ISSUE TITLE
MAX_REQUESTS_LIST causes failed logins

### ISSUE THREAD

**Issue by HenrikLaxhuber** [iotaledger/iri#360]
Upon login, the wallet (and iota.lib.js) issues a getTrytes API call to receive trytes on all of its transactions. If the getTrytes request contains more than 1000 transactions, the request is dropped with an unspecific "Could not complete request". Note that the GET_MAX_TRYTES variable is set to 10,000, but has no effect due to the MAX_REQUEST_LIST limiting the length of the request array.

This causes a failed connection request for users with many transactions to and from their addresses.

A hotfix would be to drop the check of MAX_REQUEST_LIST in  `getParameterAsList` if the request is to getTrytes, or to remove the GET_MAX_TRYTES limiter to avoid confusion and instead handle the issue client-side by splitting into multiple request. This would also provide a long-term fix.

Note that the issue thus affects both IRI and iota.lib.js, wherefore solutions should be coordinated between both projects.

**Comment by th0br0** [comment]
Hey,
we are aware of this and Chris is working on a fix right now. We will release this week.
I'll leave this report open and follow up with you once it's been released :)

**Comment by onemoreitguy** [comment]
@th0br0: Still not released right?

**Comment by onemoreitguy** [comment]
Can see my wallet with that workaround. Thanks.
this limitation is only client/node related right? doesn't affected new transactions on the seed. Or should I prevent to send/receive until new versions are available?

Eager to get the next patched version. Good luck.

**Comment by onemoreitguy** [comment]
Just to summarize and let everyone to understand:

**ISSUE**: users are getting connection error when trying to sign-in
**CAUSE**: wallets with a significant amount of transactions are disconnected after awhile by the nodes. There is a limit defined that prevents large amount of data transfers (max:1000).
**WORKAROUND**: (a) install a full node (or find one). (b) Define on the ini file the following parameter MAX_REQUESTS_LIST=10000. (c) connect the wallet. It takes more than 10-60 minutes for the node and the wallet to process all the records
**SOLUTION**: wait for a node and wallet releases

Again: I'm not related to the dev team (I'm just a IOTA supporter and enthusiast) and I found this by searching and support from the people above

**Comment by Stcetjo** [comment]
FYI, some bundles contain lots of transactions (bitfinex withdraws) if they get reattached many times then it adds up the transaction counts quickly.

**Comment by HenrikLaxhuber** [comment]
Fixed in 0.4.5
