### ISSUE TITLE
1.4.1.2 breaking getBalances

### ISSUE THREAD

**Issue by davila9210** [iotaledger/iri#365]
The getBalances function returns 'invalid addresses input' on any 1.4.1.2 node. Tried this on my own node and other nodes. When I switched back my own node to 1.4.1.1 it was working again

curl -s http://node01.iotatoken.nl:14265 -X POST -H 'X-IOTA-API-Version: 1.4.1' -H 'Content-Type: application/json' -d '{"command": "getBalances", "addresses": ["GBDSEBCDAVYVCCHEACILTATX9MGDWITKXMHFROZILRI9M99FRJJMWYYRVRBCMKQTBGRVPWYJURXTQO9T99GLCKHJMX"], "threshold": 100}' | python -m json.tool

On a 1.4.1.2 node retrieving: {"error":"Invalid addresses input","duration":0}

**Comment by th0br0** [comment]
The IOTA API only accepts non-checksummed addresses starting with 1.4.1.2
Above address contains a checksum (the last 9 trytes).
