### ISSUE TITLE
Oracle Java 9 and iri 1.4.1.2 - Start up error

### ISSUE THREAD

**Issue by cricrides** [iotaledger/iri#378]
Hello

using java 9 and iri 1.4.1.2, at start up we have the following error message
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.xnio.nio.NioXnio$2 (file:/home/IOTA/iri-1.4.1.2.jar) to constructor sun.nio.ch.EPollSelectorProvider()
WARNING: Please consider reporting this to the maintainers of org.xnio.nio.NioXnio$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

System starts and operates normally after...

Regards

cricri

**Comment by tawago** [comment]
@cricrides 
please, use 8 instead.
or i heard `--add-modules java.xml.bind` option helps with 9

**Comment by cricrides** [comment]
Hello, 
Java 9 is started with the right options including the --add-modules java.xml.bind,
The problem is not really there... But thanks for your answer ;)

**Comment by nimearo** [comment]
In my opinion this is a warning that a third party library is accessing an internal API of the jdk. But in my understanding its just for information in jdk 9 to give developers time to migrate their codes to make it compatible with the new modular jdk. 
See here https://jaxenter.com/jdk-9-replace-permit-illegal-access-134180.html

Nevertheless it's a class from org.xnio. So when they had updated their code iri might update to the new version.

**Comment by cricrides** [comment]
Hello, I think you are right on that one!
Let's close the issue and see with the next version what happens.

Thanks a lot :)
