### ISSUE TITLE
Open/Closed P2P discovery

### ISSUE THREAD

**Issue by benjyz** [iotaledger/iri#387]
Is Iota is open blockchain/network? This part of the readme indicates otherwise.

"Obviously, because this is its own, independent network, you have to go through the same process as in the main network: find neighbors. You can find neighbors in the #nodesharing Slack channel[Slack Invite], or on our forum. "

**Comment by tawago** [comment]
@benjyz yes it is. this topic is irrelevant to IRI issues so could you pease closed this? 

check the slack for more.
Here's the link to join the IOTA Slack: https://join.slack.com/t/iotatangle/shared_invite/enQtMjgzNDMwNTc2ODg3LTYwNmFjODNhOThjZDA3OGIzZWIxYjFjYWY4YjAzYjg1NDVlMGVkMWE3N2EyODRiY2UyYmI5OWI4ZDU5MjY0NjQ this link will be valid for up to 1000 users and will then need to be reset. If the link expires, please notify a mod.

**Comment by benjyz** [comment]
we are an exchange looking into iota, but the docs are very confusing. the readme and docs needs updating, with regards to node discovery. In our view P2P systems don't work on a nice to have basis. if discovery is centralised through communications channel its not going to be something we're interested in. I think this answer the question.
