### ISSUE TITLE
IRI not updating milestone indices

### ISSUE THREAD

**Issue by alfredch** [iotaledger/iri#40]
It has been reported by many node operators that milestones indices lag behind the #botbox numbers. Deltas of 1 to 15 are frequent. All of a sudden, and apparently simultaneously in all affected nodes, the indices catch up with the #botbox numbers - without a restart of IRI.
When IRI is restarted, then in most cases the indices are in sync with the #botbox numbers after a short time.

**Comment by dhughesbc** [comment]
There is a possibly related behavior I have seen several times in the several weeks that I have been running a 24/7 node. My `latestSolidSubtangleMilestoneIndex` has gone *backward* from being in sync with `latestMilestoneIndex' back to a number somewhere around 13500. Unfortunately I don't remember the exact number, but it is definitely between 13,000 and 14,000 and I am fairly certain it was the same number every time it has happened. 

After a day or so the node magically reverts to being in sync. In my experience restarting does NOT fix the issue.

**Comment by alfredch** [comment]
Solved in the new releases
