### ISSUE TITLE
When using no-ip dns_referesher will break the rule

### ISSUE THREAD

**Issue by mlouielu** [iotaledger/iri#402]
https://github.com/iotaledger/iri/blob/acfbc76f39c785aa0914f8bcb6745f34d8f6511b/src/main/java/com/iota/iri/network/Node.java#L182

DNS_REFRESHER_ENABLED default is `true`, if someone using no-ip and changed it's ip, this will break the no-ip domain to ip, and next time the user changed it's ip, the connection will just break up with no cause.

**Comment by jojoCoWorker** [comment]
Maybe linked to those issues : 
#149 
#373

**Comment by jojoCoWorker** [comment]
Linked to #979 and #790

**Comment by jojoCoWorker** [comment]
This issue doesn't exist anymore since network rewrite in v1.8.0
I think we can close it

**Comment by jakubcech** [comment]
Thanks!
