### ISSUE TITLE
iri doesn't shutdown or it takes a very long time

### ISSUE THREAD

**Issue by ccmawo** [iotaledger/iri#417]
12/20 06:26:36.192 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
....
12/20 08:41:35.556 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 1 , toReply = 0 / totalTransactions = 7127503

Iri 1.4.1.4 is still running:
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                        
23814 iota      20   0 15.775g 5.300g  20096 S  12.7 34.5  59:45.20 java  

Environment:
Ubuntu 16.04.3
Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
16GB RAM
2x 7200 rpm 3TB Seagate RAID 1

command line:
/usr/bin/java  -server -Xmx10g \
    -XX:MinHeapFreeRatio=20 \
    -XX:MaxHeapFreeRatio=90 \
    -Djava.awt.headless=true \
    -XX:+UseConcMarkSweepGC -XX:+UseParNewGC \
    -Djava.net.preferIPv4Stack=true -jar iri.jar 

java version:
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by tlc2** [comment]
kill the process
