### ISSUE TITLE
Getting instantly out of sync after adding neighbor

### ISSUE THREAD

**Issue by bluedigits** [iotaledger/iri#418]
Hi,

I double-checked an issue which occurs when you do the following:

1. Get the node in sync, i.e. wait until it's at the most current milestone.
2. Add one more neighbor and restart the node.
3. The node's milestone will be jump back to `243000`

I can do this again, it's always same behaviour.

**Comment by benoslav** [comment]
it's not an issue. if you restart the node it takes some time to be sync again

**Comment by bluedigits** [comment]
You're right, thanks!
