### ISSUE TITLE
Out of memory 

### ISSUE THREAD

**Issue by magicsunday** [iotaledger/iri#422]
My full node runs on a system with 4GB RAM and 3GB Swap

Java starts with either

    /usr/bin/java -XX:+CrashOnOutOfMemoryError -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+CMSParallelRemarkEnabled -XX:+DisableAttachMechanism -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxMetaspaceSize=30m -Xmx3G -Xms2G -Djava.net.preferIPv4Stack=true -jar iri-1.4.1.4.jar --remote -c iri.ini

or

    /usr/bin/java -server -Xmx2G -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=90 -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -Djava.net.preferIPv4Stack=true -jar iri-1.4.1.4.jar -c iri.ini

as found in some other issues here.

After a few seconds or some minutes it terminates:

[pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 1 , toReply = 0 / totalTransactions = 7562839
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

or

Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x000000075b693000, 614436864, 0) failed; error='Cannot allocate memory' (errno=12)

- What parameters should I use for JAVA to limit the maximum memory so JAVA wont quit?
- What are the minimum requirements for running a full node?

**Comment by ixidion** [comment]
Get more memory. 8GB should be the minimum, I have 12GB and it's totally fine with some reserves. 

Swap Space won't help, because Java Heap Space is not designed to be swapped to disk. 

https://iota.stackexchange.com/questions/1022/what-are-the-minimum-requirements-to-run-a-full-node/1023#1023

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
