### ISSUE TITLE
getNeighbors should include appVersion

### ISSUE THREAD

**Issue by zoran** [iotaledger/iri#423]
as we found out in the last update, the version would be very useful to actively maintain the neighborhood
```
{
  "address": "xxx",
  "appVersion": "1.4.1.4",
  "numberOfAllTransactions": 1,
  "numberOfRandomTransactionRequests": 1,
  "numberOfNewTransactions": 1,
  "numberOfInvalidTransactions": 0,
  "numberOfSentTransactions": 1,
  "connectionType": "udp"
}
```

**Comment by Citrullin** [comment]
Ohh yes. I created a feature request for auto-upgrades. But both would be really nice. In case you can somehow disable auto-upgrades.

**Comment by ixidion** [comment]
This information has to be sent from the peer and can not determined by the node itself. 
It makes no sense knowing the version of the peer, because it can be changed and faked. So it won't help your problem, to maintain your neighborhood. Think of IRI as one implementation of an IOTA node.

**Comment by alon-e** [comment]
as @ixidion said, how would you solicit this information and know it's correct?
closing issue due to lack of discussion - can be reopened if a detailed solution is proposed.
