### ISSUE TITLE
IXI modules not loading in 1.4.1.x

### ISSUE THREAD

**Issue by danielfaust** [iotaledger/iri#426]
I tried to load
https://iota.stackexchange.com/questions/642/what-does-an-hello-world-ixi-module-look-like
and
https://github.com/bluedigits/nstats
and both of them caused an exception

```
12/21 08:34:10.795 [main] INFO  com.iota.iri.IXI - Searching: ixi/nstats
12/21 08:34:10.801 [main] INFO  com.iota.iri.IXI - Loading module: nstats
12/21 08:34:10.801 [main] INFO  com.iota.iri.IXI - Starting script: ixi/nstats/index.js
12/21 08:34:10.805 [main] ERROR com.iota.iri.IRI - Exception during IOTA node initialisation:
java.lang.NullPointerException: null
        at com.iota.iri.IXI.attach(IXI.java:249) ~[iri.jar:na]
        at com.iota.iri.IXI.loadModule(IXI.java:223) ~[iri.jar:na]
        at com.iota.iri.IXI.access$200(IXI.java:31) ~[iri.jar:na]
        at com.iota.iri.IXI$1.preVisitDirectory(IXI.java:76) ~[iri.jar:na]
        at com.iota.iri.IXI$1.preVisitDirectory(IXI.java:71) ~[iri.jar:na]
        at java.nio.file.Files.walkFileTree(Files.java:2677) ~[na:1.8.0_152]
        at com.iota.iri.IXI.registerRecursive(IXI.java:71) ~[iri.jar:na]
        at com.iota.iri.IXI.init(IXI.java:63) ~[iri.jar:na]
        at com.iota.iri.IRI.main(IRI.java:88) ~[iri.jar:na]
12/21 08:34:10.817 [Shutdown Hook] INFO  com.iota.iri.IRI - Shutting down IOTA node, please hold tight...
```

I just noticed that I had an issue with bluedigits/nstats with 1.4.1.2 already https://github.com/bluedigits/nstats/issues/3 but I remember clearly that I did see the line from this code `print("Neighbor stats extension started... ");` printing `Neighbor stats extension started... ` into the log, even tough it was not the case in the exception snipped quoted in that comment.

And in iotaledger/Snapshot.ixi I see an issue with a comment from about two days ago saying that it is no longer working https://github.com/iotaledger/Snapshot.ixi/issues/2

This line causes the exception
https://github.com/iotaledger/iri/blob/v1.4.1.4/src/main/java/com/iota/iri/IXI.java#L249

So apparently `private final ScriptEngine scriptEngine = (new ScriptEngineManager()).getEngineByName("JavaScript");` in 
https://github.com/iotaledger/iri/blob/v1.4.1.4/src/main/java/com/iota/iri/IXI.java#L37 is assigning `null` to `scriptEngine`

**Comment by danielfaust** [comment]
Possibly a Docker Alpine issue. Had feedback in Slack that it does work.

**Comment by bluedigits** [comment]
Yep, Nashorn support seems to be explicitly removed from the anapsix alpine image.

**Comment by danielfaust** [comment]
It is enabled.
https://github.com/anapsix/docker-alpine-java/blob/ec088571103347eda1e5dd783871c219e97d52f3/8/152b16/server-jre/standard/Dockerfile#L74
https://github.com/anapsix/docker-alpine-java/blob/ec088571103347eda1e5dd783871c219e97d52f3/8/152b16/server-jre/unlimited/Dockerfile#L74

**Comment by bluedigits** [comment]
I only can see a rm -rf /opt/jdk/jre/lib/ext/nashorn.jar in #L74 ?

**Comment by danielfaust** [comment]
Jesus Christ... Thanks!

**Comment by bluedigits** [comment]
Np :)

**Comment by danielfaust** [comment]
I think that one uses Debian. I tried OpenJDK in Alpine and I couldn't get IRI to start, so I switched to Oracle. I really want to obtain that ~500 MB size reduction. I'll modify that Dockerfile and see what I can do.

**Comment by danielfaust** [comment]
Yup, that line had to be removed. The hello world example is now working and the image size is 129.1 MB.
