### ISSUE TITLE
latestMilestoneIndex does not update for more than 30 min

### ISSUE THREAD

**Issue by rajivshah3** [iotaledger/iri#436]
Once starting IRI, the latestMilestoneIndex shows 243000. In previous versions of IRI, it would immediately change to the latest milestone issued by the coordinator. Since 1.4.1.2, it takes more than 30 min to recognize the latest milestone, and sometimes does not recognize it at all.

**Comment by pompomJuice** [comment]
Same story

**Comment by alon-e** [comment]
fixed in 1.4.1.7
