### ISSUE TITLE
How to create a Snapshot signature file?

### ISSUE THREAD

**Issue by vikulin** [iotaledger/iri#438]
I'm trying to setup several IOTA nodes. Can you please assist me with the Snapshot signature generation? These nodes will work within a private network. Commenting out the signature generation is not an option since I'm going to run performance tests under similar nodes like IOTA mainnet does.

How to create a Snapshot signature file?

Thanks

**Comment by alon-e** [comment]
We currently don't support private networks setup. so there isn't any code to do so.
However, you can look at the public testnet code, to see how the snapshot signature is not validated, yet doesn't effect the performance of the node (to have similar performance as the mainnet nodes).

**Comment by vikulin** [comment]
It can affect when Coordinator creates a new snapshot.

**Comment by vikulin** [comment]
@alon-e , can you please reopen the issue?

**Comment by alon-e** [comment]
So you are referring to milestones?

**Comment by vikulin** [comment]
Yes, I do

2017-12-24 22:31 GMT+02:00 Alon Elmaliah <notifications@github.com>:
