### ISSUE TITLE
Invite to slack Iotatangle.slack.com

### ISSUE THREAD

**Issue by dantasgut** [iotaledger/iri#439]
Good afternoon people, could anybody share an invite to  IOTA's slack?

**Comment by mostaruk** [comment]
@dantasgut Valid for 1k users https://join.slack.com/t/iotatangle/shared_invite/enQtMjkyMDEwNTg5NTU5LTExMWUyYTA1MDc0MTU5NThkOGFlODVhOTM0NjM3ZjVhNDcwMjMzZDk4NDNlMzI5OWMyY2MxZDNmMDIwOTE5ZmQ
