### ISSUE TITLE
Cant find working Slack invite, want to contribute

### ISSUE THREAD

**Issue by vach** [iotaledger/iri#442]
Hi guys, you're doing some awesome work, just recently i looked into the repo and to my surprise someone finally did something awesome in java. So i'd like to contribute but all the links i found for slack are not functional.

**Comment by mostaruk** [comment]
@vach only valid for 1k users https://join.slack.com/t/iotatangle/shared_invite/enQtMjkyMDEwNTg5NTU5LTExMWUyYTA1MDc0MTU5NThkOGFlODVhOTM0NjM3ZjVhNDcwMjMzZDk4NDNlMzI5OWMyY2MxZDNmMDIwOTE5ZmQ

**Comment by alon-e** [comment]
closing issue - let's leave only #451 open for slack links, if needed.
