### ISSUE TITLE
`info` attribute is sometimes missing from `checkConsistency` output

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iri#444]
In some cases, `checkConsistency` returns a response with both `state` and `info` attributes.  Other times, only `state` is present.

Examples:

```javascript
{'state': True, 'duration': 239}
{'state': False, 'info': 'tails is not consistent (would lead to inconsistent ledger state)', 'duration': 239}
```

It looks like `info` starts as `null` and only gets set when `state` is `false`. If it's `null` when [`gson.toJson`](https://github.com/iotaledger/iri/blob/501e9493bc0cbd1ef1b3e0df6da39efb8ef4083d/src/main/java/com/iota/iri/service/API.java#L923) is called, that [value will be ignored and not included in the response dictionary](https://stackoverflow.com/questions/3923759/gson-ignoring-map-entries-with-value-null).

I feel like the response structure from the API should be consistent; should `checkConsistency` be modified so that its response always includes `info`, even if `null`?

**Comment by alon-e** [comment]
yes, `info` is returned only when `state ==false`.
this was intentional, however, rethinking it - I agree that "the response structure from the API should be consistent;"

I'll prepare a PR.
