### ISSUE TITLE
Dear developers, please look the report, lot of users have these issues.

### ISSUE THREAD

**Issue by ALEX778899** [iotaledger/iri#449]
Dear developers, I'm helping a lot of users, even in iotatangle.slack.com, I know you are incredibly busy, but please look the report of the issues, they are experiencing:
- never become full sync (my workaround https://github.com/iotaledger/iri/issues/375);
- have memory problems (my workaround https://github.com/iotaledger/iri/issues/409);
- have tons of invalid transactions after 1.4.1.4 update;
- they are loosing the sync, nodes not updating the solid subtangle at some point. It doesnt happen all the time, it seems random;
- some have problems with udp, maybe it's the packets fragmentation (MTU of UDP is 1500, and transaction length is 1604 bytes). And some VPS companies (Digital Ocean, Scaleway) block UDP IRI traffic (it could be the same packets fragmentation).

I checked with my team, there aren't bottlenecks, memory or OS problems, the problem should be in IRI code and I must be honest, I am a little frustrated about the very little communication from you guys.
Please @paulhandy don't write me "I wouldn't be surprised to find this to be another instance of a concern troll account", I hope you'll fix the issues in the next release.

Thanks for the beautiful work you are doing.
Regards

**Comment by StefanEkstam** [comment]
I am all but giving up totally on IOTA because of this. Please. I really want to start programming for IOTA, but if I can't even get a full node working for me, why should I give this (theoretically wonderful) concept any more of my time?

**Comment by mostaruk** [comment]
@StefanEkstam I am exactly the same been trying to get a fully synced node to start learning the develop with the tangle. My first month VPS is about to run out. I will not be renewing.

**Comment by lekanovic** [comment]
Try to ask questions on the Iota slack channel, there are a lot of people that can help out

**Comment by tpoxa** [comment]
Slack invitation link doesn't work also.

**Comment by mostaruk** [comment]
@tpoxa https://join.slack.com/t/iotatangle/shared_invite/enQtMjkyMDQwOTk1MjQ5LWY0YmJhYjVmOTk5NTFlMjQ3NDM4NzlhMjViOGZlOTQ4NjQwZmQyOGNmMGM0M2NlMjZhMjMyMmIyNDE5OTcyMmE

**Comment by tpoxa** [comment]
@mostaruk This invite link is no longer active.
Looks like I missed first click. Can you send me please invitation link to gtpoxa @ gmail com

**Comment by mostaruk** [comment]
@tpoxa check mail

**Comment by paulhandy** [comment]
You seem to claim in #409 that you fixed #375. If you find your solution satisfactory for these, and them redundant, please close #375 and make a pull request for #409.

**Comment by asmallfurrywombat** [comment]
please send slack invite to nick.p.wharton@gmail.com as well when you get time.

**Comment by asmallfurrywombat** [comment]
btw perhaps of interest: https://medium.com/@vanderstraeten.thomas/setting-up-a-iota-full-node-from-scratch-on-digitalocean-79189fb16bfd
One of the problems you immediately run into is the recommendation to use the slack forum to find neighbors. So far none of those posted in various places on the www seem to work :(. I notice there is another issue dedicated to the Slack Link problem so i'll stop.

**Comment by mostaruk** [comment]
@asmallfurrywombat https://join.slack.com/t/iotatangle/shared_invite/enQtMjkyNzAxMzE1MDI0LWQwYzgzYjEzOTM0ZTkzNDdkNGQyYjdlYzhjZmQ4YzMzMDBmZDkzNWE3MTQ2ZTI0NTVkNWU1ZTAzMDIyZjhjZmQ

**Comment by tpoxa** [comment]
My full node all times freezes syncing. Only restart with rescan option helps for a while. After milestones synced in few minutes milestone delta becomes growing. No any error logs or so. Which information I need to provide to help developers to solve this problem? This problem stops me from further development for IOTA.

**Comment by alon-e** [comment]
@tpoxa see #428

**Comment by ALEX778899** [comment]
Hi @paulhandy, in https://github.com/iotaledger/iri/issues/375 I described my workaround, you can close the issue after you'll fix the problem in the next release.
Thanks for the wonderful work you're doing
Regards

**Comment by fatihayyildiz** [comment]
Hey guys, can you share slack invite link to register group.Thanks
