### ISSUE TITLE
iri take about 30 minutes to start sync after reset

### ISSUE THREAD

**Issue by avihaiandroid** [iotaledger/iri#454]
iri take about 30 minutes to start sync after reset and until then the iri go back to 24,300

**Comment by H3npi** [comment]
Could you provide some more infos, please?
Which OS are you running?
How many RAM do you have?
Which IRI Version are you running?
What do you mean with "reset"?

**Comment by avihaiandroid** [comment]
I gave 10GB of ram for the iri (use only 5)
My server specs:
Ubuntu 17.04
Four cores
12 GB
300 GB 100% SSD
100 Mbit/s
iri version 1.4.1.4 (last dev)
reset: After i stop the proccess and start him again

**Comment by pompomJuice** [comment]
32 Xeon Cores with 128GB ram & SSD.

Same story. Node takes forever to start up and accept wallet connections.

**Comment by avihai-developer** [comment]
Fixed in V1.4.1.7
