### ISSUE TITLE
--remote: Define who can access, and disable getNeighbors

### ISSUE THREAD

**Issue by domschiener** [iotaledger/iri#46]

**Comment by france193** [comment]
Hi @domschiener I understand how to enable remote connection to my full-node (--remote to the script that runs the process), then I understand how to limit some api (putting some api to limit). But how to define remote authentication on iri.ini file? And then.. How I had to do the password hash? And how to send authentication to the remote node before to do requests? 
Thank you!

**Comment by jakubcech** [comment]
We're looking at this more holistically here:
https://github.com/iotaledger/iri/issues/306
