### ISSUE TITLE
Missing: Comments / UML / FlowChart / PseudoCode

### ISSUE THREAD

**Issue by kevinley** [iotaledger/iri#461]
Me, and probably thousands of other **studying developers**, want to get the picture of the project.

There is one big problem, there are no comments in the code at all, I can't find any UML, or flowchart or pseudocode.. in short we have to **try to understand the code the hard way**, extremely time-consuming, probably impossible due to our own lives, projects, etc.. (at least for me).

_**Comments/UML/FlowChart/PseudoCode is a necessity!**_
If you want fast adoption, put your efforts in maintaining your code.
Sorry if I am too harsh, I understand that you have lots of work to do! 
But still this issue has a right to exist.

**Comment by kevinley** [comment]
@Come-from-Beyond 
@domschiener 
@th0br0

**Comment by GhostTyper** [comment]
You "thumbs up" your own issue? Really?

https://www.youtube.com/watch?v=VnT7pT6zCcA

How about you make all this stuff and contribute them to the project, while you 'learn the code the hard way'?

**Comment by kevinley** [comment]
@GhostTyper Why don't you tell GitHub they should make it impossible to like one's own content (hate the system, not the player) and apparently given the fact that you care about that: you have way more time on your hands than me, feel free to make something useful with it .

**Comment by th0br0** [comment]
I have removed @GhostTyper's issue because it was not contributing to the discussion and was just trolling.

@kevinley we are working on more exhaustive documentation at the moment.

**Comment by kevinley** [comment]
@th0br0 Gr8!

**Comment by GhostTyper** [comment]
@kevinley There are situations where you can give your own comment additional depth with a reaction - so the system is just fine here. However, just to add weight to the own issue isn't one of them.

BTW: Opening an issue which will effectively change nothing and just bother the devs  because they already know the situation really shows, how many spare time you have.
