### ISSUE TITLE
Storing trinary in byte

### ISSUE THREAD

**Issue by eaigner** [iotaledger/iri#467]
Please correct me if I'm wrong, but the `Converter` uses `int[]` for everything when converting trinary. 

- Trits only have 3 values they could be stored in an 8 bit `byte[]` instead of a 32 bit `int[]`
- Trytes have 27 values and could also be stored in `byte[]` instead of `int[]`

Wouldn't this save quite some memory?

**Comment by mjollnir14** [comment]
Sometimes it's better to use less CPU cycles than save some memory. Might be their goal by choosing int. (I'm not part of the team)

**Comment by eaigner** [comment]
You can do arithmetic just as fine with `byte`, can't see a CPU overhead here. It is even cast down manually to `byte` in the code when doing ops.

**Comment by eaigner** [comment]
@GhostTyper I rather rely on benchmarks than a hunch ;)

```
BenchmarkInt8      	  500000	      3259 ns/op
BenchmarkInt       	          500000	      3421 ns/op
``

**Comment by GhostTyper** [comment]
You lack the very basic understanding of memory access and think that you can score with a not further described micro benchmark?

Even, if your micro benchmark is designed carefully (which I strongly doubt) doesn't that mean, that your results would even apply once in iri.

However, I will try to really "help" you, even if I didn't write java code in about the last 10 years. I'm literally shaking about the thought to install jdk and eclipse again:

I got your benchmark values by just putting a for loop around int and byte operations. This, however, is a bad choice for a micro benchmark in that case:

1. We need to measure "uneven" memory access. Therefore we need to test:
1. Array access
1. in a way the Jit can barely optimize.

If done properly, you get results in this ratio (smaller is better):

```
byte: 2627959 ns. (-64)
int:  1146634 ns. (-64)
```

You can see, the whole source-code here. I've put comments in, so you may learn something:

```
public class PerfTest {
	public static void main(String[] args) {
		// Our test-Arrays. The byte[] will need less memory. 
		byte[] bArray = new byte[] { 16, 13, 22, 51, 32, 1, 0, 21, 42, 63, 22, 63, 13, 42, 12, 63, 11, 25, 8, 4, 23 };
		int[] iArray = new int[] { 16, 13, 22, 51, 32, 1, 0, 21, 42, 63, 22, 63, 13, 42, 12, 63, 11, 25, 8, 4, 23 };
		
		byte bResult = 0;
		int iResult = 0;
		int position = 0;
		
		long start = System.nanoTime();
		
		// 500000 iteration(s) for the byte test.
		for (int counter = 0; counter < 500000; counter++)
		{
			// You get an additional difficulty for the JIT compiler to optimize the memory access when you comment this in.
			// This is because resolving position then isn't trivial anymore. Ofc, add or remove on both tests.
			//position = (position + 13) % 17;
			
			// Here the compiler and therefore the cpu has to take care of additional data, when retrieving the values from ram and putting them into
			// a register. Also the data need to be aligned, if the platform doesn't support byte wise memory access.
			bResult += bArray[position] + bArray[position + 2] + bArray[position + 4];
		}
		
		System.out.print("byte: " + (System.nanoTime() - start) + " ns."); // Time will be taken before the print call.
		System.out.println(" (" + bResult + ")");  // Print a checksum to see, if both benchmarks came to the same result.
		
		position = 0;
		
		start = System.nanoTime();
		
		// 500000 iteration(s) for the int test.
		for (int counter = 0; counter < 500000; counter++)
		{
			// You get an additional difficulty for the JIT compiler to optimize the memory access when you comment this in.
			// This is because resolving position then isn't trivial anymore. Ofc, add or remove on both tests.
			//position = (position + 13) % 17;
			
			// Here values are aligned perfectly for retrieving and don't need to be cleaned up or moved.
			iResult += iArray[position] + iArray[position + 2] + iArray[position + 4];
		}
		
		System.out.print("int:  " + (System.nanoTime() - start) + " ns."); // Time will be taken before the print call.
		System.out.println(" (" + (byte)iResult + ")"); // Print a checksum to see, if both benchmarks came to the same result.
	}
}
```

**Comment by eaigner** [comment]
Ok, seems to be JVM specific. Thanks for reminding me that Java is shit and should not be used in any circumstance for anything 👍

**Comment by mjollnir14** [comment]
That's not JVM specific, used to know that back then in C language

**Comment by eaigner** [comment]
Dude... i just tested the exact snippet in Go and it makes ZERO difference compared to my first bench.

**Comment by GhostTyper** [comment]
LUL, you even didn't use Java? I will never never be able to get rid of that Ask toolbar. (Just a joke.)

However, if Go is equally fast (or even faster) with "byte"s, then it isn't usin' real bytes and it's tricking you - or even worse, your code is just wrong.

@mjollnir14 is right, it's just about memory access and how the system works. Even if you optimize your code in assembler you would see these differences, as long as your use case doesn't allow for some tricks you can use in assembler which the JIT doesn't see.

If you post your Go code, I may look over it tomorrow for the sake of competition. Just because such statements trigger me.

However, now that this is clearified in case of Java, you can resolve the issue.

**Comment by eaigner** [comment]
No thanks, I think I had quite enough of your wonderful personality ;)

**Comment by GhostTyper** [comment]
ur welcome. :kiss:
