### ISSUE TITLE
iri-1.4.1.6 produces very high loadavg when many clients use it.

### ISSUE THREAD

**Issue by GhostTyper** [iotaledger/iri#472]
I'm operating the light wallet node node.lukaseder.de. This node has an avg of 350 clients connected and is therefore one of the most used nodes out there.

Since I updated the node to IRI 1.4.1.6 the loadavg of the linux system jumped from 1.5-3 to ~12 after iri booted and synced up. (I consider iri is bootin', while the milestones reported are still 243000.) However, while iri is bootin' the reverse proxy in front of it refuses connections (or when made manually forwards them to another synced node) to not stress iri further.

When I tell the reverse-proxy to forward all requests to other nodes (and therefore effectively not passing requests to my local iri installation) the system load is "back to normal". When the traffic gets forwarded to iri again, the load increases again.

The system configuration has not been changed and the clients seem to behave the same. There are no other virtual machines with significant load on that host.

You can see some analysis done here: https://www.youtube.com/watch?v=K1G4lEz33t8

You can see the current statistics of my node here: https://iota.lukaseder.de/load.html (The last diagram on the page.)

**Comment by Pomyk** [comment]
Load average doesn't say much, can you add cpu diagram? Machine wasn't updated for meltdown?

**Comment by GhostTyper** [comment]
The system configuration has not been changed and therefore also not updated for meltdown. There were no firmware updates, updates to the host system or kernel updates of the guest linux system.

The behaviour of 1.4.1.6 you see in the video (there you can see also CPU%) while clients aren't allowed to connect is very close to the behaviour of 1.4.1.4 while clients could connect.

loadavg ofc says much, especially when the load profile hasn't changed. Someone could just start threads producing many disk i/os or doin' other things CPU% wouldn't show. However CPU% (just in case you don't want to watch the video) has also changed from 100-400% (1-4 cores) to 800-1200% (and therefore reached the now 12 cores configured in the vm). If I need to guess, most part of the high loadavg comes from cpu utilization.

If you really require CPU% for your analysis, I will implement it. I would also temporarily go back to 1.4.1.4 to just prove that CPU% has also changed, if you don't trust my memory. However it would be a huge effort to do this, because it leads to another downtimes and maybe other problems 1.4.1.4 brings with itself.

If a dev wants to analyze the problem, I can reroute my traffic to an address they give me for a temporary test. However the node should be synced fully and then also broadcast the changes the users made via the api to the iota network.

**Comment by hans0r** [comment]
I've noticed the same CPU usage as @GhostTyper.
Since version 1.4.1.6 my public node has doubled the load. Kernel patch is since 1.4.1.6 installed but not on the host other systems hasn't any big performance issue with the patched kernel, if so only 1-3% and not 20-50%. It's possible for me to change the version back to 1.4.1.4 if you want. Clients connected to my node differ between 60-90. 

![iri](https://user-images.githubusercontent.com/34567126/34791547-99b27050-f645-11e7-933f-fccd32517682.png)

**Comment by GhostTyper** [comment]
It seems like the current 1.4.1.7-RC does solve this problem. I will watch this and close this ticket in 2 days or so, if that behaviour doesn't come back.

**Comment by GhostTyper** [comment]
There were no problems the last days, so I will close this ticket now. Thanks for IRI-1.4.1.7.
