### ISSUE TITLE
Add a way for applications to determine if a node is operating with `--testnet`

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iri#473]
As an applications developer, it would be convenient if I only had to configure applications for testnet mode in one place (i.e., the IRI node).

For example, if the IRI node added a `testnet` flag to the output from `getNodeInfo`, then applications could use that to determine whether to configure themselves for testnet automatically (calibrate min weight magnitude, etc.).

<em>Note: this is a dependency for https://github.com/iotaledger/iota.lib.py/issues/24 </em>

**Comment by mdsantosdev** [comment]
+1

**Comment by alon-e** [comment]
this is actually available already:
in `appName`, when you run w/ `--testnet` the name changes to: `IRI Testnet` [IRI.java](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/IRI.java#L29)

this is leveraged in the GUI Wallet [here](https://github.com/iotaledger/wallet/blob/7bdb07cc55eb066b0d80acb9de6a327bb867ae6d/ui/js/ui.update.js#L121)
try running a local node in testnet mode & connect the wallet to it.

**Comment by todofixthis** [comment]
Hey @alon-e thanks for the info.  If that's the officially-supported way to check for testnet mode, then PyOTA will follow suit (:
