### ISSUE TITLE
Make a reasonably limited remote API the default

### ISSUE THREAD

**Issue by ralfr** [iotaledger/iri#474]
IRI 1.4.1.6 introduced a new API command (14265) `setApiRateLimit`. Many of the current full node ops updated by merely replacing their jar file. They likely did not add the new command to `REMOTE_LIMIT_API` in their config files.

A random curl against 100 public full nodes found more than 70% allowing remote execution of `setApiRateLimit`. 

As far as we understand, this config setting "only" impacts the rate with which transactions are persisted to the nodes database.  However, any commands introduced with future versions, if handled in the same way, might allow more harm by remote executers.

Wouldn't it make sense to introduce a completely locked-down-by-default approach with the next version of IRI and only allow remote execution of explicitly listed commands?

This is based on a lengthy discussion I've had with `nuriel77` on the IOTA Slack.

**Comment by cyclux** [comment]
On this occasion I'd like to remember for https://github.com/iotaledger/iri/issues/306

**Comment by paulhandy** [comment]
Good point, Ralf

**Comment by MarcoGlauser** [comment]
It would be nice if the ip range for the limited calls could be configured as well. This would make it possible to also allow the limited calls from a private ip address like 10.1.1.24.

**Comment by jakubcech** [comment]
Related to #306, will be addressed there. Thanks!
