### ISSUE TITLE
Docker image building process takes a lot of time

### ISSUE THREAD

**Issue by ahab94** [iotaledger/iri#478]
Docker image building process takes a lot of time, depending on the issue it can take few minutes. And everytime we build an image, say for development purposes, building image in quick successions is not viable. It will build the image, pull the dependencies, each of them every time we execute `docker build`. Which takes away the dev testing ease the docker can provide. 

I will be contributing, basically enhancing the flow using native maven tools.

**Comment by jakubcech** [comment]
We made improvements to docker building in #744 - thanks!
