### ISSUE TITLE
2.5.6 + 1.4.1.6 cannot login (worked on same box with 1.4.1.4)

### ISSUE THREAD

**Issue by vsatmydynipnet** [iotaledger/iri#482]
Since updating to 1.4.1.6 i can not login anymore. Server is fully synced and runs without error in syslog.

**Comment by mlouielu** [comment]
What is "can not login anymore"? What is your environment to connect to server?

Can you use something like `curl http://localhost:14600 -X POST -H'Content-type: application/json' -H'X-IOTA-API-VERSION: 1' -d '{"command": "getNodeInfo"}' | python -m json.tool` to check your server is on?

**Comment by rajivshah3** [comment]
Try restarting your node. I've been having an issue where the API port stops working but the rest of IRI keeps running like usual. I think @th0br0 said it was a `getBalances` race condition

**Comment by vsatmydynipnet** [comment]
Everything looks good and restart done more than one time.

{
    "appName": "IRI",
    "appVersion": "1.4.1.6",
    "duration": 0,
    "jreAvailableProcessors": 4,
    "jreFreeMemory": 1271957984,
    "jreMaxMemory": 3934781440,
    "jreTotalMemory": 3934781440,
    "jreVersion": "1.8.0_151",
    "latestMilestone": "WLEAUWMIAHYMTWZOMTBGGFLHYZPBGVNTWWSBIQDNETTASGFEANVQIMYRMJVPEHAQ9IFJJLOVLMSX99999",
    "latestMilestoneIndex": 329190,
    "latestSolidSubtangleMilestone": "GLOO9G9BRHDJBITXMMOCMQMNUWFVHUGHVSLZTTUTIMIJFNCFONGMDXKQUBOTOZXCSIPCVAHEQTPF99999",
    "latestSolidSubtangleMilestoneIndex": 326860,
    "neighbors": 6,
    "packetsQueueSize": 0,
    "time": 1516180683094,
    "tips": 8148,
    "transactionsToRequest": 0
}

As mentioned, 1.4.1.4 worked with login. But was unable to attach addresses.

**Comment by mlouielu** [comment]
Your latest solid subtangle index maybe not sync to lastest milestone index?

**Comment by vsatmydynipnet** [comment]
This existed in 1.4.1.4 too. Says sometime problem to update. But i wa reading this happened to others too. After restart ist says "not synced" when trying to login. After a few minutes it tries to login, but never ends saying "logging in". If a stop the daemon, it disconnects the time the socket is closed.

Very strange.

**Comment by shrewm** [comment]
same problem for me with 2.5.6 + 1.4.1.6 and 2.5.6 + 1.4.1.7.
windows 10 x64

**Comment by vsatmydynipnet** [comment]
with 1.4..7 it even gets worser.

- iri: starts faster, and recognizes faster that node is fully synced.

- wallet: node info shows correct data of iri.login does not work, but ends with connection refused mostly. atter this node info doesnt work too. (connection refused.). close the wallet, restart, game beginns again with same ending.

- iri and wallet on debian 

I have the feeling that it is better to shutdown the server and give it another try after auto-neighbor discovery is implemented and one is able to use a wallet which works most of the time. After weeks of iri operation i was only able to login with .1.4.1.4 , but attaching addresses never worked. I like he IOTA idea, but at the moment it looks like its pretty unusable.

**Comment by shrewm** [comment]
@vsatmydynipnet can you try to run IRI with the --revalidate switch? I let it run for a few hours until I saw the workload of my harddrive dropped, stopped iri and started it again without the revalidate switch. Since then I can connect with the wallet.

**Comment by vsatmydynipnet** [comment]
This was uncool. --revalidate mentioned a lot of stuff to delete and letting it run, never got synced again. I restarted iri, it updated the Last Milestone index to 333767, is working with the 4 neighbors, but doesn't reach synced state again.

**Comment by nuriel77** [comment]
@vsatmydynipnet 

Regarding the login:

1. Are u running the wallet on the same node as IRI?
2. If not, do you have the `--remote` option enabled? (Or e.g. `API_HOST = 0.0.0.0` in ini file?)
3. Firewalls? (ufw/iptables?)

Regarding sync:
I haven't had much success with `--revalidate` tbh. I think what works for most over the past months was to download a fully sycned db, and then restart IRI without revalidate nor rescan flag.

**Comment by vsatmydynipnet** [comment]
Running Wallet and ir on same Debian sysstem, till something is working. No iptables restrictions on localhost. As mentioned, with 1.4.1.4 it worked to login, but couldn't attach addresses. since 1.4.1.6 no login, 1.4.1.7 made it more bad. 

Since --revalidate  Latest Milestone Index upgrades - now on 335013, but node doesn' get in sync anymore. 

I lost 3 of my neighbors, probably they shutdown their servers due to all of these problems, making iri and the wallet unusable, but still have 3 good neighbors. If anyone has one or two slots for me, they are appreciated. (Running Debian, 4 CPU, 12GB RAM, 400GB HDU, on Enterprise grade connection with static IP) . I have to admin, actually trying out IOTA is no fun.

**Comment by vsatmydynipnet** [comment]
We finally have decided to shutdown the node. Even as company with a long term view on thingsm in business since 1985, we do not see any possibility for implementing IOTA in one of our projects within 2 years. After weeks of testing, we only was able to login with one version. We never could attach addresses to the tangle. Sill believing in the great idea, ready to retest IOTA if it is on the way to be usable and implement auto neighbor discovery. Till now, a good idea, but practically unusable. I am not sorry to loose the weeks we tried it, more sorry that a great concept maybe falls out of the interest of users.

**Comment by nuriel77** [comment]
@vsatmydynipnet I wonder if you ever sought for help on IOTA's Discord #fullnodes channel. 

- IOTA has an (external) software for auto-neighbor discovery (nelson) with its own channel for support.
- I am guessing you didn't manage to attach to tangle due to having it disabled in your configuration file.
- There are thousand of full node owners running functioning nodes.

Sorry to hear your about experience, but I think you could have received a lot of useful help on Discord/Slack channels.

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
