### ISSUE TITLE
Sudden drop in totalTransactions 

### ISSUE THREAD

**Issue by gjeee** [iotaledger/iri#491]
In the log-output below you can see that the number of totalTransactions suddenly drops from 9130701 to 8984951. I was told that this number is an estimate. But even then how can an estimate change so big?? My node was all the time synced and healthy. FYI you can get this number by calling TransactionViewModel.getNumberOfStoredTransactions(tangle)

`Jan 19 23:09:59 xxxx.contaboserver.net java[8901]: 01/19 23:09:59.363 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 73 , toReply = 0 / totalTransactions = 9130685`

`Jan 19 23:10:09 xxxx.contaboserver.net java[8901]: 01/19 23:10:09.365 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 72 , toReply = 0 / totalTransactions = 9130693`

`Jan 19 23:10:19 xxxx.contaboserver.net java[8901]: 01/19 23:10:19.369 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 70 , toReply = 0 / totalTransactions = 9130701`

`Jan 19 23:10:29 xxxx.contaboserver.net java[8901]: 01/19 23:10:29.374 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 70 , toReply = 0 / totalTransactions = 8984951`

`Jan 19 23:10:39 xxxx.contaboserver.net java[8901]: 01/19 23:10:39.375 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 73 , toReply = 0 / totalTransactions = 8984974`

`Jan 19 23:10:49 xxxx.contaboserver.net java[8901]: 01/19 23:10:49.378 [pool-2-thread-2] INFO  com.iota.iri.network.Node - toProcess = 0 , toBroadcast = 0 , toRequest = 73 , toReply = 0 / totalTransactions = 8984986`

**Comment by gjeee** [comment]
hmmm i checked out the FAQ of RocksDB and this could explain the wildly fluctuating numbers:

> Q: Why GetIntProperty can only returns an estimated number of keys in a RocksDB database?

> A: Obtaining an accurate number of keys in any LSM databases like RocksDB is a challenging problem 
> as they have duplicate keys and deletion entries (i.e., tombstones) that will require a full compaction in 
> order to get an accurate number of keys. In addition, if the RocksDB database contains merge  
> operators, it will also make the estimated number of keys less accurate.

why not use a number in memory which initializes on startup and then increments on each insert statement??

**Comment by jakubcech** [comment]
Thanks, see https://github.com/iotaledger/iri/issues/446#issuecomment-354609702 for more details.
