### ISSUE TITLE
API Sync status call

### ISSUE THREAD

**Issue by Fabryprog** [iotaledger/iri#494]
Hello,
there is any undocumented api call to know sync status? 

I have a iri node with 6 valid neighbors but i haven't any sync!

**Comment by nuriel77** [comment]
Did you try to use getNodeInfo?
e.g.:
```sh
curl -s http://localhost:14265   -X POST  -H 'X-IOTA-API-Version: 1' -H 'Content-Type: application/json'   -d '{"command": "getNodeInfo"}'| python -m json.tool|egrep "latestSolidSubtangleMilestoneIndex|latestMilestoneIndex"
```
This will produce two numbers which should be the same if your node is fully synced. You can find botbox channel on discord to verify the numbers are the same. Or compare to what most nodes in this list have for milestone: http://iota.dance/nodes

**Comment by Fabryprog** [comment]
This is the output:

```
{
  "appName": "IRI",
  "appVersion": "1.4.1.6",
  "jreAvailableProcessors": 4,
  "jreFreeMemory": 59059016,
  "jreVersion": "1.8.0_151",
  "jreMaxMemory": 1838153728,
  "jreTotalMemory": 822083584,
  "latestMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "latestMilestoneIndex": 243000,
  "latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
  "latestSolidSubtangleMilestoneIndex": 243000,
  "neighbors": 6,
  "packetsQueueSize": 0,
  "time": 1516616529936,
  "tips": 0,
  "transactionsToRequest": 0,
  "duration": 0
}
```

I grep neighbors form https://iotanode.host/

**Comment by nevrrmind** [comment]
@Fabryprog These nodes are for the Light Wallets, and not meant for you as a neighbor. ;)

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
