### ISSUE TITLE
LatestSubtangleMilestone stucking after getTransactionsToApprove call

### ISSUE THREAD

**Issue by mstrewe** [iotaledger/iri#499]
The LatestSubtangleMilestone getting stucked in version 1.4.1.7. We discussed that in #fullnode discord channel. First idea was a ddos api attack but was not. I dumped every call on my node and realized, that after the first call of getTransactionsToApprove the subtangle milstone gets stucked. 

TCP dump attached. You can analyse the file with wireshark. 
[tcpdump.txt](https://github.com/iotaledger/iri/files/1662881/tcpdump.txt)

**Comment by michi6383** [comment]
same here.

**Comment by nuriel77** [comment]
https://github.com/iotaledger/iri/pull/498

**Comment by GalRogozinski** [comment]
#501
