### ISSUE TITLE
IRI REMOTE AUTH

### ISSUE THREAD

**Issue by pcooperuk** [iotaledger/iri#500]
Hi,
From my testing, if I enable REMOTE_AUTH in IRI
it works ok, however, it would be good if I could restrict this to ONLY the Light node port (usually 14265).

because currently if I do enable it... nelson cant connect to manage  neighbors and even if it could the neighbors cant connect unless they use the auth details.

From what I can see this means enabling REMOTE_AUTH is only if you plan to run your own IOTA tangle, not connected to IOTA true mainnet in any way (unless im wrong, could be, but testing indicates this to be so)

If the REMOTE_AUTH can be configured to be only on the Light weight port 14265, then you can have a Node that lightweight nodes can connect if they have the REMOTE_AUTH login, but the node will also perfectly communicate with the network.

currently REMOTE_AUTH seems a mute point as its all or nothing and ALL simply means no IOTA.

I'd be happy to clone and implement this, but I do not want to be running a separate IRI code chain, so more interested in knowing if this gets done, would it me included in the main branch (provided tested happy)

**Comment by nuriel77** [comment]
@pcooperuk as far as I know the REMOTE AUTH only wraps the API port:

https://github.com/iotaledger/iri/blob/27aae832094f91276ebf41544f4f7cb5f14be0ab/src/main/java/com/iota/iri/service/API.java#L129

https://github.com/iotaledger/iri/blob/27aae832094f91276ebf41544f4f7cb5f14be0ab/src/main/java/com/iota/iri/service/API.java#L1009

The peering ports are not going to require REMOTE AUTH if you enabled it.
If nelson cannot connect in to the API port, and considering this is Basic Auth, did you try to provide nelson with the IRI API url in the format:
```
http://user:password@localhost:14265
```

**Comment by pcooperuk** [comment]
Thats how I though it would work..

Had not dug too much into Nelson connecting, just knew that as soon as i enabled no neighbors were appearing at all, so also assumed that if the.  Had 2 entires in the the neighbors iota.conf, but there was no communication at all between them.
Will try the Nelson basic auth and see how it goes.

Thanks
