### ISSUE TITLE
ERROR com.iota.iri.network.Node - 'http://x.xxx.xxx.x:14265' is not a valid uri schema or resolvable address.

### ISSUE THREAD

**Issue by marcoliverhofer** [iotaledger/iri#509]
Hi Everyone,

I setup IRI on a Debian 9 VPS. Everything seem to work fine, except that in the beginning, I receive ERROR messages for all the neighbor nodes that I have specified in my .ini file.

That said, my NODE is not registered with my neighbors. So is that what this error message is trying to tell me !? I always thought, at least the NODE should be able to reach my neighbors, even if they haven't put me up in their "neighbor list".

I can reach via ping all the addresses specified in my neighbor list. So they are up and running and my system can reach them.

I traced it back to the URI Java class object that is responsible for validating the URI I give the process, though that is where I'm stuck.

Any ideas ?

Thanks,

**Comment by nuriel77** [comment]
@marcoliverhofer this scheme `http://x.xxx.xxx.x:14265` is referring to the API port of IRI (e.g wallet connections). 

To specify neighbors you need to use the scheme `tcp://some-address.com:12345` or `udp://some-address.com:12345` depending if this is a TCP or UDP port, and the correct port number of course.

You cannot arbitrarily add neighbors. Peering is mutual.

**Comment by marcoliverhofer** [comment]
Duh, yeah, of course...that was just really stupid of me. Talking about "not seeing the forest for all the trees". Completely missed that. Thanks.
