### ISSUE TITLE
 Migrate build system to Gradle

### ISSUE THREAD

**Issue by fooock** [iotaledger/iri#514]
I think that using Gradle can simplify the development of custom builds and another useful things. For example, Gradle can help if we need to modularize the project creating multiple submodules for hash, replica, api, services, storage etc. 

I can help in the migrating proccess. What do you think?

**Comment by PatrickHuetter** [comment]
+1

**Comment by GalRogozinski** [comment]
I am more of a Maven guy and not so familiar with Gradle.

But as far as I know, up to Java 8 OSGI was mainly used to create modules (see eclipse project). JBOSS achieved modularity by implementing class loaders for libraries.

Anyhows, I currently think that the best way to achieve modularity for iri is to migrate to java 9.
I see no reason to change the build system.
