### ISSUE TITLE
IRI 1.4.2.1 build not on Docker Hub (as tag :v1.4.2.1)

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/iri#517]
The IRI build 1.4.2.1 is not available under its tag on the Docker Hub, because the build failed.
![image](https://user-images.githubusercontent.com/1385611/35499243-d7b718a2-04d1-11e8-8a8b-f05f5b81c8b7.png)

While the `latest` build is `1.4.2.1`, a separate tag for that specific version should also exist.

**Comment by alon-e** [comment]
thanks!
this failed due to docker file becoming stale,
part of https://iotaledger.atlassian.net/projects/IRI/issues/IRI-11
