### ISSUE TITLE
Full Node ААААА

### ISSUE THREAD

**Issue by PVBKXWYUMYTJ** [iotaledger/iri#519]
Я мучался 30 минут и получилось создать ноду где-то на 80%.
Сделайте попроще , чтобы ноды сами себя находили. Это просто нереально вручную балансировать себя и соседей.

**Comment by snowlove** [comment]
https://github.com/SemkoDev/nelson.cli

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
