### ISSUE TITLE
Why MIN_WEIGHT_MAGNITUDE can't be below 13?

### ISSUE THREAD

**Issue by Cylix** [iotaledger/iri#524]
Hi,

I'm developing the iota.lib.cpp library and we configured a local private network in order to create a stable test environment that we can deploy on any integration server (Travis / Appveyor).

The problem is that we start to have a huge amount of tests (> 500), including many tests doing some local or remote proof of works.
That leads our build to slow down over the time and we reach a limit where the normal build takes roughly 30~40mn and the coverage builds lasts more than 50mn, which is above the maximum build duration set by travis (leading our build to be set).

Our primary reaction is to decrease the weight magnitude in order to fasten the proof of work. We are currently at 14 on our private local testnet, and we are going to make it down to 9 in order to have a fast build that can complete within 5~10mn.

However, after checking on IRI, it seems that if the magnitude is below 13, it is reset to 13: [here](https://github.com/iotaledger/iri/blob/cb69f467744db4c52429b647824da5863c6501f3/src/main/java/com/iota/iri/TransactionValidator.java#L59).

That is not a big deal as we already monkey patch the IRI to skip the snapshot signature validation such that we can use our custom snapshot, so we can also monkey patch that part and skip that limitation.

I was just wondering two things:

* Is there any reason it can't be set below 13 besides that main network will always need to be above 13?
* If I monkey patch the code I linked above by commenting, is there any possible downside / side effect that could arise? Right now, seems that all my test suite is working fine, but quite wondering for the long term.

Thanks!

**Comment by alon-e** [comment]
>Is there any reason it can't be set below 13 besides that main network will always need to be above 13?
yes, if you look at `testnet` vs `mainnet` then the packet size is different - this is an optimization:

- if a valid transaction has at least MWM 13, then it has 13 'zero's (at least) at the end.

- the hash can be represented with (243-13) = 230 trits, which are (230 / 5) = 46 bytes.

- so we can optimize and only send 46 bytes of the hash, as the "last" 3 bytes are `0` by definition.

this is not true if MWM is lower than 13. then you need more bytes to represent the valid hashes.

streamlining testnet deployments has been merged in `dev`, and test with MWM 1 used for integration tests: fdba37a49fa6b1b73e7d283241ce8babe3fb099e 9f36496c9bec380735771c613a30048b2d254d2b
