### ISSUE TITLE
Log spammed with 'Tx traversed to find tip: x' messages

### ISSUE THREAD

**Issue by Sschot** [iotaledger/iri#525]
I'm running a Bolero node, but this seems IRI related. Now and then my IRI log get's spammed with these 'traversed' messages, hundreds per seconds. 

See this pastebin for part of my log: https://pastebin.com/tLQGYF8L

This crashes Bolero in the end because log becomes too big, i'm also not sure if IRI is still working, so much log entries doesn't sound healthy to me. Why does this happen?

**Comment by ccconv** [comment]
Have the same problem since today. I don't run Bolero though.

**Comment by rajivshah3** [comment]
These messages mean that the node is finding tips (unconfirmed transactions) that a new transaction will confirm. It seems like there was a spam attack yesterday, which could explain why there were so many of these messages.

**Comment by alon-e** [comment]
added to meta-task: https://iotaledger.atlassian.net/projects/IRI/issues/IRI-28
