### ISSUE TITLE
numberOfSentTransactions increasing

### ISSUE THREAD

**Issue by BusFactor1Inc** [iotaledger/iri#529]
I have a private test net setup and I notice the numberOfSentTransactions is constantly increasing.  

What are these transactions?  I haven't been able to send any myself due to issue https://github.com/iotaledger/iota.lib.js/issues/172.

```json
// gn
[ { address: '192.168.1.7:14600',
    numberOfAllTransactions: 0,
    numberOfRandomTransactionRequests: 0,
    numberOfNewTransactions: 0,
    numberOfInvalidTransactions: 0,
    numberOfSentTransactions: 23955,
    connectionType: 'udp' },
  { address: '192.168.1.8:14600',
    numberOfAllTransactions: 0,
    numberOfRandomTransactionRequests: 0,
    numberOfNewTransactions: 0,
    numberOfInvalidTransactions: 0,
    numberOfSentTransactions: 23955,
    connectionType: 'udp' },
  { address: '192.168.1.9:14600',
    numberOfAllTransactions: 0,
    numberOfRandomTransactionRequests: 0,
    numberOfNewTransactions: 0,
    numberOfInvalidTransactions: 0,
    numberOfSentTransactions: 23955,
    connectionType: 'udp' },
  { address: '192.168.1.10:14600',
    numberOfAllTransactions: 0,
    numberOfRandomTransactionRequests: 0,
    numberOfNewTransactions: 0,
    numberOfInvalidTransactions: 0,
    numberOfSentTransactions: 23955,
    connectionType: 'udp' },
  { address: '192.168.1.11:14600',
    numberOfAllTransactions: 0,
    numberOfRandomTransactionRequests: 0,
    numberOfNewTransactions: 0,
    numberOfInvalidTransactions: 0,
    numberOfSentTransactions: 23955,
    connectionType: 'udp' } ]
```

**Comment by BusFactor1Inc** [comment]
I'm assuming they're some kind of 'ping' or 'keep alive', but I was wondering if there was a better or more correct explanation.

**Comment by BusFactor1Inc** [comment]
I am following the instructions here on how to run my own Tangle:

https://forum.iota.org/t/running-a-node-in-isolation-how-to-work-around-the-subtangle-has-not-been-updated-yet-errors/1410/3

**Comment by alon-e** [comment]
this is part of the "Tips Requester" thread, in [Node.java#L534](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/network/Node.java#L534)
so every 5 seconds the node sends the latest milestone to all its neighbors.
