### ISSUE TITLE
ZeroMQ stops sending data

### ISSUE THREAD

**Issue by crholliday** [iotaledger/iri#530]
From time to time, and with no logged errors or messages, zeroMQ stops queuing data. I have not been able to replicate it. There is some indication that it occurs during high TPS but nothing substantive. Maybe a hook that would allow restarting the service without restarting IRI... just logging for visibility.

**Comment by michi6383** [comment]
same here.

**Comment by nuriel77** [comment]
Maybe sending heartbeats from the pub can help?
In that case, might be that an additional implementation in the sub is required: checking if those heartbeats are sent, and reconnect when they stop.

**Comment by alon-e** [comment]
@th0br0 was this fixed by #569? if so. please close.
