### ISSUE TITLE
Automatic reattachments after promoting

### ISSUE THREAD

**Issue by Qomaa** [iotaledger/iri#537]
Since yesterday (afaik), I get automatic reattachments for my transactions.

**To reproduce:**
1. Send transaction
2. Reattach immediatly
3. Promote immediatly

After promoting I can see on thetangle.org and in the wallet history, that my transaction is reattached multiple times automatically. I use my own node with "default" IRI settings, manual setup.

**Examples:**
https://thetangle.org/bundle/JFTBWATX9DFHQRDJUCQBWKTKZBVSFLYCQCKXFZSUIYBSRIXWIJHHJKCYPNJLZYCCI9PLZFHIIGLBLJULW

https://thetangle.org/bundle/ASASJE9EHDJ9LJS9NDLCK9CXUUIHFKCKRHIYAIDII9BHF9FDBIHGLIAFRULXKYIYTVJCZQDSEQPALD9QW

**Comment by mikrohash** [comment]
Might just be the community running reattachers that automatically reattach value transactions.

**Comment by rajivshah3** [comment]
Is this a bug or a feature? :trollface: 

I agree with @mikrohash , I think this is probably from the community

**Comment by Pomyk** [comment]
Reattaching every minute will just reduce confirmation rate.
