### ISSUE TITLE
Error attaching Node to IOTA Tangle

### ISSUE THREAD

**Issue by pkhutal** [iotaledger/iri#538]
Hello Team,

We are integrate IOTA wallet on Android Platform. 
The following operations we executed successfully.
1.  Seed & Adress generation
2. IOTA received on Wallet Address.

But we are not able to make the transaction from wallet (sending IOTA to another address).  It is throwing following error.

**Caused by: java.lang.IllegalAccessError: 401 {"error":"COMMAND attachToTangle is not available on this node","duration":1}**
 
We are using Host URL as  **http://iota.bitfinex.com:80** 

Could you please suggest, what we are missing.

Thank you.

**Comment by mstrewe** [comment]
You try to connect to a node which do not support attachToTangle. This command will let the node do the Prove of Work. You ether need to do the POW yourself and simply broadcast your transaction or you need a node supporting POW.

For example look at https://iota.dance/nodes and choose a POW enabled node

**Comment by pkhutal** [comment]
Thank you so much, i will try and get back!

**Comment by aashu14feb** [comment]
Hello @mstrewe
I finally able to attach a 0 value transaction to tangle with node ("https://iotanode.us:443").But when i put some amount say 1i it shows "Not enough balance error".

I am trying to send some IOTA from my one wallet to another with java implementation 
// api.sendTransfer(seed, 2, 9, 15, transfers, null, null, true);

As one of address from this seed have available balance of 1500000i .

**Comment by mstrewe** [comment]
I never used the api.sendTransfer Method. Did you ask that in development discord channel?

**Comment by aashu14feb** [comment]
No. But i got some explanation about the issue that i first need to attach to tangle to get it work. Now i am able to attach to tangle as u suggested but sendTransfer(also in JavaScript) from Wallet to Wallet is not working.

One more thing i want to ask is the android wallet suppose to give me proper balance when i enter my seed and login but it is still not working.

Could you please suggest anything on that
Thanks

**Comment by mstrewe** [comment]
@aashu14feb The Android wallet will not automatically search for your Transactions after Snapshot. This means you should create/attach some addresses until you balance show up.

**Comment by mstrewe** [comment]
@aashu14feb  I checked the API and i think you forgot the inputs:

     api.sendTransfer(seed, 2, 9, 15, transfers, **INPUTS goes here**, null, true);

Therefor you get not enough balance because there are no addresses to get the balance of

**Comment by mstrewe** [comment]
@pkhutal if your problem is solved, please close the issue

**Comment by pkhutal** [comment]
@mstrewe, yes the issue is solved. Thank you for your support!

**Comment by arjun7862** [comment]
please help me am not able to do solve this issue in java api for my android app
