### ISSUE TITLE
add trusted host config field

### ISSUE THREAD

**Issue by Fabryprog** [iotaledger/iri#541]
Hello everyone

it could be nice have a new config field to pass a trusted host for remote api

For example:
--remote-api-trusted mynode.iota.org

**Comment by alon-e** [comment]
@Fabryprog could you elaborate on your request?
does the "trusted host" have access just like `localhost`? or do you mean to only accept connections from this host? (the latter can be done w/ a workaround by setting `API_HOST` to the desired host, w/o the `--remote` flag)

**Comment by nuriel77** [comment]
If I may chime in here...
`API_HOST` also binds the API port to a specific IP on the node itself.
I believe that many users proposed such a feature to be able to provide a whitelist (hostname(s) and/or IP ranges -- CIDR notation). Those should get access like `localhost` does.
It would make deployments of IRI more adaptable to different environments.
