### ISSUE TITLE
Even with --max-peers specified, the neighbour count increases past the max allowed when neighbours are added locally

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#546]
Even with --max-peers specified, the neighbor count increases past the max allowed when added locally.

I added the same set of peers twice. It accepted the second set even though it should already have been at max. The getNodeInfo responded with a count that was double the allowed.

**Comment by footloosejava** [comment]
This seems to have died a natural death. I am closing it.

**Comment by jakubcech** [comment]
Related to #373, thanks!
