### ISSUE TITLE
mainetdb is stagnant with a fresh install and 25 top peers (there is no syncing it seems)

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#547]
I have a fully configured setup, both Bolero and iri. Bolero worked fine. Then, I cleared out Bolero and tried using iri by itself. 

Everything appears to be working .... the ports are open, the neighbors are added (25 of the top ones listed) and even the iri log looks healthy ..... except there appears to be no syncing. 

All I get is the usual log feed. The mainetdb is not growing even though the neighbours are transacting. 

Am I doing something wrong? I have re-tried several times today and yesterday with no luck. CPU usage is minimal and I have tons of free ram and a very fast network.

Here is my stdout with line numbers added all the redundant transaction messages removed:

> 2:02/19 16:11:44.406 [main] INFO  com.iota.iri.IRI - Remote access enabled. Binding API socket to listen any interface.
> 3:02/19 16:11:44.408 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.2.1
> 4:02/19 16:11:54.579 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - Initializing Database Backend... 
> 5:02/19 16:11:54.624 [main] INFO  c.i.i.s.r.RocksDBPersistenceProvider - RocksDB persistence provider initialized.
> 6:02/19 16:11:54.629 [main] INFO  com.iota.iri.network.UDPReceiver - UDP replicator is accepting connections on udp port 14600
> 7:02/19 16:11:54.630 [main] INFO  c.i.i.network.replicator.Replicator - Started ReplicatorSourcePool
> 8:02/19 16:11:54.630 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Spawning Receiver Thread
> 9:02/19 16:11:54.630 [UDP receiving thread] INFO  com.iota.iri.network.UDPReceiver - Receiver thread processed/dropped ratio: 0/0
> 10:02/19 16:11:54.633 [Thread-2] INFO  c.i.i.n.r.ReplicatorSourcePool - TCP replicator is accepting connections on tcp port 15600
> 11:02/19 16:11:54.634 [pool-2-thread-1] INFO  com.iota.iri.network.Node - Spawning Broadcaster Thread
> 12:02/19 16:11:54.634 [pool-2-thread-2] INFO  com.iota.iri.network.Node - Spawning Tips Requester Thread
> 13:02/19 16:11:54.635 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Spawning Neighbor DNS Refresher Thread
> 14:02/19 16:11:54.635 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Checking Neighbors' Ip...
> 15:02/19 16:11:54.635 [pool-2-thread-4] INFO  com.iota.iri.network.Node - Spawning Process Received Data Thread
> 16:02/19 16:11:54.636 [pool-2-thread-5] INFO  com.iota.iri.network.Node - Spawning Reply To Request Thread
> 19:02/19 16:12:07.515 [main] INFO  com.iota.iri.IRI - IOTA Node initialised correctly.
> 28:02/19 16:13:25.875 [XNIO-1 task-1] INFO  com.iota.iri.service.API - Adding neighbor: 
....
> 223:02/19 16:41:54.985 [pool-2-thread-3] INFO  com.iota.iri.network.Node - Checking Neighbors' Ip...
> 224:02/19 16:41:55.059 [pool-2-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address ....

**Comment by cwarner818** [comment]
When you say "the neighbors are added (25 of the top ones listed)" did those neighbors add you back as well? It's a two-way procedure.

**Comment by footloosejava** [comment]
> When you say "the neighbors are added (25 of the top ones listed)" did those neighbors add you back as well? It's a two-way procedure.

I did not know that. I need to manually request that nodes add my node in order to sync the database? 

If anyone is inclined to help: how does a Bolero node setup get synced? and/or how do I setup my iri so that it does in essence what Bolero is doing without manually tethering?

**Comment by luca-moser** [comment]
@footloosejava 
Bolero uses [Nelson](https://github.com/SemkoDev/nelson.cli) to do automatic tethering. If you only use IRI alone, you need to manually tether neighbors.

**Comment by gjeee** [comment]
can you close the issue @footloosejava since i think your issue is clear now right? to keep things tidy :-)
