### ISSUE TITLE
interruptAttachingToTangle may interrupt other's attachToTangle process

### ISSUE THREAD

**Issue by chenwei-tw** [iotaledger/iri#553]
Because ```interruptAttachingToTangle``` doesn't take any argument (e.g. specific transaction trytes to interrupt), anyone using this API can make a full node unable to do PoW.

https://github.com/iotaledger/iri/blob/2e0d1c38b18f196fec727acacff3b3fdf0e06868/src/main/java/com/iota/iri/service/API.java#L301-L304

* ```interruptAttachingToTangle``` should be default in ```--remote-limit-api```, if this full node enable ```attachToTangle``` API

* Assumed iri is able to do multiple PoW task at the same time, what behavior is expected when ```interruptAttachingToTangle``` called?

**Comment by chenwei-tw** [comment]
Assumed iri enable doing multiple PoW task at the same time, what behavior is expected when ```interruptAttachingToTangle``` called?

**Comment by jakubcech** [comment]
We'll have a look at restricting calls in https://github.com/iotaledger/iri/issues/306
