### ISSUE TITLE
Full Nodes unable to sync

### ISSUE THREAD

**Issue by Mooonzx** [iotaledger/iri#563]
Hi there, I am currently working on a project regarding IOTA.

I have set up 3 VMs with a Full Node IOTA TESTNET. These three VMs are able to ping one another.
Is it possible for these three nodes to be synced? Because I have not been able to do so.

VM Settings:
RAM: 4000MB
Hard Disk Virtual Size: 30 GB
Network: Bridged Adapter

When I tried to log in the three nodes at the same time, it always ends up with the error, "Not Sync".

I am using IOTA Wallet 2.5.7 and IRI version 1.4.2.2 .

The following are my node info:

appName IRI
appVersion 1.4.2.2
jreAvailableProcessors 1
jreFreeMemory 126212928
jreVersion 1.8.0_151
jreMaxMemory 977141760
jreTotalMemory 977141760
latestMilestone 999999999999999999999999999999999999999999999999999999999999999999999999999999999
latestMilestoneIndex 338000
latestSolidSubtangleMilestone 999999999999999999999999999999999999999999999999999999999999999999999999999999999
latestSolidSubtangleMilestoneIndex 338000
neighbors 2
packetsQueueSize 0
time 1519869692135
tips 0
transactionsToRequest 0

**Comment by nuriel77** [comment]
@Mooonzx did you connect any of your nodes to "external" neighbors? Or are they only connected to each other?

**Comment by Mooonzx** [comment]
@nuriel77 I did not connect my of my nodes to "external" neighbours I am working on the Testnet version. Am I supposed to do so?

**Comment by nuriel77** [comment]
@Mooonzx sorry, I read too fast. Please disregard.
I don't have experience with setting up a testnet, though I think you're supposed to run a local Coordinator, https://github.com/schierlm/private-iota-testnet

**Comment by Mooonzx** [comment]
@nuriel77 Alright, I will try this and update my status!

**Comment by AlexWei2013** [comment]
same problem, waiting  @Mooonzx  thanks

**Comment by GalRogozinski** [comment]
Since this issue is more befitting to https://helloiota.com/ or Discord I am closing it.
