### ISSUE TITLE
Nasty bug results in bad packets and repeat packets to/from TCPNeighbors

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#564]
I'm not good at pull requests. I hope this makes sense to the devs here.
2 PROBLEMS ...

PROBLEM 1
=====================================
DatagramPacket returns the backing byte[] ... but that gets changed when new data is written. Yet it is used in both these threads and each time, the data is copied-in instead of overwritten. It is synchronized, so access is OK, but once it gets to the neighbor, the same problem happens as in PROBLEM 2. The TCPNeighbor caches the wrapped backing byte[] and then all the queued data in the TCPNeighbor sendQueue has the ... same backing data array .... and worse ... it can change while in use in all neighbors.

```
private Runnable spawnReplyToRequestThread()
                             and
private Runnable spawnBroadcasterThread() 
```

In the final loop that sends it, the data is not 'written' to the packet. Instead it is copied onto the backing array:

```
        synchronized (sendingPacket) {
            System.arraycopy(transactionViewModel.getBytes(), 0, sendingPacket.getData(), 0, TransactionViewModel.SIZE);
            Hash hash = transactionRequester.transactionToRequest(rnd.nextDouble() < P_SELECT_MILESTONE);
            System.arraycopy(hash != null ? hash.bytes() : transactionViewModel.getHash().bytes(), 0,
                    sendingPacket.getData(), TransactionViewModel.SIZE, REQUEST_HASH_SIZE);
            neighbor.send(sendingPacket);
        }

```
Probably better to 'set' the data in rather than use the same backing byte[] and then pass it around -- just make some fresh DatagramPacket's in Node instead of reusing such a lightweight container.

The problem would not be so big if the setData method of DatagramPacket were used ... because that would actually replace the backing byte[].

PROBLEM 2
======================================
In com.iota.iri.network.Node, all the Neighbors (TCP and UDP) are called here:

LINE 518
private Runnable spawnTipRequesterThread() {
        ... stuff ...
                    System.arraycopy(transactionViewModel.getHash().bytes(), 0, tipRequestingPacket.getData(), TransactionViewModel.SIZE,
                    
                   neighbors.forEach(n -> n.send(tipRequestingPacket));
        };
    }

Same problem.  TCPNeighbor caches the DatagramPacket backing array.
"ByteBuffer.wrap(packet.getData())" does not copy the data. It only provides the DatagramPacket's backing array, which is then re-wrapped in the new ByteBuffer.
```
LINE 80
    @Override
    public void send(DatagramPacket packet) {
        if ( sendQueue.remainingCapacity() == 0 ) {
            sendQueue.poll();
        }
        sendQueue.add(ByteBuffer.wrap(packet.getData()));
    }
```

Suggested FIX as follows. There also needs to be a 'sendLock' because the queue used is not synchronized and the check to size can change while the code is here. Due to the other thread that is accessing the queue.

Since the data size is fixed, it can be just cloned.

```
    @Override
    public void send(DatagramPacket packet) {
        synchronized (sendLock) {
            if (sendQueue.remainingCapacity() == 0) {
                sendQueue.poll();
            }
            byte[] data = packet.getData().clone();
            sendQueue.add(ByteBuffer.wrap(data));
        }
    }
```

Even better still is to just make a new DatagramPacket each time fresh. It is very lightweight and many servers make millions and millions of them constantly with no worries.

**Comment by footloosejava** [comment]
Also, more of the fixer  ....

In Node.java, the signature of sendPacket can be changed to this:

```
private void sendPacket(TransactionViewModel transactionViewModel, Neighbor neighbor) throws Exception {
        //limit amount of sends per second
        long now = System.currentTimeMillis();
        if ((now - sendPacketsTimer.get()) > 1000L) {
            //reset counter every second
            sendPacketsCounter.set(0);
            sendPacketsTimer.set(now);
        }
        if (SEND_LIMIT >= 0 && sendPacketsCounter.get() > SEND_LIMIT) {
            //if exceeded limit - don't send
            //log.info("exceeded limit - don't send - {}", sendPacketsCounter.get());
            return;
        }

        
            DatagramPacket datagramPacket = new DatagramPacket(new byte[TRANSACTION_PACKET_SIZE],TRANSACTION_PACKET_SIZE);
            datagramPacket.setData(transactionViewModel.getBytes(), 0, TransactionViewModel.SIZE);
            Hash hash = transactionRequester.transactionToRequest(isP_SELECT_MILESTONE());

            byte[] src = (hash != null) ? hash.bytes() : transactionViewModel.getHash().bytes();
            datagramPacket.setData(src, TransactionViewModel.SIZE,REQUEST_HASH_SIZE);

            neighbor.send(datagramPacket);
            sendPacketsCounter.getAndIncrement();
    }
```

Then .... one last, make the TCPNeighbour send synced (and UDP too for safe).
The UDP is OK right now because Socket.write is already sycned internally.

I've tested these changes and they appear good-to-go.

**Comment by footloosejava** [comment]
Neighbor can be changed to this. UDPNeighbor and TCPNeighbor can then move their guts to 'sendPrivate':

```
    private final Object sendDatagramLock = new Object();

    protected abstract void sendPrivate(DatagramPacket packet);

    public void send( DatagramPacket packet){
        synchronized (sendDatagramLock){
            sendPrivate(packet);
        }
    }
```

**Comment by footloosejava** [comment]
I looked at this again and it is definitely a problem:

* The TCPNeighbor ques fill up fast,  then when the sink processor catches up, it sends a burst of data from the TCPNeighbors ArrayBlockingQueue. With the data sharing the same byte[] from the premade singleton packet, it then sends all the packets containing the same data ... unless the byte[] is in fluc, in which case it sends bad data.

**Comment by footloosejava** [comment]
## Since no one has patched this yet  **(ahem!)**

I decided to throw out some metrics so that you can see how bad it really is. Adding some tracking code (below)  the **rate of good packets to bad packets (corrupted) from this bug is as high as ~30%.**

## So basically, TCP clients are killing each other with corrupted and/or duplicate packets.

After 4 minutes, with 4 TCP neighbors, this is how many TCP packets were corrupted by this bug:

> Neighbor#1 good 4739 bad 1500 = 24% corrupted packets
> Neighbor#2 good 4787 bad 1500 = 23% corrupted packets
> Neighbor#3 good 4996 bad 2000 = 29% corrupted packets
> Neighbor#4 good 5400 bad 1750 = 24% corrupted packets

```
    private final AtomicInteger OKPackets = new AtomicInteger(0);
    private final AtomicInteger BADPackets = new AtomicInteger(0);

   @Override
    public void send(DatagramPacket packet) {
        if (sendQueue.remainingCapacity() == 0) {
            ByteBuffer[] poll = sendQueue.poll();
            if (Arrays.equals(poll[0].array(), poll[1].array())) {
                OKPackets.incrementAndGet();
            } else {
                BADPackets.incrementAndGet();
                log.info("BB taken: good {} bad {}", OKPackets.get(), BADPackets.get());
            }
        }
        ByteBuffer[] array = {ByteBuffer.wrap(packet.getData()), ByteBuffer.wrap(packet.getData().clone())};
        sendQueue.add(array);
    }

    public ByteBuffer getNextMessage() throws InterruptedException {
        ByteBuffer[] array = this.sendQueue.poll(10000, TimeUnit.MILLISECONDS);
        if (Arrays.equals(array[0].array(), array[1].array())) {
            OKPackets.incrementAndGet();
        } else {
            BADPackets.incrementAndGet();
            log.info("BB taken: good {} bad {}", OKPackets.get(), BADPackets.get());
        }
        return array[1];
    }
```

**Comment by gjeee** [comment]
like i said i am no network-expert but this poll method just returns a single ByteBuffer right.....not a array or am I missing something?

**Comment by gjeee** [comment]
o wait i understand your "debug-trick" now :-)

**Comment by attritionorg** [comment]
@footloosejava Could this be used intentionally as a remote denial of service attack?

**Comment by footloosejava** [comment]
re: Could this be used intentionally as a remote denial of service attack?
Anything that sends incorrect data that requires processing/checking constitutes a DDOS risk. In this case, IRI nodes are already inadvertently DDOS'ing each other with bad data. This has been happening for some time - this bug should be patched ASAP. ( I might throw out a pull request today and see if it can get fast tracked).

**Comment by footloosejava** [comment]
This was already fixed in one of my PRs that was merged from a month ago. I am closing this issue.

**Comment by GalRogozinski** [comment]
#594 closed this
