### ISSUE TITLE
Unnecessary gaps in branches

### ISSUE THREAD

**Issue by gjeee** [iotaledger/iri#573]
The [checkSolidity routine](https://github.com/iotaledger/iri/blob/2f1fb78b06cbdc7e280b4191326593ef7ea03514/src/main/java/com/iota/iri/TransactionValidator.java#L125) is important since it checks a tx and if any downstream tx are missing it will add it to its transactionRequester. It will also update the solid-property of a tx.

The TipsManager runs a [thread](https://github.com/iotaledger/iri/blob/2e0d1c38b18f196fec727acacff3b3fdf0e06868/src/main/java/com/iota/iri/service/TipsManager.java#L55) every 750 ms to check the solidity regularly for non-solid tips. To this end it picks a random non-solid tip. When it is actually no longer a tip, it will remove the hash from tipsViewModel. That is fine of course. However in this case the checkSolidity() routine is no longer called due to short-circuit evaluator (see code below).

Imo this is unwanted since it can lead to gaps deeper down a branch (and these gaps are not actively worked on by adding it to the transactionRequester). This can also lead to less effective random walks since they are terminated sooner (so less indirect confirms).

```
 private void scanTipsForSolidity() throws Exception {
        int size = tipsViewModel.nonSolidSize();
        if(size != 0) {
            Hash hash = tipsViewModel.getRandomNonSolidTipHash();
            boolean isTip = true;
            if(hash != null && TransactionViewModel.fromHash(tangle, hash).getApprovers(tangle).size() != 0) {
                tipsViewModel.removeTipHash(hash);
                isTip = false;
            }
            if(hash != null  && isTip && transactionValidator.checkSolidity(hash, false)) {
                //if(hash != null && TransactionViewModel.fromHash(hash).isSolid() && isTip) {
                tipsViewModel.setSolid(hash);
            }
        }
}
```

**Comment by gjeee** [comment]
To further speed up the tips-solidity scan I would advise to do a check immediate after receiving a tx.

So I would change the routine [TransactionValidator#updateStatus](https://github.com/iotaledger/iri/blob/2f1fb78b06cbdc7e280b4191326593ef7ea03514/src/main/java/com/iota/iri/TransactionValidator.java#L217)

```
public void updateStatus(TransactionViewModel transactionViewModel) throws Exception {
        transactionRequester.clearTransactionRequest(transactionViewModel.getHash());
        boolean bTip=transactionViewModel.getApprovers(tangle).size() == 0;
        if(bTip) {
            tipsViewModel.addTipHash(transactionViewModel.getHash());
        }
        tipsViewModel.removeTipHash(transactionViewModel.getTrunkTransactionHash());
        tipsViewModel.removeTipHash(transactionViewModel.getBranchTransactionHash());

        if(quickSetSolid(transactionViewModel)) {
            addSolidTransaction(transactionViewModel.getHash());
            if(bTip){
                   tipsViewModel.setSolid(transactionViewModel.getHash());
            }
        }
}
```

**Comment by GalRogozinski** [comment]
Thanks for the input.

Why do you say the gaps are not worked on by the `transactionRequester`?
The `TransactionValidator#checkSolidity` method requests all the non solid transaction that the tip approves as far as I can tell.

As far as `updateStatus()` I think it is better for one job to be done in one place if possible. Did you run tests that confirm better performance?

**Comment by gjeee** [comment]
rgd point 2: i think you are right (to keep the responsible job in 1 place). my suggested changes do increase performance, but it is indeed not that drastic that the change is warranted.

rgd point 1: you are also right about that. 

thanks for your feedback i will close this issue now :-)

**Comment by gjeee** [comment]
i am going to reopen this issue. performance tests show that without my 2 modifications the non-solid tips increase slowly in the hundreds. with the fix it always stays around 0. if the hash fix has been committed in the new iri i will do more tests. for now i will put this investigation on hold.

**Comment by jakubcech** [comment]
Related to #761 and #779

**Comment by gjeee** [comment]
this is not an issue anymore with PR #913 and #907 in place. i will close this now.
