### ISSUE TITLE
TCP clients are killing each other with corrupted and/or duplicate packets.

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#578]
see https://github.com/iotaledger/iri/issues/564

From 24% up to 30% of all outgoing TCP packets are corrupted and/or duplicated because of this bug.

**Comment by footloosejava** [comment]
I have submitted a new PR that fixes this. see changes to Node and TCPNeighbor in https://github.com/iotaledger/iri/pull/577

**Comment by GalRogozinski** [comment]
Since this is a symptom of #564 I am closing it as a duplicate.
