### ISSUE TITLE
Use IRI api to generate address and transfer iota

### ISSUE THREAD

**Issue by sunujacob** [iotaledger/iri#581]
can we use iri api to send iota to an address or to generate address using json rpc. I didnt find it [here](https://iota.readme.io/v1.2.0/reference#getbalances). Please help.

**Comment by gjeee** [comment]
you need a client-library for that, e.g. [https://github.com/iotaledger/iota.lib.js](https://github.com/iotaledger/iota.lib.js) 

look at sendTransfer

**Comment by sunujacob** [comment]
The thing is nodejs isnt my strong point. I'm used to php. And I found a json rpc library. I can retrieve nideinfo but not sendinfo as that is not covered in the documentation.

**Comment by gjeee** [comment]
try discord.... there is a php channel

**Comment by sunujacob** [comment]
Thanks for replying.. will try discord

**Comment by GalRogozinski** [comment]
Questions of this kind are good for https://helloiota.com/
