### ISSUE TITLE
GPG public key for current release signature changed

### ISSUE THREAD

**Issue by Strayer** [iotaledger/iri#582]
Sorry if I'm missing something here, but did the release signing key change for 1.4.2.2?

Previously it was E18604B060443214, now it seems to be E2DACFD8E7CE8224, which I can find nowhere, not even on keyservers.

**Comment by rajivshah3** [comment]
@paulhandy I think they're referring to your GPG key

**Comment by GalRogozinski** [comment]
By looking in https://keybase.io/paulhandy, I can confirm it is Paul's :-)
