### ISSUE TITLE
Commit discussion ... re pull 583

### ISSUE THREAD

**Issue by directorm** [iotaledger/iri#584]
I'd love to get feedback or hear from other people about the changes in 
https://github.com/iotaledger/iri/pull/583

It can be forked here:
https://github.com/directorm/iri/tree/directorm-NonBlockingIOAndMoreV1

Especially if you get a chance to fork it and run it ... and even better if you can help make it better!

Or that it inspires you to hack on the iri here and find your own enhancements.

Over to you ...

**Comment by gjeee** [comment]
kickass!!! lots of interesting angles to sharpen code!

**Comment by footloosejava** [comment]
Very nice - that's awesome. Can't wait to check it out!

**Comment by gjeee** [comment]
today (16th of March) i applied your PR ....works fine as far I can see....however i did notice a lot more traffic although the network is quite quiet last days....so I am a bit surprised to see that RX is that high.....significantly more than usual.....

![image](https://user-images.githubusercontent.com/13155183/37549041-d27cff12-297c-11e8-9606-2f6e74129e17.png)

**Comment by directorm** [comment]
Good to hear you got it working! It should work out-of-the-box as it did.

Re: RX -- that's interesting. The received data is higher? That's good - if that means the system is able to process more data faster for each peers. Although, I'm not sure that is what it means. Can you break it down by TCP and UDP for RX and TX? With iftop perhaps?

**Comment by directorm** [comment]
Good to hear you got it working! It should work out-of-the-box as it did.

Re: RX -- that's interesting. The received data is higher? That's good - if that means the system is able to process more data faster for each peers. Although, I'm not sure that is what it means. Can you break it down by TCP and UDP for RX and TX? With iftop perhaps?

Maybe also worth noting that the packet corruption issue mentioned in Issues has been applied to this version - so TCP outgoing packets are no longer corrupted.

UDP incoming processing should also be faster now. In this PR version, the UDP receiver thread submits the data into the striped executor - and that can be efficiently multi-tasked asynchronously (although in reality it uses less threads than the original version). 

In the original version, the executor queue can block when it fills up to `PROCESSOR_THREADS` qty of jobs:

```
ExecutorService processor = new ThreadPoolExecutor(PROCESSOR_THREADS, PROCESSOR_THREADS, 5000L,
                                            TimeUnit.MILLISECONDS, new ArrayBlockingQueue<Runnable>(PROCESSOR_THREADS, true),
                                             new ThreadPoolExecutor.AbortPolicy());
```

In my version, the jobs are submitted into the striped executor with concurrency of 4. Then the jobs when processed async are submitted to the various queues. Each queue entry corresponds with a new striped executor task on that queue one-to-one unless the queue fills up and it drops the task entirely.

```
private void addReceivedDataToReceiveQueue(TransactionViewModel receivedTransactionViewModel, Neighbor neighbor) {
        boolean added = receiveQueue.add(new ImmutablePair<>(receivedTransactionViewModel, neighbor));
        if (receiveQueue.size() > RECV_QUEUE_SIZE) {
            log.warn("Receive queue full. Transaction dropped. Consider increasing the Q_SIZE_NODE parameter. Current size: {}", RECV_QUEUE_SIZE);
            receiveQueue.poll();
            added = false;
        }
        if (added) {
            executor.submitStripe("receiveQueue", () -> {
                try {
                    Pair<TransactionViewModel, Neighbor> receivedData = receiveQueue.poll();
                    if (receivedData == null) {
                        log.error("Process Received job - null result from receiveQueue.poll()");
                    } else {
                        processReceivedData(receivedData.getLeft(), receivedData.getRight());
                    }
                } catch (final Exception e) {
                    log.error("Process Received Data Thread Exception:", e);
                }
            });
        }
    } 
```

Since each Node.java queue (braodcast, receive, reply) uses a unique stripe (you can see their stats in the console output), each stripe ensures concurrency (sequentially as far as these queues are concerned), but also ensures that the tasks don't block here. When the tasks are finished, they also get submitted to executor on  various TCP-OUT and UDP-OUT stripes and these also don't block pending socket processing.

It makes sense to me that this system leads to higher throughput and more efficient use of processor threads. In future versions I hope to make a StripeManager that can respond to system load and adjust the levels of concurrency required in each operational area - on the fly :)

**Comment by directorm** [comment]
:point_up_2:  Of course, I'm hoping that's why the RX is higher!

**Comment by directorm** [comment]
Did you overwrite the database when you installed the PR and then re synced it?

**Comment by GalRogozinski** [comment]
Please continue the discussion on the PR #583
