### ISSUE TITLE
PR review code quality rule - Use explicit scoping instead of the default package private level

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#594]
Re Travis CI build  code-style rule: **Use explicit scoping instead of the default package private level**

There are a lot of instances where it makes sense to keep the level as `package private`:

- Where only tests, properly arranged by package, need access to a method or variable

- Where other classes in the same package need privileged access.

This is more restrictive than `protected` because it allows only package family members access. This is also more sensible in many cases than `private` where (1) a method is not and interface method, (2) it is something package members should have visibility to, (3) the field is `final` or it is accessed through an accessor (get method) to ensure encapsulation.

I think this rule needs to be eliminated since it is actually going to lead to more problems and code-smells in the future than keeping it in place.

For your consideration.

**Comment by alon-e** [comment]
for context: the enforcing tool is Codacy (based on PMD): https://app.codacy.com/app/iotaledger/iri/dashboard

-- Agreed & removed.
