### ISSUE TITLE
Jinn and Arduino

### ISSUE THREAD

**Issue by mrlukaszfuszara** [iotaledger/iri#598]
Will Jinn be available for Arduino?

**Comment by alon-e** [comment]
This isn't related to IRI.
Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
