### ISSUE TITLE
Question - `toRequest` is going up on its own - even without neighbors or network connection. 

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#604]
I have no neighbors for an hour now - I disconnected them. My `toRequest` is going up. See below - I cut out the log entries 'toProcess = 0`, `toBroadcast = 0` , ` toReply = 0` for clarity

I also disconnected from the internet entirely and it is still going up.

Normal? Why is this happening?

The qty comes from this code in the TransactionRequester:

```
 public int numberOfTransactionsToRequest() {
        return transactionsToRequest.size() + milestoneTransactionsToRequest.size();
    }
```

Perhaps someone has a quick answer.

```
03/30 17:20:36.570 [pool-3-thread-2] INFO  toRequest = 58 ,  totalTransactions = 8492226
03/30 17:20:46.572 [pool-3-thread-2] INFO  toRequest = 58 ,  totalTransactions = 8492226
...
03/30 17:27:06.816 [pool-3-thread-2] INFO  toRequest = 58 ,  totalTransactions = 8492226
03/30 17:27:16.818 [pool-3-thread-2] INFO  toRequest = 59 ,  totalTransactions = 8492226
03/30 17:27:26.820 [pool-3-thread-2] INFO  toRequest = 59 ,  totalTransactions = 8492226
03/30 17:27:36.821 [pool-3-thread-2] INFO  toRequest = 59 ,  totalTransactions = 8492226
03/30 17:27:46.823 [pool-3-thread-2] INFO  toRequest = 59 ,  totalTransactions = 8492226
```

**Comment by alon-e** [comment]
this can happen, there is a balancing act:
1. There are threads scanning tips for missing transactions in yet to be solid subtangles (`TipsVM`). 
2. `TransactionRequester` removes requested tips w/ probability `P_REMOVE_REQUEST`.
