### ISSUE TITLE
Cannot find all the related transaction with findTransaction with Tag

### ISSUE THREAD

**Issue by yillkid** [iotaledger/iri#606]
Reproduce:

The transaction in IOTA explorer: [here](https://thetangle.org/transaction/PJMQHYNXLERTVTOWBLPKVDJ9HSTUACPURBCPJEWQDQAWGOPWZWFJMOVIXPALFW9XXSJVBZQVTFG9A9999)
* Transaction hash: PJMQHYNXLERTVTOWBLPKVDJ9HSTUACPURBCPJEWQDQAWGOPWZWFJMOVIXPALFW9XXSJVBZQVTFG9A9999
* Transaction Tag: 9JVXCXMFAMKLUQQCDACSWJVDLHC

and the transaction is issued from a full-node **http://node.deviceproof.org:14265**

Find transaction by Tag with a full-node:
`curl http://node.deviceproof.org:14265 \
   -X POST \
   -H 'Content-Type: application/json' \
   -H 'X-IOTA-API-VERSION: 1.4.1' \
   -d '{"command": "findTransactions", "tags": ["9JVXCXMFAMKLUQQCDACSWJVDLHC"]}'
`

Output:
`{"hashes":["XKCW9XYDZINICSXGZUZUCBFXMSPDKDHIMBUYRNSQSZBF9TENNWGYWKAUEM9EIKVUBYZVZKRUKMAB99999","VMWABNXWNGELKWEMRMAFEUIZBQDBQTZYVVHMHBOOMHKHMCCOTCAPXCTTXMVOX9GEDHLXEYEKPQOUA9999","YGPDRXHNQDLKKAQQNPLNLTEWP9JNIVKRHUSWZJSKO9BXZLYIDFSTUNADQY9FDG9WYDTUGZGENNJD99999","YGRUNPATJDHNRMCGVCNFPRXUWJFGPUFJWNWSNGNJWQQEBXWGWBSDMRLJQOKVZYZGGSBIGUBYWKEDZ9999","HXVCZOXJNZVSTOIKOYFGASYQCPXFVXTPRCQADASAHWGHYGWOLZJZXRQGNASKIORVSTNCGSBOBALHA9999","CLVGMJWNZELSUYNBDITZF9SSNUFYREQGEGQSVFF9TQOSVUNVUGEDGLOM9UDNESIEZMEGSRKXZIPRA9999","PTIJKVT9RUASWVNPEDAESAHPGWIPEEBGOZNWBCLBDIVJZTOUWQHJECWARPNTJMGHZDQLXMQVOVOIZ9999"],"duration":1}`

The PJMQHYNXLERTVTOWBLPKVDJ9HSTUACPURBCPJEWQDQAWGOPWZWFJMOVIXPALFW9XXSJVBZQVTFG9A9999 hash **NOT** in the hash list !

**Comment by footloosejava** [comment]
Just a question. It is a zero value transaction. Are they retained after snapshots?

**Comment by yillkid** [comment]
Reproduce:

# coding=utf-8

from iota import Iota, ProposedTransaction, Address, TryteString, Tag, Transaction

NODE_URL="http://node.deviceproof.org:14265"
DEPTH=7
MIN_WEIGHT_MAGNITUDE=14

def transfer(seed, address, tag, message, value):

    recipient_address = address
    sender_message = message
    sender_tag = tag

    prepared_transferes = []
    dic_bundle = ""

    api = Iota(NODE_URL, seed)

    sender_tag = bytes(sender_tag)
    transfer_value = int(value)

    txn = \
        ProposedTransaction(
            address = Address(
                recipient_address
        ),

        message = TryteString.from_string(sender_message),
        tag = Tag(sender_tag),
        value = transfer_value,
    )

    prepared_transferes.append(txn)
    try:
        dic_bundle = api.send_transfer(
            depth=DEPTH,
            transfers=prepared_transferes,
            min_weight_magnitude=MIN_WEIGHT_MAGNITUDE
        )
    except Exception as e:
        print e.message, e.args
        dic_bundle = ""

    return str(dic_bundle['bundle'].hash)


def find_transaction(search_type, search_value):

    api = Iota(NODE_URL)
    result = ""

    if int(search_type) == 0:
        result = api.find_transactions(tags = [search_value])
    if int(search_type) == 3:
        result = api.find_transactions(bundles = [search_value])

    return result


TAG = "AABBCCDDMMMMMGG"
SEED = "RBYYYKDIUDXV9Z9FQPFJSA9QQIGFZAS9XXAWHSDPPXYR9ULXZWYNQSOOYHOXSNXEORWGRIQXXINRHKTCU"
RECEIVE_ADDRESS = "ILXW9VMJQVFQVKVE9GUZSODEMIMGOJIJNFAX9PPJHYQPUHZLTWCJZKZKCZYKKJJRAKFCCNJN9EWOW9N9YDGZDDQDDC"
MESSAGE = "message"
VALUE = 0

bundle_hash = transfer(SEED, RECEIVE_ADDRESS, TAG, MESSAGE, VALUE)

print "Send success, bundle hash is " + str(bundle_hash)
print "Search by tag ... " + str(TAG) + " result is " + str(find_transaction("0", TAG))
print "Search by bundle hash ... result os " + str(find_transaction("3", bundle_hash))

**Comment by alon-e** [comment]
@yillkid , this is a known issue, it relates to the `obsoleteTag` being indexed in IRI: #340 
and library protection from key derivation function bug: example: https://github.com/iotaledger/iota.lib.js/blob/master/lib/crypto/bundle/bundle.js#L121

so the result is that the first transaction in a bundle's `tag` is incremented, so you can't fetch with that tag.
waiting for a DB migration to make this change.

> It is a zero value transaction. Are they retained after snapshots?
@footloosejava no transactions are retained after global snapshots. 
only the state of addresses (balance per addresses) is retained.

**Comment by jakubcech** [comment]
This was fixed as part of https://github.com/iotaledger/iri/pull/728, thanks!
