### ISSUE TITLE
Incorrect tag size in TransactionViewmodel - specifies 27 bytes, whilst tagBytes is always 17 bytes

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#611]
Bug in code  - perhaps a typo?

Code from lines 292 to 298 in `TransactionViewModel.java`

TAG_SIZE specifies 27 bytes, whilst tagBytes is always 17 bytes.

All tests still pass when changed to 17.

```
public Hash getTagValue() {
        if(transaction.tag == null) {
            byte[] tagBytes = Converter.allocateBytesForTrits(TAG_TRINARY_SIZE);
            Converter.bytes(trits(), TAG_TRINARY_OFFSET, tagBytes, 0, TAG_TRINARY_SIZE);
            transaction.tag = new Hash(tagBytes, 0, TAG_SIZE);
        }
        return transaction.tag;
    }
```

The error is here in `TransactionViewModel.java`:

```
private static final int TAG_SIZE = 27;
```

Both `OBSOLETE_TAG_TRINARY_SIZE` and `TAG_TRINARY_SIZE` are both 81 - resulting in `TAG SIZE` = **17** (ie. Not 27).

This is also probably why this strange bounds check/adjustment was made in `Hash.java` - adjusting the bytes size to equivalent of `Math.min( size, bytes.length-offset )`:

```
private void fullRead(byte[] bytes, int offset, int size) {
        this.bytes = new byte[SIZE_IN_BYTES];
        System.arraycopy(bytes, offset, this.bytes, 0, size - offset > bytes.length ? bytes.length-offset: size);
        hashCode = Arrays.hashCode(this.bytes);
    }
```

**Comment by alon-e** [comment]
@footloosejava - yeah, you're right it's a regression bug due to poor variable naming.
`TAG_SIZE` vs. `TAG_TRINARY_SIZE`.
