### ISSUE TITLE
Question: How can I setup my full-node to use all available cores?

### ISSUE THREAD

**Issue by tolotos-rgu** [iotaledger/iri#616]
I have a full-node running which uses only one of the available cores. How can I configure IRI to use all cores?

**Comment by jojoCoWorker** [comment]
Hi tolotos-rgu !
Are you running iri on a Virtual Machine ?
If this is the case, you're "only one cpu' is a virtual cpu so no matter if you see only one cpu on tangletools.org, all you're cpu's are used by your Virtual Machine.

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
