### ISSUE TITLE
udp nodes for iri where get?

### ISSUE THREAD

**Issue by axelxod** [iotaledger/iri#626]
start iri, where i can get udp node for sync?
when i try add http://node:14265 in iri - i have error.

**Comment by gjeee** [comment]
you need to manually find peers (try discord channel) and/or use [nelson](https://github.com/SemkoDev/nelson.cli) which enables automatic peer discovery.

**Comment by alon-e** [comment]
You can get more support by joining our [discord](https://bit.ly/iota-invite) - #fullnodes channel

Common IOTA discussion boards:

- [https://forum.helloiota.com/](https://forum.helloiota.com/)
- [https://iota.stackexchange.com](https://iota.stackexchange.com)
- [https://www.reddit.com/r/Iota/](https://www.reddit.com/r/Iota/)
- [discord](https://bit.ly/iota-invite)
