### ISSUE TITLE
Preflight Response Error

### ISSUE THREAD

**Issue by domschiener** [iotaledger/iri#63]
When making a request with Content-Type header from the browser, I get a 500 Internal Server Error:
```
Response for preflight has invalid HTTP status code 500
```

Disabling the Content-Type header will result in the request coming through successfully.

**Comment by domschiener** [comment]
```
{"exception":"Invalid request payload: \u0027\u0027","duration":4}
```

This is the response from IRI. Probably has to do with the fact that Google sends an OPTIONS request before the POST, and IRI rejects the OPTIONS request.

**Comment by todofixthis** [comment]
The IRI will also need to add `Access-Control-Allow-Origin: <domain or *>` to the response.

https://enable-cors.org/server.html

**Comment by jakubcech** [comment]
Reopen if you still see this issue, probably not present anymore
