### ISSUE TITLE
Silently fails when --config option refers to non-existing file

### ISSUE THREAD

**Issue by alongalky** [iotaledger/iri#631]
### Bug description
When launching a node with an INI file via the --config option, the launch continues even when the file does not exist. This is confusing because the INI settings are simply ignored.

### Steps To Reproduce
1. Run `java -jar iri-1.4.2.3.jar -p 14265 --testnet --config fake.file`

### Expected behaviour
I would expect the node to crash immediately with an "INI file not found" error message. In addition, it would be useful to give an indication in the successful case, such as "Successfully loaded options from configuration file <conf.ini>"

### Actual behavior
The node runs with default settings and does not complain.

**Comment by jakubcech** [comment]
Part of Configuration rework: #724  https://github.com/iotaledger/iri/issues/724

**Comment by alongalky** [comment]
@jakubcech I don't see this issue addressed in #724 (fail when file doesn't exist)

**Comment by GalRogozinski** [comment]
@alongalky you are correct that it is not explicitely written there. By linking the issues it has become part of the task.

I should mention here that the issue will be resolved by removing the `--config` flag. It has never really worked anyhows. People can use a config file by creating an `iota.ini` file in IRI base folder.

**Comment by jakubcech** [comment]
@GalRogozinski 'and removing the `--config` flag' is not part of #724?

**Comment by alongalky** [comment]
@jakubcech I think removing the `--config` flag does not fix the problem: you could still have a misnamed or missing `iota.ini`, and IRI will start silently without loading the configuration. I think the desired behavior should be either of the following:
1. Require an `iota.ini`, and fail if one is not provided
1. Only load a configuration file if the `--config` option is provided, and fail if the file is not found
