### ISSUE TITLE
How to find and validate two another transactions when commit my own transaction

### ISSUE THREAD

**Issue by ggokka** [iotaledger/iri#632]
The issue tracker is only for reporting bugs or asking for feature requests and bugs.
If you need technical assistance for running a node please consult the #fullnode channel on discord (https://discord.gg/jrxApWC) or https://forum.helloiota.com/Technology/Help.
If you have general questions on IOTA you can go to https://iota.stackexchange.com/, or https://helloiota.com/, or browse discord channels (https://discord.gg/C88Wexg).

### Bug description
A general description of the bug.

### Hardware Spec
On what hardware is the node running on?

### Steps To Reproduce
1. 
2. 
3. 

### Expected behaviour
What should happen.

### Actual behavior
What really happened.

### Errors
Paste any errors that you see.

*Note*
The feature request will probably be integrated faster if you do a pull request for it.
If you want to discuss the feature before you actually write the code you are welcome to do it by first submitting an issue.

### Description
Briefly describe the feature you want.

### Motivation
Explain why this feature is needed.

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by GalRogozinski** [comment]
You can get more support by joining our discord - #fullnodes channel

Common IOTA discussion boards:

    https://forum.helloiota.com/
    https://iota.stackexchange.com
    https://www.reddit.com/r/Iota/
    discord
