### ISSUE TITLE
"Should never reach this point" - is reachable, transactionToApprove (1.1.2.6 dev)

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#65]
In the latest update to `transactionToApprove` The `hit` was added:
Using `ThreadLocalRandom.nextLong(totalRating)` - which returns a random number `[0-totalRating)`

So, in the corner case where the random number selected is `0L` - the  `return preferableMilestone;` is reached.

```
if (totalRating > 0L) {
            long hit = ThreadLocalRandom.current().nextLong(totalRating);
            if (hit > 0L) {
                ...
            }
        }
        // Should never reach this point
        return preferableMilestone;
```

Is this intentional?

This also has the side effect of never choosing a tip who's `tailsRatings` is 1.

**Comment by alfredch** [comment]
That is intentional. The comment is misleading.

**Comment by alfredch** [comment]
Tip selection completely reworked. No point to keep that issue report open,
