### ISSUE TITLE
Refactor to "weightedRandomChoice" function

### ISSUE THREAD

**Issue by alongalky** [iotaledger/iri#654]
https://github.com/iotaledger/iri/blob/1337870a02a6cdd1aa1f014aa513e398c4e827b1/src/main/java/com/iota/iri/service/TipsManager.java#L271-L276

I recommend refactoring this since the function is already very long. The function call should look like:
weightedRandomChoice(tips, tips.map(tipIndex => walkRatings[tipIndex]))

**Comment by GalRogozinski** [comment]
I'd say the entire `randomWalk` method should be broken down to smaller methods

**Comment by alongalky** [comment]
Agreed, I think this is a nice isolated first step
