### ISSUE TITLE
recursiveUpdateRatings is tested, but not used

### ISSUE THREAD

**Issue by alongalky** [iotaledger/iri#655]
https://github.com/iotaledger/iri/blob/16e5a34f5df16d7df2d2af30203bf61f88fc893c/src/test/java/com/iota/iri/service/TipsManagerTest.java#L125

The wrong function is being tested: `recursiveUpdateRatings` instead of `serialUpdateRatings`. The tests should be modified and the `recursiveUpdateRatings` function removed from the code.

**Comment by jakubcech** [comment]
Resolved by https://github.com/iotaledger/iri/pull/785
