### ISSUE TITLE
getInclusionStates returns "The subtangle is not solid"

### ISSUE THREAD

**Issue by pinpong** [iotaledger/iri#71]
{"command": "getInclusionStates", "transactions": ["OAATQS9VQLSXCLDJVJJVYUGONXAXOFMJOZNSYWRZSWECMXAQQURHQBJNLD9IOFEPGZEPEMPXCIVRX9999"], "tips": ["EJDQOQHMLJGBMFWB9WJSPRCYIGNPO9WRHDCEQXIMPVPIJ9JV9RJGVHNX9EPGXFOOKBABCVMMAAX999999"]}

**Comment by alfredch** [comment]
Take a more recent solid milestone. The result is 'false'.
{"command": "getInclusionStates", "transactions": ["DBPECSH9YLSSTQDGERUHJBBJTKVUDBMTJLG9WPHBINGHIFOSJMDJLARTVOXXWEFQJLLBINOHCZGYFSMUEXWPPMTOFW"], "tips": ["MYSRR9NCI9WVTXJVPZQDMWQGECJSXXCAYLP9ZATOQNJBE9QSWDUFQWVHDVBCEEBKHZLPOA9YBGH999999"]}

**Comment by pinpong** [comment]
Yeah sure but the response is misleading.

**Comment by alfredch** [comment]
Why do you think so? The subtangle is in fact 'not solid' looking back from milestone 'EJDQO...'.
That is the reason why that milestone did not get a single approval, even not from the later milestones.
