### ISSUE TITLE
Logging: make visibility of log levels configurable

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#717]
### Description
Allow a user to configure the level of log visible to him/her by setting the lowest visible level.

### Motivation
1. a user debugging issues may want access to `debug`, while a node operator might want only `error` messages for example.

1. Currently printing `log.debug` level requires a workaround in `logback.xml` file.

### Requirements
- user definable flag to set levels
- default `info`
- `--debug` flag will set the default to `debug`

### Am I planning to do it myself with a PR?
Yes

**Comment by jakubcech** [comment]
Addressed by #727
