### ISSUE TITLE
Can iri automatically discover neighbor now

### ISSUE THREAD

**Issue by hunjixin** [iotaledger/iri#746]
Can iri automatically discover neighbor now

**Comment by hunjixin** [comment]
and Is the code associated with consensus already open source?  I looked for some time, but I didn't find it.

**Comment by GalRogozinski** [comment]
Github is for opening issues or asking for feature requests.

Questions should go to common IOTA discussion boards:

https://forum.helloiota.com/
https://iota.stackexchange.com
https://www.reddit.com/r/Iota/
discord
