### ISSUE TITLE
Where is the IRI database on OS X ?

### ISSUE THREAD

**Issue by Kwintspiracy** [iotaledger/iri#748]
Hello,

I'm trying to replace the ire.jar file with the newest version. For that I need to know where is located the IRI database on my Mac so I can delete and start fresh.

Can you please indicate the location?
I've been using the Light Wallet and Bolero.

Thank you

**Comment by GalRogozinski** [comment]
Github is for opening issues or asking for feature requests.

Questions should go to common IOTA discussion boards:

https://forum.helloiota.com/
https://iota.stackexchange.com
https://www.reddit.com/r/Iota/
discord

**Comment by rajivshah3** [comment]
@Kwintspiracy for Bolero the database is stored in `~/.bolero` according to https://github.com/SemkoDev/bolero.fun#where-is-the-database-located
