### ISSUE TITLE
PearlDiver Search Times (for discussion)

### ISSUE THREAD

**Issue by footloosejava** [iotaledger/iri#751]
![image](https://user-images.githubusercontent.com/32090281/39856084-72bd644a-53e3-11e8-861a-5abf9e362dd1.png)

### Does Using an Executor Work Better Than Creating Threads?

No. The search times are sufficiently long that creating threads has NO effect on performance times. Unless the search times were sub 10-millisecond, creating anywhere from 1 to 32 threads makes zero difference. I tested it, I won't bore you with the chart.

### Are the performance gains log-based?

No. The time taken is 1/2 with every doubling of processing resources. On my system, there is definitely a hard-cap of 16-to-18 worker threads where after that there is no further benefit to adding extra workers.

### What is the effect of Hyper-Threading / Simultaneous Multi-Threading?

I also ran the entire test with HT/SMT turned off in the BIOS (Cores still 16 but logical processors also now only 16). My test at threads 1-15 with it OFF are almost identical to the one with it turned ON. If the HT/SMT has a benefit, then the values of 'OFF' should be almost double the ones done with it enabled. The exact same parameters, 1000 iterations at each worker count, random data, etc.. It would appear that the benefit of HT/SMT is negligible or very-very small.

![image](https://user-images.githubusercontent.com/32090281/39900162-c7068518-5474-11e8-865e-28689d697b37.png)

### What does Changing Minimum Weight Magnitude do to Search Times?

Changing the MWM from 14 to 15, triples the amount of time for searching.

![image](https://user-images.githubusercontent.com/32090281/39937500-cf18995e-5504-11e8-95aa-d5f583804b1e.png)

**Comment by GalRogozinski** [comment]
@alon-e have a look.

@footloosejava, Alon is busy today but don't worry. We will tend to that PR.

**Comment by footloosejava** [comment]
The PR was merged. I am closing this.
