### ISSUE TITLE
Unnecessary condition in random tip request ? 

### ISSUE THREAD

**Issue by gjeee** [iotaledger/iri#762]
### Bug description
I still do not see why this [condition](https://github.com/iotaledger/iri/blob/a3a1aa8a70212372f91826a008f87015163cc5cb/src/main/java/com/iota/iri/network/Node.java#L415) is there when responding to a random tip request:

`transactionRequester.numberOfTransactionsToRequest() > 0`

Imo this is totally out-of-place.

![image](https://user-images.githubusercontent.com/13155183/40383106-55acc770-5e00-11e8-8432-4d3dec363d2f.png)

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by alon-e** [comment]
The reason for this conditional is the following:
step 1. the request is for a random tip - then it means the requester has nothing else to request and is synced.
step 2. if the node replies w/ a random tip *request* (b/c it doesn't have anything to request (`transactionRequester.numberOfTransactionsToRequest() == 0`) then you have a loop.

this is the reason for the `P_REPLY_RANDOM_TIP`.

and the actual `numberOfTransactionsToRequest` part is there so the node won't send wasteful packets (wasteful from it's PoV) - it will only send some random tip when it has a transaction to request for itself.

@gjeee I wouldn't call this a bug, but a protocol design choice, could you elaborate on why you think it's not needed?

**Comment by gjeee** [comment]
> and the actual numberOfTransactionsToRequest part is there so the node won't send wasteful packets (wasteful from it's PoV) - it will only send some random tip when it has a transaction to request for itself.


are you saying that the reply (with a random tip) is combined with a request of its own ??? really?

**Comment by GalRogozinski** [comment]
The way the IOTA gossip protocol works is that each time you request a transaction you also tell your neighbor about a transaction you know of.

**Comment by gjeee** [comment]
ok ok now i am beginning to understand....tx for the clarification. i will close the issue/discussion.
