### ISSUE TITLE
`setArrivalTime` publishes both in seconds and milliseconds

### ISSUE THREAD

**Issue by tsvisabo** [iotaledger/iri#766]
`setArrivalTime` publishes both in seconds and milliseconds

### Expected behaviour
arrivalTime should be published only as milliseconds since epoch

### Actual behavior
arrivalTime is published  as both seconds and milliseconds since epoch 

source 1: [src/main/java/com/iota/iri/network/Node.java](https://github.com/iotaledger/iri/blob/d59de9fbaa2432a7123d9a4d65a1555241fcd934/src/main/java/com/iota/iri/network/Node.java#L392)
source 2: [src/main/java/com/iota/iri/service/API.java](https://github.com/iotaledger/iri/blob/bc6b943368695ab266db31347c1752ba79dca846/src/main/java/com/iota/iri/service/API.java#L660)

### Am I planning to do it myself with a PR?
No.

**Comment by alongalky** [comment]
This caused a nasty bug in [CLIRI](https://github.com/iotaledger/cliri), and it's a problem for any actual uses of `arrivalTime`. It makes transactions sent by one's own node appear much older than everyone else's.

**Comment by GalRogozinski** [comment]
In `SnapshotServiceImpl#isOrphaned` we also calculate the arrival time

**Comment by georgmittendorfer** [comment]
In SnapshotServiceImpl#isOrphaned the arrival time is only used. It is converted to seconds there. So the code assumes it is in millis and that seems to be correct (I am not completely sure as I don't fully understand the code there).

**Comment by GalRogozinski** [comment]
`timestamp` is in seconds. Make sure you differentiate it from `arrivalTimestamp`.
