### ISSUE TITLE
Measure quality and performance of the TipSelection algorithm

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#767]
### Description
Run `transactionsToApprove` and collect information

### Motivation
In order to compare the current implementation with any future implementations metrics on the quality of tips and runtime need to be collected.

### Requirements
Run `transactionsToApprove` multiple times over a variety of nodes and depths, and collect the following metrics:

- [x] `duration` of API call

- [x] check `timestamps` of tips to see how old they are (compare to local time)

- [x] count # of times `trunk == branch` when calling `transactionsToApprove`

- [x] count # of times each `transactionHash` is selected as a tip

- [x] count # of times a `milestone` is selected as a tip

- [x] count # of times returned transactions are not actual tips (check `findTransactions::approvees`)

This should be a standalone tool - that can be used to monitor mainnet tip selection performance, as well as be integrated in CI (run on a predefined DB) to create a baseline for future algorithmic changes

### Open Questions (optional)

- Any other valuable metrics?

**Comment by Johnny-Milkshakes** [comment]
Check if selected tip is actually a tip and if not check reason for stopping?

**Comment by GalRogozinski** [comment]
@alon-e 
With the new tip selection algo (which will soon be presented to the community), to get the last metric (not actual tip) we need to enable zmq logging.

**Comment by tsvisabo** [comment]
- About `count # of times each transactionHash is selected as a tip`:
  I think it is highly correlated with tanglescope's blowball metric. For tests on static tangles w/o 
  tanglescope it may be a good metric.
- `Run transactionsToApprove multiple times over a variety of nodes and depths`
  Do we want to test the tip selection or to continuously monitor it? if we want to monitor it, so then we do 
  that continuously with a configurable `test_interval`
  what are `depths`? how many do we want to test against? what are the values? i think that for each 
  depth there should be a single histogram so we can have comparisons (@GalRogozinski  suggests 
  that depths will range from 1-15)
- If we want to monitor this data via `tanglescope`, then `duration` includes also network latency, @GalRogozinski  suggests that both IRI and the monitoring application will be on the same machine 
- There could be bunch of other metrics we could try to measure, for example POBLB (probability of being left behind)

**Comment by alon-e** [comment]
@galrogo that is why I wrote: check `findTransactions::approvees` - meaning fetch (via API) all the approvers of the selected tips - if they have any then they are not tips.
this should be done in proximity to the first call.

@tsvisabo 
correlation does not imply causation - "blowballs" can appear even if the generic tip selection algo doesn't select the same tips often, for example, if someone is creating blowballs on purpose.

depth == how many milestones back should the walkers start from. yes, I agree that 1-15 is a good range to start w/ having 5(?) sample points - the wallet's default depth is 3. so `[1, 3, 6, 10, 15]`?

the `duration` is a parameter in the API response, you can use it. but I guess also network latency shouldn't be too bad - let's focus here on creating the tooling, later we can discuss how to deploy it; as I mentioned in the issue - I envision it has 2 purposes: 1. monitoring mainnet a la `tangleScope` 2. creating a baseline for regression.

re: POBLB - let's start off by collecting these stats and see from there. afaik POBLB is not defined for a single tip ([paper](https://assets.ctfassets.net/r1dr6vzfxhev/6FMwUH0b4WIyi6mm8oWWgY/8f1d7b30f7b652098a5e68b6634c63df/POLB-02.pdf)) and even if so, it's not something you can do natively in IRI currently.

**Comment by tsvisabo** [comment]
@alon-e , sure, but then when you expect correlation (say 100%) and you don't find it, that means that there's missing variance which lies somewhere else, and that might trigger an alarm

**Comment by tsvisabo** [comment]
BTW, `# trunk == branch` and `# transactionHash` could be two different metrics, but we can also just report frequencies/histogram, (e.g, run tip selection 10 times, 20 tips are selected, 10 seen once, 3 seen twice, 1 seen 4 times)  
unless there's a dependency between trunk/branch tip selection the distinction is meaningless.

**Comment by GalRogozinski** [comment]
@tsvisabo will be in charge of continous monitoring with tanglescope

**Comment by tsvisabo** [comment]
@alon-e 
I think that for each of the above new metrics, Tangle's `width` is an important factor that should be reflected in the metrics, either by reporting for different width categories or by "normalizing" the metrics

**Comment by GalRogozinski** [comment]
We now have Jmeter tests that do that
