### ISSUE TITLE
Neighbors with DDNS disconnected when IP Changed

### ISSUE THREAD

**Issue by alberk8** [iotaledger/iri#790]
### Bug description
Connect to a Neighbor what use FQDN but uses DDNS.  When the IP change the neighbor will not be able to connect back even though the DDNS is updated with the correct IP.  

### Hardware Spec
On what hardware is the node running on?
Intel i5 with IRI 1.4.2.4

### Steps To Reproduce
1. Connect to a Neighbor with FQDN but uses DDNS for IP resolution
2.  Ask the neighbor to disconnect network connection (reset router/modem), re-establish network connection and update DDNS with new IP.

### Expected behaviour
IRI should recognize the new IP from the FQDN and reconnect to the neigbor

### Actual behavior
IRI does not reconnect and will only do that when the node is restarted.

**Comment by rajivshah3** [comment]
Shouldn’t the DNS refresh pick up those changes?

**Comment by alberk8** [comment]
No, only a restart of IRI will fix the issue.

**Comment by jojoCoWorker** [comment]
This issue doesn't exist anymore since network rewrite in v1.8.0
I think we can close it
