### ISSUE TITLE
Refactor the hash class 

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#798]
### Description
Rewrite the code to adhere to SOLID principles

### Motivation
Increase the maintainability and adaptability of our hash code

### Requirements
- [x] Hash should be an interface that implements `Indexable` and `HashId` not a concrete object anymore 
- [x] Use `TransactionHash`, `AddressHash`, `TagHash`, `BundleHash` in the implementation
- [x]  There may be an an abstract class `AbstractHash` between the implementations and the interface so we adhere to DRY.
- [x] `Calculate` should be a static factory method in `TransactionHash`. It can be removed from the other implementations.
- [ ] Note: `Hash` is not a really good name. We may need to find a new name (out of scope).

**Comment by kwek20** [comment]
@jakubcech @galrogo 
I should keep an eye on the way we do lazy loading right? This guy touches it somewhat.
https://iota.stackexchange.com/questions/1803/why-were-4-byte-integers-chosen-as-the-best-way-of-storing-individual-trits-with?rq=1

Also, should i do this one first?
https://github.com/iotaledger/iri/issues/880

Or leave it and keep calling the current constuctor?

**Comment by kwek20** [comment]
@jakubcech @galrogo

What about an ObsoleteTagHash class? Required or just use TagHash?
I would say that we just make it, no idea until we have the obsoleteTag, and this way we can distinguish

**Comment by GalRogozinski** [comment]
I would use ObsoleteTagHash since we still have it in IRI.
But I don't think we need CoordinatorHash.
