### ISSUE TITLE
Unable to connect to node on eth0 interface

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iri#8]
I'm running the IRI on a VPS, and I notice that it will process HTTP requests sent to localhost, but if I send HTTP requests to its public IP, I get connection refused:

```
> curl -X POST --data '{"command": "getNodeInfo"}' http://localhost:14265
{"appName":"IRI","appVersion":"1.1.1", ...}

> curl -X POST --data '{"command": "getNodeInfo"}' http://<public ip>:14265
curl: (7) Failed to connect to <public ip> port 14265: Connection refused
```

Not 100% sure how to repro, but I get this issue consistently on a DigitalOcean VPS running Fedora 24 64-bit.

Here are the network interfaces on this VPS:

```
> ip addr
1: lo: <LOOPBACK,UP,LOWER_UP>
inet 127.0.0.1/8 scope host lo
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP>
inet <public ip> scope global eth0
```

I might be diagnosing the issue incorrectly, but I think something is going on with the IRI:

- I confirmed that the firewall is not blocking port 14265.
- I stopped the IRI and started a basic node.js HTTP service listening on port 14265, and it worked as expected.

**Comment by todofixthis** [comment]
Additional info from [Slack](https://iotatangle.slack.com/archives/newbies/p1480285037000007) (copying it here so that it doesn't get lost due to the 10k message limit):

> Heya.  I need a little help getting my first headless node up and running.
> 
> I'm running IRI-1.1.1.1 on a VPS.  I've got a few neighbors configured, and I believe my node is successfully downloading/propagating transactions:
> 
>     IRI 1.1.1.1
>     Transactions to request = 2 / 3604 (896 ms / 0%)
>     Latest milestone has changed from #6000 to #6256
>     Latest SOLID SUBTANGLE milestone has changed from #6000 to #6254
>     Transactions to request = 2 / 3604 (238 ms / 0%)
>     Transactions to request = 2 / 3605 (219 ms / 50%)
>     Transactions to request = 1 / 3605 (198 ms / 0%)
>     ...
> 
> However, I am unable to send any requests to my node.
> 
> It works if I send the command from an SSH session on the instance:
>
>     curl -X POST --data '{"command": "getNodeInfo"}' 'http://localhost:14265'
>     {"appName": "IRI", "appVersion": "1.1.1.1", ...}
> 
> However, if I try the same from my local machine, I get connection refused:
> 
>     curl -X POST --data '{"command": "getNodeInfo"}' 'http://<ip address>:14265'
>     curl: (7) Failed to connect to <ip address> port 14265: Connection refused
> 
> I'm pretty sure iptables is not blocking port 14265.  I added a logging rule and tailed the system log as I sent requests against various ports; other ports got logged and blocked, but not 14265.
> 
>  The plot thickens.  If I run an HTTP server on my VPS, it works as expected:
> 
>     # VPS
>     > cat test.js
>     var http = require('http');
>     
>     var server = http.createServer(function(request, response) {
>       response.writeHead(200, {'Content-type': 'text/plain'});
>       response.end('Hello, world!\n');
>     });
>     
>     server.listen(14265);
>     
>     > node test.js
>     
>     # localhost
>     > curl http://<ip address>:14265/
>     Hello, world!
> 
> Is it possible that IRI is listening on the wrong interface, perhaps?
> 
> Just to be sure, I tried compiling and running v1.1.1 from source, but I got the same result.

**Comment by knarz** [comment]
This is the intended behaviour because exposing the API to the outside world would mean that anybody could just run any command on your node.

If you are sure that you want to change this then your best bet would be to run an nginx as a reverse proxy, which would then also allow you to do basic auth to secure your node.

You could also change the listener here https://github.com/iotaledger/iri/blob/master/src/main/java/com/iota/iri/service/API.java#L78 to `0.0.0.0` which should then listen on all interfaces.

**Comment by todofixthis** [comment]
Good point.  I'm-a close this issue then.

**Comment by todofixthis** [comment]
Adding some context for anyone researching related issues:

- The API only listens on the loopback interface.  If you want to send API requests to your node, it has to be on localhost.  The port number is hard-coded to 14265.  [source](https://github.com/iotaledger/iri/blob/d4df2fc/src/main/java/com/iota/iri/service/API.java#L78)
- The Node service listens on the public interface.  The port number is determined by the port argument provided to `java -jar iri.jar <port> <neighbor> [<neighbor> [...]]` [source](https://github.com/iotaledger/iri/blob/d4df2fc/src/main/java/com/iota/iri/service/Node.java#L56)
