### ISSUE TITLE
As a user, I want to be able to resolve common, known issues with IRI

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#814]
### Description
There are common issues (often) related to running IRI on specific set-ups and platforms. These should be ideally addressed in a 'Troubleshooting' section of the IRI documentation for users to find.

### Motivation
Resolving most common issues by find-able documentation with resolutions instead of addressing them one by one. 

### Requirements
1. User navigates to the IRI documentation.
2. Finds a section regarding common issues and their workarounds. 
3. Can see a resolution to the issue he has with steps 
OR 
finds instructions on how to create a task to improve the documentation or change the documentation herself. 

### Known candidates

1. https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty

**Comment by rajivshah3** [comment]
I'd be happy to help with this if needed. Maybe the "Troubleshooting" section could be added to https://docs.iota.org/iri ?

**Comment by jakubcech** [comment]
Great, thanks. That's exactly what I'm going to do today. Happy if you contribute to the topic afterwards. :)
