### ISSUE TITLE
Store database snapshots corresponding to every major release for IRI

### ISSUE THREAD

**Issue by akashgoswami** [iotaledger/iri#826]
### Description
The database snapshots for older releases are hard to find once everyone has upgraded the IRI. 
As a result, older releases can't be tested and migration problems are hard to reproduce. 
With every major release, a snapshot of the current database should be taken and stored in a backed up storage (S3). Testnet DB backup should be mandatory and Mainnet backup would be nice to have. 

This will ensure that we could always go back in time and see if the performance were better/worse and what problems will be faced by someone migrating from the older releases to the newer one. 

### Motivation
In a distributed ledger - there is no central authority which could maintain the backup of the database. Since IF is responsible for overall software state of IRI, this should be done by IF. 

### Requirements
Take a snapshot of the database prior to the release of a new version and archive it in a publicly accessible repository. 

### Am I planning to do it myself with a PR?
No.

**Comment by GalRogozinski** [comment]
We are doing that
