### ISSUE TITLE
Travis: deploy doesn't upload all files

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#832]
### Bug description
Files generated as part of the `deploy` process are not uploaded - only files that existed beforehand are uploaded.
Seems `files` is indexed before deploy starts.

### Steps To Reproduce
deploy a release.
You'll see that `iri-1.5.0-javadoc.jar  iri-1.5.0-sources.jar iri-1.5.0.jar.asc` are not added, even though they exist in targets.

### Expected behaviour
all `*.jar*` files should be included in the release (https://github.com/iotaledger/iri/blob/dev/.travis.yml#L57)

### Actual behavior
on the pre-existing files are included: `iri-1.5.0.jar original-iri-1.5.0.jar`

**Comment by GalRogozinski** [comment]
Closing since we are not using travis for this anymore
