### ISSUE TITLE
Investigate if we're able to run tests in parallel in BuildKite

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#834]
Investigate if we're able to set up the ability (infrastructure) to run in parallel (even if we don't run in parallel yet)
http://www.agilosoftware.com/blog/bdd-and-test-parallelisation-with-lettuce/

Need to talk with @geminoz about BuildKite

**Comment by jakubcech** [comment]
https://github.com/iotaledger/iri-regression/issues/3

**Comment by th0br0** [comment]
You are. https://buildkite.com/docs/builds/parallel-builds
