### ISSUE TITLE
Integrate BuildKite

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#839]
### Description
We want to set up a CI integration with BuildKite to replace the current Travis integration. The integration should do everything that the current Travis integration does. 

### Requirements
- [ ] Should do the same that Travis except the release deployment.
- [ ] BuildKite results need to be public.

**Comment by geminoz** [comment]
Quick comment to confirm this is a work in progress

**Comment by rajivshah3** [comment]
> BuildKite results need to be public.

It looks like they're testing this in a private beta now: 
https://forum.buildkite.community/t/getting-started-with-public-builds/43

**Comment by geminoz** [comment]
Nice catch. Just emailed support to know if we can have an early access of the feature
