### ISSUE TITLE
[Question] Difference between original iri and iri?

### ISSUE THREAD

**Issue by mrbianchi** [iotaledger/iri#851]

**Comment by mrbianchi** [comment]
closed without answer

**Comment by miili** [comment]
This is GitHub, not reddit.

**Comment by jakubcech** [comment]
Hey, please use [Discord ](https://discordapp.com/invite/fNGZXvh) for questions like these. And refer to our [Contribution guidelines](https://github.com/iotaledger/iri/blob/dev/CONTRIBUTING.md). Thanks

**Comment by iotarin** [comment]
Useless answer @miili , I know that it isn't reddit
@jakubcech I asked it 25/05/2018 but no answers , the same question is asked by another users without answer

Sorry by using this platform
