### ISSUE TITLE
Figure out why the checkConsistency calls fail

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#899]
### Description
The JS library obfuscates the exceptions coming from the `checkConsistency` call, let's de-obfuscate and reproduce the issues. We need to figure out in which section we fail and whether this is a regression or not - we've made two changes to `checkConsistency` recently:
- stop if the transaction is not solid
- addition of `belowMaxDepth`

Note: Chris is working on the client call de-obfuscation.

**Comment by chrisdukakis** [comment]
Hey @jakubcech  & @GalRogozinski ,
I've created two pull requests for `develop (iota.lib.js)` & `next (@iota/core)` branches:

https://github.com/iotaledger/iota.lib.js/pull/255
https://github.com/iotaledger/iota.lib.js/pull/251

To print exceptions, `checkConsistency` should be called with `rejectWithReason: true` option:
```
npm i @iota/core @iota/http-client
```
```js
const { createCheckConsistency } = require('@iota/core')
const { createHttpClient } = require('@iota/http-client')

const provider = createHttpClient({ provider: 'http://..' }) // <- change to your node uri
const checkConsistency = createCheckConsistency(provider)

const tail = 'TAIL9HASH...'

checkConsistency(tail, { rejectWithReason: true })
   .then(state => console.log(`State is: ${state}`))
   .catch(err => console.log(`Check failed, reason: ${err}`))
```

**Comment by cyclux** [comment]
In my latest test the API fails with:
Error: Inconsistent subtangle

The problem is occuring 100% of the time now.

**Comment by alon-e** [comment]
>In my latest test the API fails with:
>"Error: Inconsistent subtangle"
@cyclux This eherror obfuscates the real reason why IRI fails on the transaction - any error would trigger the same response.
in Chris' version, the error message is revealed.
Can you run w/ that version? or call IRI directly?
(you can use:)
```
curl -H 'X-IOTA-API-Version: 1' -H 'Content-Type: application/json' -d '{"command":"checkConsistency", "tails":["NDMGKNFYSRFNCGLXWEDBRLDJLRUJEIYGKIHLIDKCHDSMENOORWVEFGRCRGWAEEPCAHHASLVORTHM99999"]}' $URL1 | jq
```

**Comment by gjeee** [comment]
@alon-e my node shows the following. so this confirms indeed the discrepancy you demonstrated in issue #898

![image](https://user-images.githubusercontent.com/13155183/43686751-3ca57802-98cb-11e8-9d8d-5cb7dceb8708.png)

**Comment by cyclux** [comment]
So tested it now with several different nodes and bundles, always get an error like this:
```tails are not solid (missing a referenced tx): SLYTWMSGYWYMBUDPJPRPAMOHHFLFDVABFQNWLZHIYXYSMXEEHSNGSPCSGGVPOIJCINPSHBDGMZELA9999"```

**Comment by gjeee** [comment]
@cyclux PR #913 will fix this as well: before this fix, it did set the solid field to true but forgot to store it (for txs where both its trunk and branch are solid). this has big consequences on all the routines which rely on #TransactionViewModel.isSolid():

- like the #WalkValidatorImpl .isValid() step in the random walks
- but also in the #TransactionValidator.checkSolidity() routine which unintentionally is deeply recursing because of this
