### ISSUE TITLE
Error response has 200 status

### ISSUE THREAD

**Issue by todofixthis** [iotaledger/iri#9]
If a node is unable to fulfill a command because of an error, I think the response should have a non-200 status code (i.e., 400/500).

```
> curl -X POST -D- --data '{"command": "foo"}' 'http://localhost:14265'
HTTP/1.1 200 OK  <-- s/b 400 Bad Request?
...

{"error":"Command \u0027foo\u0027 is unknown","duration":0}
```

Checking the status code is an easy way for a client to get a quick idea of whether the request succeeded without having to decode the response body.

**Comment by davassi** [comment]
Agree. Fix on the way...

**Comment by davassi** [comment]
Issue Fixed with the last commit.
