### ISSUE TITLE
As a developer, I want to be able to decode the gossip protocol

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#916]
### Description
We need a wireshark plugin to decode the gossip protocol at the wire level. This will be useful while analyzing packet drops and performance issues. 

### Requirements
The plugin should be able to decode both TCP and UDP payloads
Since port number of the gossip protocol could be changed on the fly, the use must be able to choose the payload and select decode as IOTA Gossip.

- [ ] Different TX fields broken down in trytes. 
- [ ] Fields will be converted into human-interpretable format.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes

**Comment by akashgoswami** [comment]
Uploaded to https://github.com/iotaledger/wireshark-dissector

**Comment by alon-e** [comment]
great tool!
added a request and submitted a PR :)
would be great to make this repo public if you feel it's ready.
