### ISSUE TITLE
Use RESTEasy implementation of JAX-RS

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#920]
### Description
Use RESTEasy implementation of JAX-RS.
https://github.com/resteasy/Resteasy

We want API.java to only handle receiving the API calls.
Any application logic should be handled by underlying services.

### Motivation
We want the code up to SOLID standards.
https://github.com/iotaledger/iri/pull/392/ is an example of what we want from the code.

### Requirements
1. No long methods with `switch`
2. No application logic in API.java. Only parameter validation.

**Comment by GalRogozinski** [comment]
We will change the code to adhere to #874 after we refactor it to be more amendable
