### ISSUE TITLE
Boolean configuration flags have undefined behavior

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#930]
### Bug description
This is a follow up on #910.
The following boolean flags that are *true by default* and have to be set to false like so:
`--dns-refresher false`
`--dns-resolution false`

However other flags that are *false by default* are set to true w.o specifying value, e.g.
`--rescan`

### Expected behavior
Either use a disabling flag:
`--disable-dns-refresher` 

**Or enforce passing a value:**
 `--rescan true`

Edit:
We need to give a good error message if we go with option num. 2 and if the flag is used without a passing value. 

We need to understand what and how we break things and document it properly.

**Comment by jakubcech** [comment]
I'm for enforcing passing a value

**Comment by jakubcech** [comment]
Check whether this breaks the docker file.

**Comment by jakubcech** [comment]
#1047

**Comment by karimodm** [comment]
For what solution approach are we settling on? I am prone to avoid any ambiguity and always go for arity >0, "enforce passing a value: --rescan true" approach.

**Comment by jakubcech** [comment]
Yes, we agreed on arity > 0 aka enforce passing a value. :)

**Comment by jakubcech** [comment]
This still in review or were there changes to be made here @kwek20?

**Comment by GalRogozinski** [comment]
We still need to fix aloe tests and travis.
I want to fix aloe tests first, and then when it passes we will fix Travis

**Comment by kwek20** [comment]
@GalRogozinski All fixed, see the linked PRs in #1295
