### ISSUE TITLE
Integrate aloe regression tests into legacy regression repo

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#934]
### Description
Simplify iri-regression so that we can have a temporary solution that we can integrate with Travis instead of waiting for BuildKite.  

The node would sit on a Travis machine for now. 

### Motivation
We're currently not utilizing the existing tools, we could just expand on the existing regressionrepo. 

### Requirements
Create a list of what you want this feature request to fulfill.

### Open Questions (optional)
Anything you want to discuss.

### Am I planning to do it myself with a PR?
Yes/No.

**Comment by karimodm** [comment]
Since BuildKite is somewhat already here, should we consider this issue as "Rejected"?

**Comment by karimodm** [comment]
Can we close this one @jakubcech ?
