### ISSUE TITLE
Full node / Impossible to reach API 

### ISSUE THREAD

**Issue by Philconee** [iotaledger/iri#948]
### Bug description

Hi, I'm running a node on my computer but impossible for me to reach the api on localhost : 

```
curl http://localhost:14265 \
-X POST \
-H 'Content-Type: application/json' \
-H 'X-IOTA-API-Version: 1' \
-d '{"command": "getNodeInfo"}'
```
respond : 

`Connection refused on 14265`

Idk if it is linked, but transaction "torequest" is still 0 :

![issue_iota](https://user-images.githubusercontent.com/35865627/44514494-934c8f80-a6c0-11e8-9d7f-9c8ac902309c.png)

Thank you ! 👍

**Comment by GalRogozinski** [comment]
Github is for opening issues or asking for feature requests.

Questions should go to common IOTA discussion boards:

https://forum.helloiota.com/
https://iota.stackexchange.com
https://www.reddit.com/r/Iota/
discord
