### ISSUE TITLE
Release IRI 1.5.5

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#951]
### Description
Release new version of IRI. We agreed on the following network flow when releasing a new version.

1. Canary Spamnet
1. Spamnet 
1. Canary Mainnet 
1. Upgrade our Mainnet nodes 
1. Release 
1. Entire Mainnet

**Comment by GalRogozinski** [comment]
We need to discuss how API documentation is released exactly.
For the next release they should be generated manually but we shouldn't forget about future releases.

**Comment by GalRogozinski** [comment]
@kwek20 can you arrange a repository for the API docs?

**Comment by DyrellC** [comment]
@geminoz has set up 5 nodes on the spamnet with the new release branch. I think we should organise a mass spamming event to gather some metrics before we replace the other 5.

**Comment by jakubcech** [comment]
We still need to merge the snapshot into the branch.
