### ISSUE TITLE
getTrytes API contract is broken if TxVM returns null

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#965]
### Bug description
`getTrytes` receives N hashes and returns N transactions which contain the trytes or `999` if it is missing.
in the case where `TxVM.fromHash()` returns `null`, then the resulting list of transactions will be shorter than N, and the mapping from hashes to transactions is broken.

https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/service/API.java#L564-L566

### Expected behaviour
return N elements, `999` if missing

### Actual behaviour
shorter list

### Errors
Paste any errors that you see.

**Comment by 7h7** [comment]
I think it should return an error message, that a transaction is missing and not just `999`

**Comment by GalRogozinski** [comment]
I know from @muXxer that hornet uses the `999` solution but he agrees that the error message is better.

Unless I get any objections we will start returning an error

**Comment by obany** [comment]
I don't think an error message is the correct response.

If you have a scenario where some of the transactions do exist you still want them returned, not an error.

In my opinion returning the list with trytes, null or 9s with indexes matching the input hash list is the correct response.

Ideally it would be 9s if the transaction did exist but we no longer have the data and null if the transaction never existed. This will then tell you the state of the transactions within that node.

**Comment by GalRogozinski** [comment]
null is now put in the response instead of providing a shorter list
