### ISSUE TITLE
Connection to DDNS neighbors lost after IP change

### ISSUE THREAD

**Issue by thudenska** [iotaledger/iri#979]
### Bug description
IRI doesnt update neighbors IP for neighbors using Dynamic DNS services. When neighbors dynamic IP changes it keeps trying to connect to its old IP.

### Hardware Spec
VPS, CentOS 7, IRI Playbook Setup

### Steps To Reproduce
1. Add neighbor via DDNS FQDN
2. Change neighbors IP

### Expected behaviour
IRI should check frequently for changed IP on neighbors that are added with an FQDN.

### Actual behaviour
After a neighbors IP changes IRI keeps trying to connect to his old IP. After a restart of the IRI service IPs seem to be updated and it can connect to neighbors with changed IP again.

### Errors
-

**Comment by nuriel77** [comment]
You didn't start up IRI with this flag by any chance? `--dns-resolution-false`

**Comment by jojoCoWorker** [comment]
I'm also trying to run IRI behind dynamic IP so I'm using dynamic DNS services (no-ip). I can provide any logs, perform any tests...
I saw sometimes IRI keeping several domain names for the same neighbor, then iri seems to send transactions to those several domain names for the same neighbor initially. Connexions are often lost and come back generally when a neighbor "cleans" iri DNS resolution restarting.

**Comment by jojoCoWorker** [comment]
I discovered you can't really see what happens using curl command line "getNeighbors". The tool Iota Peer Manager let me "see" the new IPs and I can see that peering is ok whereas the curl command shows me there is no more NewTransctions received :
![image](https://user-images.githubusercontent.com/33653820/46468964-4933ef00-c7d2-11e8-880d-098dc68fa961.png)
On that image, we can see each neighbor appears on peer manager view but one is "doubled", we can see his FQDN and his new IP (I deleted the previous IP). It seems IRI continues to send TX to the FQDN and to the new IP but only the new IP returns new TXs.
The curl command doen't show the new IP...

**Comment by jojoCoWorker** [comment]
My IP changed this morning and that killed connections with 2 out of 3 of my neighbors... Will this problem be taken in account onde day ? It's quite impossible to run a full node in those conditions... I suppose I'm not the only one to connect behind a dynamic IP...

**Comment by jojoCoWorker** [comment]
New IP change 10 minutes ago (maybe my ISP doesn't like my internet activity...) the only neighbor who stays connected to my nodes is under UDP protocol whereas very often TCP is easier to connect in my case.

**Comment by jakubcech** [comment]
Hey, thanks for reporting this. The plan is for taking this up during the next sprint. :) The current sprint ends next week.

**Comment by jojoCoWorker** [comment]
If ever that can help, I suppose it's linked to the DNS management in IRI, Here is what I can see today with Iota Peer Manager :
![image](https://user-images.githubusercontent.com/33653820/46920120-afe2b500-cfe9-11e8-8836-6fa3e6a7da61.png)
192.168.1.20 is exactly the same machine as rig1.home, however IRI seems to send TXs differently to those 2 addresses.

**Comment by nuriel77** [comment]
Does `rig1.home` have a PTR (reverse) DNS record?
You can check that with `dig` from the package `bind-utils` in CentOS (or `dnsutils` in Ubuntu)

Example:
```
dig -x 192.168.1.20
```
Should return `rig1.home` in `;; ANSWER SECTION:`

**Comment by jojoCoWorker** [comment]
on ```rig1.home``` :
```;; ANSWER SECTION:
20.1.168.192.in-addr.arpa. 0    IN      PTR     rig1.home.
```
got same answer if I run that dig command on the machine where rig1 is the neighbor.

**Comment by f-ben** [comment]
Looks like this is still an issue on my node. Is there any more information needed I can supply to get this fixed?

**Comment by GalRogozinski** [comment]
#1255 should have solved this

**Comment by jojoCoWorker** [comment]
Nothing really changed for me
IRI 1.7.0-RELEASE installed with Nuriel's playbook docker version
I have one of my 4 neighbors behind a DDNS like me, his IP changed those last 24 hours and here is what I can see on my logs :
```
mai 04 16:40:54 yoann-virtualbox docker[8928]: 05/04 14:40:54.746 [pool-12-thread-3] INFO  com.iota.iri.network.Node - Checking Neighbors' Ip...
mai 04 16:40:55 yoann-virtualbox docker[8928]: 05/04 14:40:55.053 [pool-12-thread-3] INFO  com.iota.iri.network.Node - DNS Checker: Validating DNS Address 'iotanode.blabla.de' with '89.245.XX.XX'
[...]
mai 04 16:42:37 yoann-virtualbox docker[8928]: 05/04 14:42:37.929 [pool-14-thread-21] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 89.245.YY.YY
mai 04 16:42:37 yoann-virtualbox docker[8928]: 05/04 14:42:37.930 [pool-14-thread-19] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 89.245.XX.XX
mai 04 16:42:37 yoann-virtualbox docker[8928]: 05/04 14:42:37.931 [pool-14-thread-19] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 89.245.XX.XX
mai 04 16:42:37 yoann-virtualbox docker[8928]: 05/04 14:42:37.931 [pool-14-thread-21] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 89.245.YY.YY
mai 04 16:42:38 yoann-virtualbox docker[8928]: 05/04 14:42:38.087 [pool-14-thread-19] INFO  c.i.i.n.r.ReplicatorSinkProcessor - ----- NETWORK INFO ----- Sink 89.245.XX.XX is connected
mai 04 16:43:07 yoann-virtualbox docker[8928]: 05/04 14:43:07.948 [pool-14-thread-21] ERROR c.i.i.n.r.ReplicatorSinkProcessor - ***** NETWORK ALERT ***** No sink to apiHost 89.245.YY.YY:15600, reason: connect timed out
mai 04 16:43:07 yoann-virtualbox docker[8928]: 05/04 14:43:07.949 [pool-14-thread-21] INFO  com.iota.iri.network.Neighbor - Sink 89.245.YY.YY closed
mai 04 16:43:37 yoann-virtualbox docker[8928]: 05/04 14:43:37.930 [pool-14-thread-6] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Opening sink 89.245.YY.YY
mai 04 16:43:37 yoann-virtualbox docker[8928]: 05/04 14:43:37.931 [pool-14-thread-6] INFO  c.i.i.n.r.ReplicatorSinkProcessor - Connecting sink 89.245.YY.YY
mai 04 16:43:47 yoann-virtualbox docker[8928]: 05/04 14:43:47.628 [pool-14-thread-19] ERROR c.i.i.n.r.ReplicatorSinkProcessor - ***** NETWORK ALERT ***** No sink to apiHost 89.245.XX.XX:15600, reason: Socket is closed
mai 04 16:43:53 yoann-virtualbox docker[8928]: 05/04 14:43:53.335 [pool-14-thread-6] ERROR c.i.i.n.r.ReplicatorSinkProcessor - ***** NETWORK ALERT ***** No sink to apiHost 89.245.YY.YY:15600, reason: No route to host (Host unreachable)
mai 04 16:43:53 yoann-virtualbox docker[8928]: 05/04 14:43:53.336 [pool-14-thread-6] INFO  com.iota.iri.network.Neighbor - Sink 89.245.YY.YY closed
```
I just changed yesterday IP with 89.245.YY.YY and today IP with 89.245.XX.XX
His FQDNS is written here as iotanode.blabla.de
So we can see that DNS Address is well validated but IRI still tries to connect to the old IP...

That's a very boring problem when you try to find neighbors, in statistic tools, new IP's are considered as new neighbors and the statistics in front of FQDNS look like node is dead...

IRITop :
![image](https://user-images.githubusercontent.com/33653820/57180949-1946ea00-6e8e-11e9-9dcc-e0ff04b69558.png)

IOTA Peer Manager :
![image](https://user-images.githubusercontent.com/33653820/57181030-de918180-6e8e-11e9-9345-529f9b31b933.png)

Neighbor's list with playbook interface :
![image](https://user-images.githubusercontent.com/33653820/57181060-72fbe400-6e8f-11e9-948a-28178b906308.png)

**Comment by georgmittendorfer** [comment]
#1255 only fixed unwanted dns resolving for UDP neighbors that got added with IP (not FQDN). So this issue is not directly related to the fix mentioned above imo.

**Comment by jojoCoWorker** [comment]
Maybe I can help, being clearer or going deeper...
It seems [ReplicatorSinkProcessor](https://github.com/iotaledger/iri/blob/dev/src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java) uses a neighbors IP list that is not updated...

I unfortunately can't read java but I think there is 2 different ways to get rid of this :

1. The "maybe too easy way" : It's not necessary to use IP list, we can keep a HostName list everywhere in the code and there would be nothing to update because the Hostname allways links to the right IP...

2. The 2nd way IMHO : a "real Dev" should find the place in the code where a new neighbor is added as soon as another IP is resolved from the same DNS, the old IP should disappear from neighbors IP lists instead of a reverse DNS Lookup being added to the neighbors HostName list...

**Comment by jojoCoWorker** [comment]
This issue doesn't exist anymore since network rewrite in v1.8.0
I think we can close it

**Comment by jakubcech** [comment]
Should be fixed now. Reopen if nay. Thanks!
