### ISSUE TITLE
Review snapshot logic for local snapshots

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#980]
Review the separate parts of local snapshots:

- [x] [Feat: added config variables for local snapshots](https://github.com/iotaledger/iri/pull/981)
- [x] [Feat: added a generic helper class for dag traversal](https://github.com/iotaledger/iri/pull/982)
- [x] [Feat: renamed Milestone to MilestoneTracker](https://github.com/iotaledger/iri/pull/983) **URGENT**
- [x] [Feat: Introducing the GarbageCollector of local snapshots](https://github.com/iotaledger/iri/pull/995)
- [x] [Feat: Introducing a dedicated MilestoneSolidifier for Local Snapshots](https://github.com/iotaledger/iri/pull/1001)

- [ ] ... more to come :)

**Comment by karimodm** [comment]
Made first review pass for:
 * Feat: added config variables for local snapshots
 * Feat: added a generic helper class for dag traversal
 * Feat: renamed Milestone to MilestoneTracker URGENT
