### ISSUE TITLE
Integrate Faucet with Hub

### ISSUE THREAD

**Issue by akashgoswami** [iotaledger/iri#991]
### Bug description
Faucet website currently uses the same Seed for distributing tokens.  As the source address space grows, walking through all of them while finding an unused address becomes time-consuming. This could be potentially fixed by integrating Faucet with Hub. 

### Expected behaviour
Faucet should work flawlessly even after distributing multiple tokens. 

### Am I planning to do it myself with a PR?
Yes

**Comment by jakubcech** [comment]
Hub is now up and running. :)
