### ISSUE TITLE
Travis has a hard coded merge with dev

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#993]
### Bug description
Currently travis always tries to merge to `dev` branch before testing: https://github.com/iotaledger/iri/blob/dev/.travis.yml#L32.

We need to have travis automatically merge to the upstream branch as described in travis docs:
https://docs.travis-ci.com/user/pull-requests#how-pull-requests-are-built
>Travis CI builds a pull request when it is first opened, and whenever commits are added to the pull request. Rather than build the commits that have been pushed to the branch the pull request is from, we **build the merge between the source branch and the upstream branch**.

### Expected behaviour
Travis should automatically merge to the correct upstream branch stored in `$TRAVIS_BRANCH`
### Actual behaviour
`$TRAVIS_BRANCH` contains the local branch and not the upstream branch

**Comment by alon-e** [comment]
>https://travis-ci.org/GalRogozinski/iri/jobs/429531222
>Here is an example build (from @GalRogozinski )
This is not a good example for 2 reasons:
1. this is actually a `push` trigger not a PR.
2. this PR is not `mergeable` so the latter (PR) did not trigger at all.
(more info: https://arturdryomov.online/posts/how-the-pull-request-is-built/)

see your PR doesn't even have Travis triggered.

example branch w/ both triggers: https://github.com/alon-e/iri/pull/14
so the Travis PR looks at: https://github.com/alon-e/iri/commit/c4c4180570075a3a02ddb73b39e0272daafe22eb
which is `Merge 8c936ab into f575913`

and finally: `echo $TRAVIS_BRANCH` returns
push: current branch: https://travis-ci.org/alon-e/iri/jobs/429777343#L678
PR: target/upstream branch: https://travis-ci.org/alon-e/iri/jobs/429777399#L682

Testing how to (re)trigger Travis on PRs when upstream changes.

**Comment by alon-e** [comment]
related issue: https://github.com/travis-ci/travis-ci/issues/1620

**Comment by alon-e** [comment]
actually,
while Travis UI does not update that the merge refs changed.
it seems like the underlying refs did actually change when rebuilding.
see: https://travis-ci.org/alon-e/iri/jobs/429777399#L702

so the whole explicit merge w/ upstream may not be relevant.
