### ISSUE TITLE
Can not run build target mvn javadoc:javadoc

### ISSUE THREAD

**Issue by legacycode** [iotaledger/iri#996]
### Bug description

I am working on documentation and can not run "mvn javadoc:javadoc" due to missing dependencies. In pom.xml there is a custom jar referenced.

```xml
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-javadoc-plugin</artifactId>
	<version>3.0.0</version>
	<configuration>
		<doclet>com.iota.mdxdoclet.MDXDoclet</doclet>
		<sourcepath>src/main/java</sourcepath>
		<useStandardDocletOptions>false</useStandardDocletOptions>
		<additionalOptions>
			<additionalOption>-version "${project.version}"</additionalOption>
		</additionalOptions>
		<quiet>true</quiet>
		<docletArtifact>
			<groupId>com.iota</groupId>
			<artifactId>mdxdoclet</artifactId>
			<version>0.1</version>
		</docletArtifact>
	</configuration>
</plugin>
```

### Steps To Reproduce
1. Execute "mvn javadoc:javadoc"

### Expected behaviour
Javadocs should be generated in target directory.

### Actual behaviour
Build error

### Errors
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.0:javadoc (default-cli) on project iri: An error has occurred in Javadoc report generation: Unable to resolve artifact:groupId = 'com.iota'
[ERROR] artifactId = 'mdxdoclet'
[ERROR] version = '0.1': Failure to find com.iota:mdxdoclet:jar:0.1
```

### Motivation
I want to document the source code and would like to verify the result.

### Requirements
com.iota doclet artifacts.

### Open Questions (optional)
1. Is this still actual or can it be replaced by a default one?
2. Where can i download this dependencies?
3. Ist there a custom iota repository i can use?

### Am I planning to do it myself with a PR?
Yes.

**Comment by kwek20** [comment]
Hey!

You can get the Doclet from here:
https://github.com/iotaledger/iri-mdx-doclet

We made this to generate markdown files for our documentation site(Coming soon-ish) automatically.
It should still run javadoc on the side though, I'll look into it
